
INSERT INTO public.additive_rulebook (
    additive_code, ins_number, canonical_name, functional_class, 
    jurisdiction, status, max_level_value, max_level_unit, 
    label_requirement, regulation_title, source_url, verification_status
) VALUES 
('E102', '102', 'Tartrazine', 'Colorant', 'IN', 'permitted', 100.0, 'mg/kg', 'Synthetic food color declaration required', 'FSSAI Food Additives Regulation 2.4.5', 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Food_Additives_Regulations_08_09_2020.pdf', 'verified'),
('E102', '102', 'Tartrazine', 'Colorant', 'EU', 'requires_warning', NULL, NULL, 'May have an adverse effect on activity and attention in children', 'EU Regulation 1333/2008 Annex V', 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32008R1333', 'verified'),
('E102', '102', 'Tartrazine', 'Colorant', 'US', 'restricted', NULL, NULL, 'FD&C Yellow No. 5 label disclosure required', '21 CFR 74.705', 'https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfcfr/CFRSearch.cfm?fr=74.705', 'verified'),
('E110', '110', 'Sunset Yellow FCF', 'Colorant', 'IN', 'permitted', 100.0, 'mg/kg', 'Synthetic food color declaration required', 'FSSAI Food Additives Regulation 2.4.5', 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Food_Additives_Regulations_08_09_2020.pdf', 'verified'),
('E110', '110', 'Sunset Yellow FCF', 'Colorant', 'EU', 'requires_warningCustom', NULL, NULL, 'May have an adverse effect on activity and attention in children', 'EU Regulation 1333/2008 Annex V', 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32008R1333', 'verified'),
('E150D', '150d', 'Sulphite Ammonia Caramel', 'Colorant', 'IN', 'permitted', NULL, NULL, 'Class IV Caramel Color', 'FSSAI Compendium Food Additives 2020', 'https://www.fssai.gov.in', 'verified'),
('E150D', '150d', 'Sulphite Ammonia Caramel', 'Colorant', 'US', 'requires_warning', NULL, NULL, 'Prop 65 Cancer warning required if 4-MEI exceeds 29 mcg/day', 'Cal. Code Regs. tit. 27 § 27001', 'https://oehha.ca.gov/proposition-65', 'verified'),
('E171', '171', 'Titanium Dioxide', 'Colorant', 'EU', 'banned', NULL, NULL, 'Banned due to non-excludable genotoxicity after nanoparticle accumulation', 'EU Regulation 2022/63', 'https://efsa.onlinelibrary.wiley.com/doi/10.2903/j.efsa.2021.6585', 'verified'),
('E171', '171', 'Titanium Dioxide', 'Colorant', 'IN', 'permitted', 100.0, 'mg/kg', 'Permitted under specific category limits', 'FSSAI Food Additives Regulation 2020', 'https://www.fssai.gov.in', 'verified'),
('E211', '211', 'Sodium Benzoate', 'Preservative', 'IN', 'permitted', 120.0, 'mg/kg', 'Preservative Class II', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E211', '211', 'Sodium Benzoate', 'Preservative', 'EU', 'permitted', 150.0, 'mg/kg', NULL, 'EU Regulation 1333/2008', 'https://eur-lex.europa.eu', 'verified'),
('E202', '202', 'Potassium Sorbate', 'Preservative', 'IN', 'permitted', 1000.0, 'mg/kg', 'Preservative Class II', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E300', '300', 'Ascorbic Acid (Vitamin C)', 'Antioxidant', 'IN', 'permitted', NULL, 'GMP', 'Antioxidant', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E319', '319', 'TBHQ (Tertiary Butylhydroquinone)', 'Antioxidant', 'IN', 'permitted', 200.0, 'mg/kg', 'Antioxidant in fats and oils', 'FSSAI Food Additives Regulation 2020', 'https://www.fssai.gov.in', 'verified'),
('E319', '319', 'TBHQ (Tertiary Butylhydroquinone)', 'Antioxidant', 'JP', 'banned', NULL, NULL, 'Banned due to immunotoxicity concerns', 'Japan Food Sanitation Act', 'https://www.mhlw.go.jp', 'verified'),
('E322', '322', 'Lecithins', 'Emulsifier', 'IN', 'permitted', NULL, 'GMP', 'Emulsifier / Stabilizer', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E330', '330', 'Citric Acid', 'Acidulant', 'IN', 'permitted', NULL, 'GMP', 'Acidity Regulator', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E331', '331', 'Sodium Citrates', 'Acidity Regulator', 'IN', 'permitted', NULL, 'GMP', 'Acidity Regulator', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E407', '407', 'Carrageenan', 'Thickener', 'IN', 'permitted', NULL, 'GMP', 'Thickener / Stabilizer', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E412', '412', 'Guar Gum', 'Thickener', 'IN', 'permitted', NULL, 'GMP', 'Thickener', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E415', '415', 'Xanthan Gum', 'Thickener', 'IN', 'permitted', NULL, 'GMP', 'Thickener / Stabilizer', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E422', '422', 'Glycerol', 'Humectant', 'IN', 'permitted', NULL, 'GMP', 'Humectant', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E440', '440', 'Pectins', 'Gelling Agent', 'IN', 'permitted', NULL, 'GMP', 'Gelling Agent', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E450', '450', 'Diphosphates', 'Emulsifying Salt', 'IN', 'permitted', 9000.0, 'mg/kg', 'Emulsifier / Raising Agent', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E466', '466', 'Sodium Carboxymethyl Cellulose', 'Thickener', 'IN', 'permitted', NULL, 'GMP', 'Thickener', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E471', '471', 'Mono- and Diglycerides of Fatty Acids', 'Emulsifier', 'IN', 'permitted', NULL, 'GMP', 'Emulsifier', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E476', '476', 'PGPR', 'Emulsifier', 'IN', 'permitted', 5000.0, 'mg/kg', 'Emulsifier in cocoa and chocolate products', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E500', '500', 'Sodium Carbonates', 'Raising Agent', 'IN', 'permitted', NULL, 'GMP', 'Raising Agent / Acidity Regulator', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E500II', '500ii', 'Sodium Bicarbonate', 'Raising Agent', 'IN', 'permitted', NULL, 'GMP', 'Raising Agent', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E503', '503', 'Ammonium Carbonates', 'Raising Agent', 'IN', 'permitted', NULL, 'GMP', 'Raising Agent', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E551', '551', 'Silicon Dioxide', 'Anti-caking Agent', 'IN', 'permitted', 10000.0, 'mg/kg', 'Anti-caking agent', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E621', '621', 'Monosodium Glutamate (MSG)', 'Flavor Enhancer', 'IN', 'restricted', 10000.0, 'mg/kg', 'Prohibited in food for infants under 12 months with mandatory label disclosure', 'FSSAI Regulation 2.4.5', 'https://www.fssai.gov.in', 'verified'),
('E627', '627', 'Disodium Guanylate', 'Flavor Enhancer', 'IN', 'permitted', NULL, 'GMP', 'Flavor Enhancer', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E631', '631', 'Disodium Inosinate', 'Flavor Enhancer', 'IN', 'permitted', NULL, 'GMP', 'Flavor Enhancer', 'FSSAI Food Additives Regulations', 'https://www.fssai.gov.in', 'verified'),
('E924A', '924a', 'Potassium Bromate', 'Flour Treatment Agent', 'IN', 'banned', NULL, NULL, 'Prohibited as flour treatment agent due to carcinogenicity', 'FSSAI Prohibition Notification 2016', 'https://www.fssai.gov.in', 'verified'),
('E951', '951', 'Aspartame', 'Artificial Sweetener', 'IN', 'restricted', NULL, NULL, 'NOT RECOMMENDED FOR CHILDREN. CONTAINS PHENYLALANINE', 'FSSAI Packaging & Labelling Regs', 'https://www.fssai.gov.in', 'verified')
ON CONFLICT (additive_code, jurisdiction) DO UPDATE SET
    status = EXCLUDED.status,
    canonical_name = EXCLUDED.canonical_name,
    label_requirement = EXCLUDED.label_requirement;
