import os
import sys
import pandas as pd

sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = r"c:\Users\thout\Downloads\check it"

all_supabase_csv = os.path.join(BASE_DIR, "all_supabase_products.csv")
confirmed_csv = os.path.join(BASE_DIR, "india_products_confirmed.csv")
needs_ver_csv = os.path.join(BASE_DIR, "india_products_needs_verification.csv")

print("=== EXECUTING BATCH 41 INGREDIENTS INTEGRATION & PURGE ===")

df_all = pd.read_csv(all_supabase_csv, dtype=str)
df_confirmed = pd.read_csv(confirmed_csv, dtype=str) if os.path.exists(confirmed_csv) else pd.DataFrame()
df_needs_ver = pd.read_csv(needs_ver_csv, dtype=str) if os.path.exists(needs_ver_csv) else pd.DataFrame()

for df in [df_all, df_confirmed, df_needs_ver]:
    if not df.empty and 'barcode' in df.columns:
        df['barcode'] = df['barcode'].astype(str).str.strip()

batch_41_rows = [
    {"barcode":"64100108233","product_name":"Frosted Flakes","brands":"Kellogg's","ingredients_text":"Milled corn, sugars (sugar, corn and barley malt extract), salt, riboflavin, vitamins and minerals (iron, niacinamide, thiamine hydrochloride, cholecalciferol [vitamin d3], d-calcium pantothenate, pyridoxine hydrochloride, folic acid)","additive_flags":"Clean"},
    {"barcode":"5050083943683","product_name":"Pringles Texas BBQ Sauce","brands":"Pringles","ingredients_text":"Dried potatoes, vegetable oil (corn, cottonseed, high oleic soybean, and/or sunflower oil), degerminated yellow corn flour, cornstarch, rice flour, maltodextrin, sugar, mono- and diglycerides, contains 2% or less of salt, tomato powder, monosodium glutamate, citric acid, onion powder, spice, garlic powder, yeast extract, hydrolyzed corn protein, malted barley flour, malic acid, disodium inosinate, disodium guanylate, paprika extract color, natural flavors, whey, wheat starch","additive_flags":"INS 621 MSG + INS 627 + INS 631"},
    {"barcode":"9300657114053","product_name":"Organic Tomato Ketchup","brands":"Heinz","ingredients_text":"Concentrated organic tomatoes (contains 198g of tomatoes per 100ml), organic sugar, salt, organic white vinegar (from wheat), food acid (citric acid), natural flavour, spice. Contains 77% concentrated tomatoes","additive_flags":"Clean"},
    {"barcode":"65400008100","product_name":"7Up Tropical","brands":"PepsiCo Canada","ingredients_text":"Carbonated water, glucose-fructose and/or sugar, natural flavour, citric acid, malic acid, sodium citrate, sodium benzoate","additive_flags":"INS 211 preservative"},
    {"barcode":"5053827200097","product_name":"Trésor Duo Choco","brands":"Kellogg's","ingredients_text":"Farines de céréales (50%) (riz, avoine complète, blé), fourrage au chocolat blanc (chocolat blanc {9%} {sucre, lait entier en poudre, beurre de cacao}, huiles végétales {palme, tournesol, colza} en proportions variables, sucre, lait écrémé en poudre, sirop de glucose, amidon, émulsifiant {lécithine de soja}), sucre, cacao en poudre, sel, antioxydants (palmitate d'ascorbyle, alpha-tocophérol). Vitamines et minéraux: vitamines (niacine, b6, b2, b1, acide folique, b12) et fer","additive_flags":"Clean"},
    {"barcode":"5900130031330","product_name":"Salted Caramel & Australian Macadamia","brands":"Nestlé/Froneri/Nuii","ingredients_text":"Entrahmte milch, zucker, sahne (14%), kakaobutter, glukosesirup, gesalzene karamellsauce (zucker, wasser, glukosesirup, gezuckerte kondensmilch {vollmilch, zucker}, butterfett, salz (0,08%), modifizierte stärke, verdickungsmittel {pektine, xanthan}, emulgator {mono- und diglyceride von speisefettsäuren}, natürliches aroma), mager-milchpulver, australische macadamianuss-stückchen (2,5%), butterfett, molkenerzeugnis, kakaomasse, laktose, emulgatoren (mono- und diglyceride von speisefettsäuren)","additive_flags":"Clean"},
    {"barcode":"57000010867","product_name":"Heinz Kansas City Barbecue Sauce","brands":"Heinz","ingredients_text":"Tomato paste, white vinegar, sugar, brown sugar, water, blackstrap molasses, salt, corn starch, spices and seasonings (anchovies fish), natural flavour, mustard, onion powder, garlic powder, xanthan gum","additive_flags":"Clean"},
    {"barcode":"5060639126866","product_name":"Monster Energy Zero Sugar","brands":"Monster Energy/Monster","ingredients_text":"Carbonated water, acid (citric acid), flavourings, taurine (0.4%), acidity regulator (sodium citrates), panax ginseng root extract (0.01%), sweeteners (sucralose, acesulfame k), l-carnitine l-tartrate (0.04%), preservatives (sorbic acid, benzoic acid), caffeine (0.03%), vitamins (b3, b6, b2, b12), colour (anthocyanins), sodium chloride, d-glucuronolactone, guarana seed extract (0.002%), inositol, magnesium carbonate, ginseng","additive_flags":"Energy drink with caffeine"},
    {"barcode":"7896102583182","product_name":"Maionese","brands":"Heinz","ingredients_text":"Óleo vegetal, água, vinagre, açúcar, ovo caipira, limão, goma de ovo caipira, cebola, farinha de","additive_flags":"Clean"},
    {"barcode":"878204788792760276","product_name":"California Pizza Kitchen Thai Crunch Salad Full","brands":"California Pizza Kitchen","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"9300657234713","product_name":"Baked Beans in a Deliciously Rich Tomato Sauce","brands":"HEINZ FOR TWO","ingredients_text":"Navy beans (51%), tomato sauce (49%) [tomatoes (24%), water, sugar, maize thickener (1422), salt, food acids (acetic acid, citric acid), flavours]","additive_flags":"INS 1422 thickener"},
    {"barcode":"7613287291363","product_name":"Veggie Balls","brands":"Garden Gourmet/Nestlé","ingredients_text":"Woda, oleje roślinne (olej rzepakowy, olej słonecznikowy), marchew 10,2%, groszek 9,0%, kukurydza 7,2%, białko sojowe 6,5%, białko pszenne 6,0%, seler, białko jaja w proszku, puree jabłkowe, ocet spirytusowy, cebula, papryka czerwona, cebula w proszku, skrobia kukurydziana, sól, błonnik z grochu, skrobia z grochu, aromaty naturalne, przyprawy, ekstrakty przypraw","additive_flags":"Clean"},
    {"barcode":"13000005746","product_name":"Tomate Ketchup","brands":"Heinz","ingredients_text":"Concentrado de tomate (agua y pasta de tomate), azúcares añadidos (fructosa y glucosa), vinagre, sal yodada, cebolla en polvo y saborizante natural","additive_flags":"Clean"},
    {"barcode":"4060800105189","product_name":"Pepsi Max","brands":"Pepsi","ingredients_text":"Wasser, kohlensäure, farbstoff zuckerkulör e 150d, süßungsmittel aspartam* und acesulfam-k, säuerungsmittel phosphorsäure und citronensäure, säureregulator natriumcitrat, aroma koffein, aroma. *enthält eine phenylalaninquelle","additive_flags":"INS 150d Caramel"},
    {"barcode":"4009900531597","product_name":"Skittles Smoothies","brands":"Mars/Mars Wrigley Confectionery/Skittles/Wrigley","ingredients_text":"Sucre, sirop de glucose, graisse de palme, acidifiant acide citrique, dextrine, acidifiant acide malique, aromes, maltodextrine, amidon modifie, sel, correcteur d'acidite citrate trisodique, agent d'enrobage cire de carnauba, colorants e153, e162, e163, e100, e132, e160a; concentres (de patate douce, de radis)","additive_flags":"Artificial colours (E153, E162, E163, E100, E132, E160a)"},
    {"barcode":"9300657410100","product_name":"Curried Egg Salad","brands":"Heinz Wattie's","ingredients_text":"White vinegar, sugar, canola oil [protected with antioxidant], skim milk powder, maize thickener (1422), sweetened condensed milk, salt, egg yolk, mustard flour, preservative (202), antioxidant (395)","additive_flags":"INS 202 preservative + INS 1422 thickener"},
    {"barcode":"8410494301385","product_name":"Pepsi Light Sin Cafeína","brands":"Pepsi","ingredients_text":"Agua carbonatada, colorante (e-150d), acidulantes (e-338, e-330), edulcorantes (aspartamo, acesulfamo k), conservador (e-211), extractos y aromas naturales","additive_flags":"INS 150d + INS 211"},
    {"barcode":"7622201140106","product_name":"Schokolade Weihnachts-Geschenk","brands":"TOBLERONE","ingredients_text":"Sucre, pâte de cacao, lait entier en poudre, beurre de cacao, miel (3%), beurre concentré, amandes (1,6%), émulsifiant (lécithines de soja), blancs d'oeufs, arôme. Cacao: 28% minimum dans le chocolat au lait. Cacao: 50% minimum dans le chocolat noir","additive_flags":"Clean"},
    {"barcode":"70221009731","product_name":"Chocolate Candy Bar","brands":"Oreo","ingredients_text":"Sugar, palm oil, cocoa butter, nonfat milk, wheat flour, whey, chocolate, milkfat, contains less than 2% of hazelnut paste, soy lecithin, wheat starch, cocoa (processed with alkali), glucose-fructose syrup (glucose syrup, high fructose corn syrup), salt, potassium bicarbonate, baking soda, artificial flavor, sunflower lecithin","additive_flags":"Clean"},
    {"barcode":"8000500160466","product_name":"Boîte Cube Remplie de Chocolats Pralinés","brands":"Ferrero","ingredients_text":"Milk chocolate 30% (sugar, cocoa butter, cocoa paste, skimmed milk powder, concentrated butter, emulsifiers: lecithins [soy], vanillin), hazelnuts 28.5 per cent, sugar, palm oil, wheat flour, lactoserumen powder, lean cocoa, emulsifiers: lecithins [soy], baking powder: carbonate sodium acid, salt, vanillin","additive_flags":"Clean"},
    {"barcode":"5053827206488","product_name":"Crunchy Nut Granola Bar - Chocolate & Nuts","brands":"Kellogg's","ingredients_text":"Nuts (41%) (peanuts, roasted almonds {vegetable oil [canola, safflower] in varying proportions, salt}), chocolate (16%) (sugar, cocoa mass, cocoa butter, fat reduced cocoa powder, emulsifier {soy lecithin}, natural vanilla flavouring), glucose syrup, oats (6.5%), chocolate chunks (5%) (cocoa mass, sugar, fat reduced cocoa powder, dextrose, cocoa butter, emulsifier {soy lecithin}), fructose, sugar, crisp rice piece (rice flour, rice bran)","additive_flags":"Clean"},
    {"barcode":"38000234576","product_name":"Caramel Crunch Jumbo Snax Cereal","brands":"Kellogg's/Corn Pops","ingredients_text":"Degerminated yellow corn meal, sugar, corn bran, brown sugar syrup, contains 2% or less of salt, natural flavor, wheat flour, bht for freshness. Vitamins and minerals: reduced iron, niacinamide, vitamin b6 (pyridoxine hydrochloride), vitamin b2 (riboflavin), vitamin b1 (thiamin hydrochloride), folic acid, vitamin d3, vitamin b12","additive_flags":"BHT preservative"},
    {"barcode":"49000048056","product_name":"Dasani Purified Water","brands":"Coca-Cola","ingredients_text":"Purified water, magnesium sulfate, potassium chloride","additive_flags":"Clean"},
    {"barcode":"3116740032724","product_name":"Naturnes","brands":"Nestlé","ingredients_text":"Eau de cuisson. Artichauts 23,3%, pommes de terre 22.5%, semoule de riz, huile de colza, jus de citron concentré","additive_flags":"Clean baby food"},
    {"barcode":"745460112596","product_name":"Ketchup 0 Sel Ajouté 70% Moins de Sucres","brands":"Heinz","ingredients_text":"Tomates (200g pour 100 g de tomato ketchup), vinaigre d'alcool, jus de citron à base de concentré, chlorure de potassium, acidifiant (acide malique), fibres d'agrumes, extraits d'épices et d'herbes (contiennent du céleri), édulcorant (sucralose)","additive_flags":"Clean"},
    {"barcode":"0012000801655","product_name":"Pepsi Mini","brands":"Pepsi/PepsiCo","ingredients_text":"Carbonated water, sugar, citric acid, sodium citrate, flavor, aspartame, acesulfame potassium, caffeine, gum arabic, sodium benzoate, color (caramel e150d)","additive_flags":"INS 150d + INS 211"},
    {"barcode":"9300682055598","product_name":"Chocolate","brands":"Mars","ingredients_text":"Celebrations contains an assortment of milk chocolates 54%. Ingredients: sugar, glucose syrup, milk solids, cocoa butter, cocoa mass, peanuts, desiccated coconut, vegetable fat, vegetable oil, emulsifier (soy lecithin, 471), malt extract (barley), salt, cocoa powder, humectant (422), egg white, wheat flour, raising agent (341, 501, 500). Milk chocolate contains cocoa solids 25% minimum, milk solids 14% minimum","additive_flags":"Clean"},
    {"barcode":"44700091432","product_name":"Mesquite Smoked Turkey Breast","brands":"Heinz","ingredients_text":"Turkey breast, water, cultured dextrose, contains less than 2% of the following: potato starch, sea salt, honey, vinegar*, cultured celery juice*, cherry powder. *ingredient used to preserve quality. No gluten","additive_flags":"Clean"},
    {"barcode":"7613035412798","product_name":"Copa Copacabana Organic Infusion","brands":"Nestlé/Special T","ingredients_text":"Morceaux de pommes* (37%), marc de pomme* (23.1%), écorce de cynorrhodon (22%), menthe crépue* (8.5%), réglisse* (4.5%), arôme naturel de citron vert, arômes, acidifiant: acide citrique. *provient de culture biologique","additive_flags":"Clean"},
    {"barcode":"80052944","product_name":"Kinder","brands":"Kinder/Ferrero","ingredients_text":"Sucre, lait écrémé en poudre 17,5%, graisses végétales (palme, karité), lait en poudre 10,5%, beurre de cacao, pâte de cacao, beurre concentré 4%, émulsifiant e322 (soja), vaniline","additive_flags":"Clean"},
    {"barcode":"8715700421056","product_name":"Sandwich Spread","brands":"Heinz","ingredients_text":"Vegetables 43% (gherkin 19%, onion 11%, kohlrabi, carrot 3.8%, celeriac 3.7%, red pepper 1.8%), sugar, rapeseed oil, water, vinegar, skimmed milk powder, modified starch, spices (contain mustard), thickener (guar gum), colour (lutein), acid (lactic acid), flavourings (contain celery), spice extracts","additive_flags":"Clean"},
    {"barcode":"5000112636925","product_name":"Urge Original 0.33L","brands":"COCA-COLA EUROPEAN PARTNERS NORGE","ingredients_text":"Kullsyreholdig vann, sukker, maltodextrin, aromaer, surhetsregulerende middel (e330, e331), appelsinjuice fra konsentrat, konserveringsmiddel (e202), koffein, antioksidant (e300), fargestoff (e160a), stabilisator (e410)","additive_flags":"INS 202 preservative + INS 160a colour"},
    {"barcode":"50166909","product_name":"Twix","brands":"Twix","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8436574335491","product_name":"Mega Vitamins","brands":"Quamtrax","ingredients_text":"Extracto de concentrado de ostras crudas, extracto seco de hoja de ginkgo biloba, nicotinamida (niacina)","additive_flags":"Supplement"},
    {"barcode":"9300682060929","product_name":"Snickers","brands":"Snickers","ingredients_text":"Sugar, peanuts, glucose syrup, cocoa butter, cocoa mass, vegetable oil, vegetable fat, soy lecithin, egg white, flavours. Milk chocolate contains cocoa solids 23%, milk solids 21%","additive_flags":"Clean"},
    {"barcode":"9300617061304","product_name":"Choc Centre Crunchy Cookies with a Choc Filled Centre","brands":"Cadbury","ingredients_text":"Wheat flour, choc centre filling (25%) (sugar, vegetable oil, milk solids, cocoa mass, thickener (1414), cocoa powder, emulsifier (soy lecithin), flavour), milk chocolate chips (15%) (sugar, milk solids, cocoa butter, cocoa mass, vegetable fat, dextrose, emulsifier (442), flavour), sugar, milk solids, vegetable oil, wheat starch, raising agents (503, 500, 450), salt, flavours (contains milk), colour (160a), soybean fibre","additive_flags":"INS 1414 thickener + INS 160a colour"},
    {"barcode":"5053990151035","product_name":"Pringles Pizza Flavour","brands":"Pringles","ingredients_text":"Patatas deshidratadas; aceite de girasol; harina de trigo; harina de maíz; harina de arroz; condimento con sabor de pizza (lactosa {leche}, suero de mantequilla en polvo {leche}, potenciadores del sabor","additive_flags":"INS 621 MSG likely"},
    {"barcode":"7622300073589","product_name":"Oreo Wafer Roll Chocolate","brands":"Oreo","ingredients_text":"น้ำตาล 39% แป้งสาลี 28% น้ำมันพืช 19% ผงโกโก้ 9% แต่งกลิ่นเลียนธรรมชาติและสังเคราะห์","additive_flags":"Clean"},
    {"barcode":"5601363012683","product_name":"Chips Original","brands":"Lay's/Frito-Lay/PepsiCo","ingredients_text":"Potatoes, vegetable oil (canola, corn, soybean, and/or sunflower oil), and salt","additive_flags":"Clean"},
    {"barcode":"4009900456807","product_name":"Extra Eucalyptus 5pk","brands":"MARS NORGE AS","ingredients_text":"Søtningsmidler (xylitol 30%, sorbitol, aspartam, acesulfam k), gummibase, fortykningsmiddel e414, aromaer, fuktighetsbevarende middel e422, emulgator sojabønnelecitin, overflatemiddel e903, antioksidant e320","additive_flags":"BHT antioxidant"},
    {"barcode":"8000500359556","product_name":"Raffaello Chocolate 90g","brands":"Ferrero","ingredients_text":"Sugar, cocoa butter, skim milk powder, coconut flake, palm oil, whey powder, almond, coconut oil, milk powder, soy lecithins e322, natural flavors","additive_flags":"Clean"},
    {"barcode":"38000284472","product_name":"Pringles Las Meras Meras Habaneras","brands":"Pringles","ingredients_text":"Dried potatoes, vegetable oil (corn, cottonseed, high oleic soybean, sunflower), degerminated yellow corn flour, cornstarch, rice flour, maltodextrin, mono- and diglycerides, salt, 2% citric acid, monosodium glutamate, malic acid, sugar, spice, onion powder, garlic powder, corn syrup solids, yeast extract, lime juice concentrate, sodium diacetate, natural and artificial flavor, disodium inosinate, disodium guanylate, whey, yellow 6 lake, wheat starch, yellow 5 lake","additive_flags":"INS 621 MSG + INS 627 + INS 631 + Artificial colours"},
    {"barcode":"4770477231516","product_name":"Pepsi","brands":"Pepsi","ingredients_text":"Carbonated water, sugar, colour (caramel e150d), acid (phosphoric acid), flavourings (including caffeine), sweeteners (acesulfame k, sucralose)","additive_flags":"INS 150d Caramel"},
    {"barcode":"5000159543125","product_name":"Salted Caramel Fingers","brands":"Twix","ingredients_text":"Sugar, glucose syrup, wheat flour, palm fat, skimmed milk powder, cocoa butter, cocoa mass, milk fat, lactose, whey permeate (from milk), salt, fat reduced cocoa, emulsifier (soya lecithin), raising agent (e500), vanilla extract. (May contain: almond, barley, hazelnut, oats)","additive_flags":"Clean"},
    {"barcode":"5059319023885","product_name":"Miel Pops Loops","brands":"Kellogg's","ingredients_text":"Farines de céréales complètes (83%) (blé, avoine, orge, seigle), sucre, miel (4.5%), sel, sirop de glucose, phosphate tricalcique, arôme naturel, antioxydant (extrait riche en tocophérols), colorant (caroténoïdes), niacine, fer, vitamine b6, riboflavine, thiamine, acide folique, vitamine d, vitamine b12","additive_flags":"Clean"},
    {"barcode":"0028400017091","product_name":"Doritos Flavored Tortilla Chips - Cool Ranch","brands":"Doritos","ingredients_text":"Whole corn, vegetable oil (contains one or more of the following ingredients: corn oil, soybean and/or sunflower), corn maltodextrin, salt, tomato powder, corn starch, lactose, whey, skim milk, dry extract of corn syrup, onion powder, sugar, garlic powder, monosodium glutamate, cheddar cheese (milk, cultures, cheese, salt, enzymes), dextrose, malic acid, buttermilk, natural and artificial flavors, sodium acetate, artificial coloring (including red 40, blue 1, yellow 5), sodium caseinate, spice, citric acid, inosinate disodium salt and guanylate disodium salt","additive_flags":"INS 621 MSG + Artificial colours (Red 40, Blue 1, Yellow 5)"},
    {"barcode":"42211792","product_name":"Extra Menthol Strong 14g","brands":"Mars Norge AS","ingredients_text":"Søtningsstoffer: xylitol 29%, sorbitol, aspartam, acesulfam k; gummibase, aromaer, fortykningsmiddel e414, fuktighetsbevarende middel e422, emulgeringsmiddel sojabønnelecitin, overflatebehandlingsmiddel e903, antioksidant e320, farvestoffer e133, e160a","additive_flags":"BHT antioxidant + INS 133 + INS 160a colours"},
    {"barcode":"0009064407928","product_name":"Delowar","brands":"Various","ingredients_text":"NON-FOOD — Voltage stabilizer/electrical product","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8000500411827","product_name":"Origins","brands":"Ferrero/Ferrero Rocher","ingredients_text":"Chocolat noir extra 30% (pâte de cacao 77.5% {côte d'ivoire}, sucre, beurre de cacao 2.5%, beurre concentré, émulsifiants {lécithines {soja}}, arômes), noisettes 25.5%, huile de palme, sucre, cacao maigre en poudre, farine de froment, lactoserum en poudre, émulsifiants (lécithines {soja}), poudres à lever (carbonate acide de sodium), vanilline, sel. Cacao dans le chocolat noir: 80% minimum","additive_flags":"Clean"},
    {"barcode":"59622000424","product_name":"Pop Tarts","brands":"Kelloggs","ingredients_text":"Wheat flour, sugar, glucose syrup, invert sugar syrup, palm oil, dextrose, fat reduced cocoa powder, colours (calcium carbonate, paprika extract), wheat starch, humectant (glycerol), salt, raising agents (sodium hydrogen carbonate, e450), beef gelatin, starch, citric acid, natural vanilla flavouring with other natural flavourings, brown rice syrup, vegetable juice concentrates (beetroot, carrot), emulsifier (soy lecithin), stabiliser (xanthan gum), niacin, iron, thiamin, riboflavin, folic acid","additive_flags":"Clean"},
    {"barcode":"44000060657","product_name":"Golden Oreo","brands":"OREO","ingredients_text":"Wheat flour, sugar, palm oil, rapeseed oil, wheat starch, glucose-fructose syrup, raising agents (sodium carbonates, ammonium carbonates), salt, emulsifier (soya lecithins), flavourings","additive_flags":"Clean"},
    {"barcode":"7622201735296","product_name":"Oreo","brands":"Oreos","ingredients_text":"Azúcar, harina de trigo enriquecida, aceite vegetal, cacao en polvo, jarabe de maíz de alta fructosa, almidón, sal, lecitina de soja, bicarbonato de sodio, bicarbonato de amonio, vainillina","additive_flags":"Clean"},
    {"barcode":"0028400164733","product_name":"Lay's Classic Potato Chips 13 3/4 Ounce Party Size Bag","brands":"Frito Lays","ingredients_text":"Potatoes, vegetable oil (sunflower, corn, and/or canola oil), and salt","additive_flags":"Clean"},
    {"barcode":"8002270386794","product_name":"Sanpellegrino Limone","brands":"San Pellegrino/Nestlé","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8410066139385","product_name":"Heinz Tomate Frito","brands":"Heinz","ingredients_text":"Tomaten (170g per 100g tomato frito), extra vierge olijfolie 3,5% (met extracten van gebakken ui en knoflook), suiker, zout, citrusvezel","additive_flags":"Clean"},
    {"barcode":"5212039100018","product_name":"Natural Mineral Water","brands":"Eonio/PepsiCo Inc.","ingredients_text":"Water (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"3223905200","product_name":"Del Valle Nectar de Mango","brands":"Coca-Cola Company","ingredients_text":"Agua, jugo y pulpa de mango de concentrado (25%), azucares, concentrado sabor mango","additive_flags":"Clean"},
    {"barcode":"38000222931","product_name":"Pop Tarts","brands":"Kellogg's","ingredients_text":"Enriched flour (wheat flour, niacin, reduced iron, vitamin b1 [thiamin mononitrate], vitamin b2 [riboflavin], folic acid), corn syrup, high fructose corn syrup, dextrose, soybean and palm oil (with tbhq for freshness), sugar, bleached wheat flour. Contains 2% or less of wheat starch, salt, dried cherries, dried apples, citric acid, leavening (baking soda, sodium acid pyrophosphate, monocalcium phosphate), modified wheat starch, gelatin, caramel color, xanthan gum","additive_flags":"TBHQ preservative + INS 150d Caramel"},
    {"barcode":"0040000488064","product_name":"M & M Chocolate (180 G)","brands":"Mars","ingredients_text":"Sugar, cocoa mass, full cream milk powder, lactose, cocoa butter, starch, palm fat, glucose syrup, shea fat, stabiliser (gum arabic {e414}), emulsifiers (soya lecithin {e322}, sunflower lecithin {e322}), colours (curcumin {e100}, brilliant blue {e133}, mixed carotenes {e160a}, beta-apo-8'-carotenal {e160e}, beetroot red {e162}, titanium dioxide {e171}, iron oxide and hydroxides {e172}), dextrin, glazing agent (carnauba wax {e903}), palm kernel oil, salt, natural vanilla extract, flavouring. (May contain: peanut)","additive_flags":"Artificial colours (E100, E133, E160a, E160e, E162, E171, E172)"},
    {"barcode":"01746305","product_name":"Unknown","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"0764460291056","product_name":"The Originote","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"28400751452","product_name":"Kettle Cooked Cajun Spice","brands":"Lay's","ingredients_text":"Potatoes, vegetable oil (corn, canola, and/or sunflower oil), spices (including black pepper, red pepper, and thyme), salt, corn maltodextrin, brown sugar, tapioca maltodextrin, onion powder, sugar, garlic powder, potassium salt, corn syrup solids, paprika, citric acid, yeast extract, paprika extracts, lactose, natural flavors, skim milk, buttermilk","additive_flags":"Clean"},
    {"barcode":"5942204005694","product_name":"Pepsi Max","brands":"Pepsi","ingredients_text":"Water, carbon dioxide, colorant (caramel with ammonium sulfite), sweeteners (aspartame, acesulfame potassium), acidifying agents (phosphoric acid, citric acid), acidity regulator (sodium citrate), flavors, caffeine","additive_flags":"INS 150d Caramel"},
    {"barcode":"53689484795976358393","product_name":"California Pizza Kitchen Ultimate Bloody Mary","brands":"California Pizza Kitchen","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"0007010975021","product_name":"Popat Ganga Jamuna","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"5060402907906","product_name":"Mars Spread","brands":"Mars","ingredients_text":"Crema spalmabile al cioccolato al latte e aromatizzata al caramello. Ingredienti: zucchero, oli vegetali (colza, palma, girasole), latte intero in polvere, cioccolato al latte (5%) (zucchero, burro di cacao, latte scremato in polvere, massa di cacao, lattosio {latte}, proteine del siero di latte, olio di palma, siero di latte in polvere, grasso del latte, emulsionante {lecitine di soia}, estratto di vaniglia), maltodestrina, lattosio (latte), cacao magro in polvere, emulsionante (lecitine di girasole)","additive_flags":"Clean"},
    {"barcode":"38000185212","product_name":"Pringles Extra Hot","brands":"Pringles","ingredients_text":"Papas deshidratadas. Aceite vegetal (contiene al menos uno de los siguientes aceites: maíz, semilla de algodón, semilla de soya y/o semilla de girasol), almidón de maíz, harina de maíz desgerminado, harina de arroz, maltodextrina, emulsificante (mono y diglicéridos), sal, regulador de la acidez (ácido cítrico), azúcar, acentuadores del sabor (glutamato monosódico, diacetato de sodio, guanilato disódico, inosinato disódico), cebolla en polvo, ajo en polvo, extracto de levadura, chile en polvo, saborizantes naturales y artificiales a chile, colorantes artificiales (rojo allura ac, amarillo ocaso fcf)","additive_flags":"INS 621 MSG + INS 627 + INS 631 + Artificial colours"},
    {"barcode":"7771605000605","product_name":"Fanta Sabor Naranja Mandarina","brands":"Fanta/Coca-Cola","ingredients_text":"Agua carbonatada, azúcar, saborizantes naturales, reguladores de la acidez (sin 330, sin 331 (iii), sin 452(i)), sustancia conservadora (sin 211), edulcorantes (sin 951 aspartame (0.008%), sin 950 acesulfame k (0.006%)), colorantes artificiales (sin 102, sin 129)","additive_flags":"INS 211 + INS 102 + INS 129"},
    {"barcode":"5000157076397","product_name":"Heinz Mayonnaise","brands":"Heinz","ingredients_text":"Rapeseed oil 68%, water, pasteurized free range egg yolk* 5%, spirit vinegar, sugar, starch, salt, mustard seeds, spices, antioxidant (calcium disodium edta)","additive_flags":"Clean"},
    {"barcode":"8001860238369","product_name":"Scotti Hakumaki Sushi","brands":"Scotti","ingredients_text":"500 g uncooked hakumaki sushi rice, 625 ml cold water, 120 ml sushi rice vinegar","additive_flags":"Clean"},
    {"barcode":"8703510010522","product_name":"Shell Pasta","brands":"Savorit","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8002000247142","product_name":"Sanjivani 250gm","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"0855460003074","product_name":"Superseedz Somewhat Spicy Gourmet Pumpkin Seeds","brands":"Kathies Kitchen","ingredients_text":"Shelled pumpkin seeds, cayenne pepper sauce, granulated garlic, granulated onion. Cayenne, paprika, black pepper, oregano, basil, thyme, rosemary, marjoram, sage","additive_flags":"Clean"},
    {"barcode":"7771609000854","product_name":"Fanta Sabor Papaya","brands":"Fanta/Coca-Cola","ingredients_text":"Agua carbonatada, azúcar, saborizante idéntico al natural de papaya, regulador de la acidez (sin 330), sustancias conservadoras (sin 211, sin 385), edulcorantes (sin 950 acesulfame k (0.004%), sin 951 aspartame (0.0008%)), colorantes artificiales (sin 102, sin 110)","additive_flags":"INS 211 + INS 385 + INS 102 + INS 110"},
    {"barcode":"8852756304145","product_name":"Honey Crunch Corn Flakes","brands":"Kellogg's","ingredients_text":"Corn (69.3%), sugar, peanut (4.3%), honey (2.2%), iodized salt, vitamins (c, b3, a, b6, b12, b2, b1, folic acid), minerals (ferric phosphate, reduced iron, zinc oxide), antioxidant (mixed tocopherol), cereal extract","additive_flags":"Clean"},
    {"barcode":"5000112648300","product_name":"Coca-Cola Zero Sugar 6 x 250 ml","brands":"Coca-Cola","ingredients_text":"Sprankelend water; kleurstof: e150d; voedingszuur: e338; zoetstoffen: aspartaam, acesulfaam-k; natuurlijke aroma's; aroma cafeïne; zuurteregelaar: e331","additive_flags":"INS 150d Caramel"},
    {"barcode":"59724101548","product_name":"Krave Chocolatey","brands":"Kellogg's","ingredients_text":"Garniture à saveur de chocolat (sucre, huile végétale, substances laitières modifiées, cacao, chocolat non sucré, lécithine de soya, huile de palme, arôme naturel), sucres (sucre, mélasse verte), farine d'avoine entière, farine de blé entier, farine de riz, fibres de bale d'avoine, son de maïs, sel, huile de palme modifiée, arôme naturel, carotène (pour la couleur), rocou (pour la couleur), vitamines et minéraux: fer, chlorhydrate de thiamine, niacinamide, oxyde de zinc, d-pantothénate de calcium, chlorhydrate de pyridoxine, cholecalciferol (vitamine d3), acide folique. Contient: lait, soya, avoine, blé","additive_flags":"Clean"},
    {"barcode":"8715600249071","product_name":"Pepsi Frisdrank 6 x 0.33 L","brands":"Pepsi","ingredients_text":"Ingrediënten: koolzuurhoudend water, suiker, kleurstof (sulfiet-ammoniak-karamel), aroma's (bevat cafeïne), voedingszuur (fosforzuur), zoetstoffen (acesulfaam-k, sucralose)","additive_flags":"INS 150d Caramel"},
    {"barcode":"5000112668254","product_name":"Cherry 1.5L","brands":"Coca-Cola","ingredients_text":"Sprankelend water, suiker, kleurstof: e150d, voedingszuur: e338, natuurlijke aroma's, aroma cafeïne","additive_flags":"INS 150d Caramel"},
    {"barcode":"8715600248760","product_name":"Pepsi Zero Caffeïne Vrij Frisdrank 1.5 L","brands":"Pepsi","ingredients_text":"Koolzuurhoudend water, kleurstof (karamel e150d), zoetstoffen (e950, e951), voedingszuren (e338, e330), zuurteregelaar (e331), aroma's","additive_flags":"INS 150d Caramel"},
    {"barcode":"38000139277","product_name":"Screamin' Dill Pickle","brands":"Pringles","ingredients_text":"Dried potatoes, vegetable oil (corn, cottonseed, high oleic soybean, and/or sunflower oil), degerminated yellow corn flour, cornstarch, rice flour, maltodextrin, mono- and diglycerides, contains 2% or less of sodium diacetate, salt, whey, lactose, citric acid, monosodium glutamate, dill seed powder, natural flavor, garlic powder, onion powder, dill extract, garlic extract, mustard extract, wheat starch","additive_flags":"INS 621 MSG"},
    {"barcode":"0053859034382","product_name":"Heritage","brands":"Stremicks Heritage Foods LLC","ingredients_text":"Organic milk, organic skim milk, organic nonfat milk solids, vitamin a palmitate, vitamin d3","additive_flags":"Clean"},
    {"barcode":"00001295","product_name":"Feed Grade Soybeans","brands":"H-E-B/Rural Route 1","ingredients_text":"NON-FOOD — Animal feed","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"38100212290","product_name":"Corn Flakes","brands":"Kellogg's","ingredients_text":"Milled corn, sugar, malt flavor, contains 2% or less of salt. Bht added to packaging for freshness. Vitamins and minerals: iron, vitamin c (sodium ascorbate, ascorbic acid), niacinamide, vitamin b6 (pyridoxine hydrochloride), vitamin b2 (riboflavin), vitamin b1 (thiamin hydrochloride), vitamin a palmitate, folic acid, vitamin d, vitamin b12","additive_flags":"BHT preservative"},
    {"barcode":"90446207","product_name":"ORGANICS Viva Mate","brands":"Red Bull","ingredients_text":"Wasser, zucker*, kohlensäure, zitronensaftkonzentrat, mate-extrakt (0,33%), karamellzuckersirup*, natürliches zitronenaroma, johannisbrotaroma und vanillearoma, natürliches aroma koffein*","additive_flags":"Clean"},
    {"barcode":"70847002901","product_name":"Monster Energy Zero Sugar","brands":"Monster","ingredients_text":"Carbonated water, citric acid, erythritol, flavours, taurine, sodium citrate, panax ginseng flavour, caffeine, sorbic acid, sucralose, benzoic acid, niacinamide (vit. b3), grape skin extract, acesulfame potassium, salt, d-glucuronolactone, guarana seed extract, inositol, pyridoxine hydrochloride (vit. b6), riboflavin (vit. b2), cyanocobalamin (vit. b12)","additive_flags":"Energy drink with caffeine"},
    {"barcode":"70847012474","product_name":"Zero Ultra","brands":"Monster Energy","ingredients_text":"Carbonated water, citric acid, erythritol, taurine, sodium citrate, natural & artificial flavors, panax ginseng flavor, l-carnitine l-tartrate, caffeine, sucralose, sorbic acid (preservative), benzoic acid (preservative), niacinamide (vit. b3), d-calcium pantothenate (vit. b5), pyridoxine hydrochloride (vit. b6), cyanocobalamin (vit. b12)","additive_flags":"Energy drink with caffeine"},
    {"barcode":"726684792221","product_name":"Toned Milk","brands":"Sid's Farm","ingredients_text":"Milk","additive_flags":"Clean single-ingredient"},
    {"barcode":"9900601913017","product_name":"Good Life Almond","brands":"Good Life","ingredients_text":"Almond","additive_flags":"Clean single-ingredient"},
    {"barcode":"0028000517205","product_name":"Media Crema","brands":"Nestlé","ingredients_text":"Light cream, carrageenan, sodium alginate, disodium phosphate, sodium citrate","additive_flags":"Clean"},
    {"barcode":"70847014973","product_name":"Sparkling Water","brands":"Monster Energy Company","ingredients_text":"Pure triple filtered carbonated water, apple juice concentrate, erythritol, natural flavors with extracts of concord and muscat grapes, citric acid, potassium citrate, stevia leaf extract, malic acid, monk fruit extract, ascorbic acid (vitamin c)","additive_flags":"Clean"},
    {"barcode":"70847016144","product_name":"Hubert's Lemonade Diet Lemonade Original","brands":"Monster Energy Company","ingredients_text":"Pure filtered water, erythritol, natural lemon juice concentrate, cane sugar, citric acid, natural flavors (extracts of lemons), stevia leaf extract, monk fruit extract","additive_flags":"Clean"},
    {"barcode":"5000159565578","product_name":"Twix","brands":"Twix","ingredients_text":"Sugar, glucose syrup, wheat flour, palm fat, skimmed milk powder, cocoa butter, cocoa mass, whey permeate (milk), milk fat, fat-reduced cocoa powder, salt, emulsifier (soya lecithin), raising agent (e500), flavouring. (May contain: nuts, other cereals containing gluten)","additive_flags":"Clean"},
    {"barcode":"70847018650","product_name":"Hubert's Organic Pink Lemonade","brands":"Monster Energy Company","ingredients_text":"Pure filtered water, organic cane sugar, organic lemon juice concentrate, citric acid, natural flavors, organic strawberry juice concentrate, organic stevia leaf extract, organic fruit & organic vegetable juice (for color)","additive_flags":"Clean"},
    {"barcode":"70847875116","product_name":"Hansen's Natural Cane Soda Kiwi Strawberry","brands":"Hansen's/Monster Energy Company","ingredients_text":"Contains: pure triple filtered carbonated water, sugar, citric acid, natural flavors with extracts of new zealand and/or chilean and/or italian kiwi fruits, u.s. and/or european strawberries","additive_flags":"Clean"},
    {"barcode":"70847876458","product_name":"Natural Cane Soda","brands":"Hansen's/Monster Energy Company","ingredients_text":"Pure triple filtered carbonated water, sugar, caramel color, natural spices of wintergreen, birch, anise, sassafras, tahitian vanilla extract, citric acid","additive_flags":"INS 150d Caramel"},
    {"barcode":"8992982201501","product_name":"Nestle RH 30","brands":"Nestlé","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"5059319016481","product_name":"Special K Crunchy Oat Granola Dark Chocolate Curls","brands":"Kellogg's","ingredients_text":"Crunchy oat, wheat and barley clusters with dark chocolate. 30 ingredients: whole oats (66%), dark chocolate (10%) (cocoa mass, sugar, milk fat, emulsifier {sunflower lecithin}), sugar, sunflower oil, wheat flour (6%), corn fibre, glucose syrup, puffed barley (2%), emulsifier (soy lecithin), natural spice flavouring, natural flavouring, barley malt extract. For allergens see ingredients highlighted in bold. May contain gluten from other cereals, nuts","additive_flags":"Clean"},
    {"barcode":"38000311208","product_name":"Frosted Brown Sugar Cinnamon Toaster Pastries","brands":"Kellogg's/Pop-Tarts","ingredients_text":"Enriched flour (wheat flour, niacin, reduced iron, vitamin b1 [thiamin mononitrate], vitamin b2 [riboflavin], folic acid), sugar, soybean and palm oil (with tbhq for freshness), corn syrup, dextrose, high fructose corn syrup, bleached wheat flour, contains two percent or less of molasses, salt, leavening (baking soda, sodium acid pyrophosphate, monocalcium phosphate), cinnamon, wheat starch, gelatin, caramel color, soy lecithin","additive_flags":"TBHQ preservative + INS 150d Caramel"},
    {"barcode":"5050083356902","product_name":"All-Bran Bizcochito Fruta y Fibra","brands":"Kellogg's","ingredients_text":"Cereales salvado de trigo (12% harina de trigo (9%), copos de avena integral (9%)), jarabe de glucosa-fructosa, puré de manzana (12%), aceite de girasol, jarabe de glucosa, pasas sultanas (5,5%) (humectante: glicerol), azúcar, fibra de avena, fructosa, jarabe de azúcar parcialmente invertido, dextrosa, leche desnatada en polvo, emulgentes (e475, e472e, lecitina de soja), aroma de malta de cebada, gasificante (e500), sal, aromas, almidón modificado, ácido málico, canela, estabilizante (goma guar), antioxidante (ácido ascórbico, e320), niacina, hierro, vitamina b6, riboflavina (b2), tiamina (b1), acido fólico, vitamina b12","additive_flags":"BHT antioxidant"},
    {"barcode":"2698201756697","product_name":"Unknown","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"84504517","product_name":"Kinder Joy","brands":"Kinder","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"0661706974370","product_name":"Unknown","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"0431627066061","product_name":"Unknown","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"9427142066021","product_name":"Unknown","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"9505000021549","product_name":"Unknown","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"0001678530004","product_name":"Bisk Farm Rich Marie","brands":"Bisk Farm","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"7622201756932","product_name":"Cadbury Oreo Coco Creme","brands":"Oreo","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8564324165644","product_name":"Lemon Juice","brands":"Fruitaco","ingredients_text":"Lemon juice (99%), water (1%), class ii preservative (ins 224)","additive_flags":"INS 224 preservative"},
    {"barcode":"70847016120","product_name":"Hubert's Lemonade Diet Lemonade Strawberry","brands":"Monster Energy Company","ingredients_text":"Pure filtered water, erythritol, natural lemon juice concentrate, cane sugar, citric acid, natural flavors (extracts of strawberries), fruit and vegetable juice (for color), stevia leaf extract, monk fruit extract","additive_flags":"Clean"},
    {"barcode":"87157246","product_name":"Ketchup","brands":"Heinz","ingredients_text":"Tomato (148 g per 100 g), vinegar, sugar, salt, extracts of spices and herbs (contains celery), spice","additive_flags":"Clean"},
    {"barcode":"0068274193996","product_name":"Nestle Splash Citron","brands":"Nestlé","ingredients_text":"Eau, arômes naturels, acide citrique, hexamétaphosphate de sodium, sorbate de potassium, benzoate de potassium, sucralose, acésulfame-potassium, edta de calcium et de disodium","additive_flags":"Clean"},
    {"barcode":"90446290","product_name":"Organics Viva Mat","brands":"Organics/Red Bull","ingredients_text":"Wasser, zucker, kohlensäure, zitronensaftkonzentrat, natürlicher mate-extrakt (0,33%), natürliche aromen aus pflanzenextrakten (0,05%: zitrone, koffein aus kaffeebohnen, johannisbrot, vanille), karamellzuckersirup","additive_flags":"Clean"},
    {"barcode":"4600680030296","product_name":"Nuts","brands":"Nestlé","ingredients_text":"Potato flakes, palm oil, salt, sugar, flavor enhancer (monosodium glutamate), onion powder, garlic powder, spices, natural flavoring, color (paprika extract)","additive_flags":"INS 621 MSG"},
    {"barcode":"70847016205","product_name":"Ultra Blue","brands":"Monster","ingredients_text":"Carbonated water, citric acid, erythritol, natural & artificial flavors, taurine, sodium citrate, panax ginseng extract, l-carnitine l-tartrate, caffeine, sorbic acid (preservative), sucralose, benzoic acid (preservative), niacinamide (vit. b3), acesulfame potassium, d-calcium pantothenate (vit. b5), salt, guarana extract, d-glucuronolactone, inositol, pyridoxine hydrochloride (vit. b6), blue #1, red #40, cyanocobalamin (vit. b12)","additive_flags":"Artificial colours (Blue #1, Red #40)"},
    {"barcode":"70847017707","product_name":"Monster Energy Zero Ultra","brands":"Monster","ingredients_text":"Carbonated water, citric acid, erythritol, taurine, sodium citrate, natural & artificial flavors, panax ginseng extract, l-carnitine l-tartrate, sucralose, caffeine, sorbic acid (preservative), benzoic acid (preservative), niacinamide (vit.b3), acesulfame potassium, d-calcium pantothenate (vit. b5), salt, guarana extract, d-glucuronolactone, inositol, pyridoxine hydrochloride (vit. b6), cyanocobalamin (vit. b12). Monster energy blend: taurine, panax ginseng extract, l-carnitine, caffeine, guarana extract, glucuronolactone, inositol","additive_flags":"Energy drink with caffeine"},
    {"barcode":"3256540011649","product_name":"Beignets Chocolat x8","brands":"Brioche Pasquier/Pitch","ingredients_text":"Farine de ble 30% - fourrage goût chocolat 25% [sirop de glucose-fructose - sucre - eau - chocolat 4.4% (sucre, pâte de cacao, poudre de cacao maigre, beurre de cacao, lactose, émulsifiant: lécithine de soja) - noisettes - épaississant: amidon de maïs - lait entier en poudre - arôme naturel de vanille] - huile de tournesol – levain 5% (farine de ble, eau, sel) – œufs frais 5% – sucre – huile de colza – sirop de fructose-glucose - emulsifiant: mono- et diglycérides d'acides gras - levure - sel – fibres de psyllium – gluten de ble – protéines de ble - antioxydant: acide ascorbique","additive_flags":"Clean"},
    {"barcode":"5050083713873","product_name":"Trésor Chocolat Lait","brands":"Kellogg's/Trésor","ingredients_text":"Farines de céréales (blé {26%}, avoine complète {17%}, riz {12%}), fourrage au chocolat au lait (sucre, huiles végétales {palme, tournesol, colza} en proportions variables, chocolat au lait {8.5%} {sucre, pâte de cacao, petit-lait en poudre, matière grasse du lait, lait entier en poudre, beurre de cacao}, sirop de glucose, cacao maigre en poudre, lait entier en poudre, lait écrémé en poudre, émulsifiant {lécithine de soja}, acidifiant {acide citrique}), sucre, sel, colorants (caroténoides, rocou), antioxydants (palmitate d'ascorbyle, alpha-tocophérol)","additive_flags":"Clean"},
    {"barcode":"70847020905","product_name":"Ultra Sunrise","brands":"Monster Energy","ingredients_text":"Carbonated water, natural flavors, erythritol, lemon pulp, citric acid, taurine, sodium citrate, panax ginseng extract, l-carnitine l-tartrate, potassium sorbate (preservative), caffeine, sucralose, sodium benzoate (preservative), niacinamide (vit. b3), acesulfame potassium, d-calcium pantothenate (vit. b5), salt, guarana extract, d-glucuronolactone, inositol, pyridoxine hydrochloride (vit. b6), yellow #5, yellow #6, cyanocobalamin (vit. b12)","additive_flags":"Artificial colours (Yellow #5, Yellow #6)"},
    {"barcode":"9064407928","product_name":"Delowar","brands":"Various","ingredients_text":"NON-FOOD — Voltage stabilizer/electrical product","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"5050083735196","product_name":"Kellogg's Trésor Duo Choco 375 GR","brands":"Kellogg's","ingredients_text":"Farines de céréales (riz {26%}, avoine complète {14%}, blé {11%}), fourrage au chocolat blanc (sucre, chocolat blanc {9%} {sucre, lait entier en poudre, beurre de cacao}, huiles végétales {palme, tournesol, colza}, lait écrémé en poudre, amidon modifié, petit-lait en poudre, lait entier en poudre, émulsifiant {lécithine de soja}, arômes), sucre, cacao en poudre, sel, antioxydant (palmitate d'ascorbyle, alpha-tocophérol), vitamines (niacine, b6, b2, b1, acide folique, b12) et fer. Peut contenir: fruits à coque","additive_flags":"Clean"},
    {"barcode":"70847877882","product_name":"Cane Soda Creamy Root Beer","brands":"Hansen's/Monster Energy Company","ingredients_text":"Contains: pure triple filtered carbonated water, sugar, caramel color, natural spices of wintergreen, birch, anise, sassafras, tahitian vanilla extract, citric acid","additive_flags":"INS 150d Caramel"},
    {"barcode":"50457366","product_name":"Heinz Ketchup","brands":"Heinz/Morrisons","ingredients_text":"Tomatoes (148g per 100g), spirit vinegar, sugar, salt, spice and herb extracts (celery), spice","additive_flags":"Clean"},
    {"barcode":"5050083932991","product_name":"80G Cracker Crisps Cream & Onion Special K","brands":"Kellogg's","ingredients_text":"Amidon de tapioca, pomme de terre déshydratée, farine de blé, assaisonnement crème acidulée et oignon (dextrose, crème acidulée en poudre [crème acidulée, lactose {du lait}], acide citrique, antioxydants {e304, e307}, oignon en poudre, sel, arôme {contient du lait}, extrait de levure, sucre, amidon modifié, ciboulette, huile de tournesol), sirop de glucose, caséine {du lait}, yaourt en poudre, acidifiants {acide citrique, acide malique, acide lactique}), huile de tournesol, farine de maïs","additive_flags":"Clean"},
    {"barcode":"8000500033593","product_name":"Maxi Kinder Surprise Garçon Spiderman Œuf de Chocolat au Lait 320g","brands":"Ferrero/Kinder","ingredients_text":"Chocolat supérieur au lait 45% (sucre, lait en poudre, beurre de cacao, pâte de cacao, émulsifiants: lécithines [soja], vanilline), lait écrémé en poudre, sucre, graisses végétales (palme, karité), beurre concentré, émulsifiants: lécithines [soja], vanilline","additive_flags":"Clean"},
    {"barcode":"8000500045497","product_name":"Nutella & Go","brands":"Nutella/Ferrero","ingredients_text":"Sugar, palm oil, hazelnuts (13%), skimmed milk powder (8.7%), fat-reduced cocoa (7.4%), emulsifier: lecithin (soya), vanillin. Breadsticks: wheat flour, palm oil, salt, barley malt extract, baker's yeast","additive_flags":"Clean"},
    {"barcode":"8858998581856","product_name":"Pepsi Lime Flavour","brands":"Pepsi/PEPSI","ingredients_text":"วัตถุเจือปนอาหาร (ins 290, ins 330, ins 331 (i)), สีธรรมชาติ (ins 150d), วัตถุที่ให้ความหวานแทนน้ำตาล (แอสปาแตม, อะซีซัลเฟม โพแทสเซียม, ซูคราโลส), วัตถุกันเสีย (ins 202, ins 211), แต่งกลิ่นธรรมชาติ (กลิ่นไลม์)","additive_flags":"INS 150d + INS 202 + INS 211"},
    {"barcode":"38000198885","product_name":"Sweetened Multi-Grain Cereal Natural Fruit","brands":"Kellogg's","ingredients_text":"Corn flour blend (whole grain yellow corn flour, degerminated yellow corn flour), sugar, wheat flour, whole grain oat flour, modified food starch, contains 2% or less of hydrogenated vegetable oil (coconut, soybean and/or cottonseed), oat fiber, salt, soluble corn fiber, natural flavor, red 40, turmeric extract color, blue 1, yellow 6, annatto extract color, bht for freshness, vitamins and minerals: vitamin c (sodium ascorbate and ascorbic acid), niacinamide","additive_flags":"Hydrogenated oil + Artificial colours + BHT"},
    {"barcode":"3272770094245","product_name":"Tartare l'Original Ail et Fines Herbes +10% Gratis","brands":"Tartare/Fromarsac/Savencia","ingredients_text":"Lait et crème pasteurisés, ail et fines herbes (2,6%), sel, poivre, conservateur: sorbate de potassium","additive_flags":"INS 202 preservative"},
    {"barcode":"9300657021696","product_name":"Spicy Peri Peri Mayonnaise","brands":"Heinz","ingredients_text":"Canola oil [protected with antioxidant (307b)], white vinegar, free range egg (8%), tomato puree, sugar, salt, lemon juice, garlic, peri peri chilli (0.3%), stabilisers (412, 415), antioxidants (307b from soy, 385), natural colour (paprika extract)","additive_flags":"Clean"},
    {"barcode":"9300605135574","product_name":"Sourz Snakes Alive","brands":"Nestlé","ingredients_text":"Glucose syrup, cane sugar, thickener (dextrin, roasted starch, acid treated starch or starch acetate) (wheat), food acids (malic, citric), gelatine, acidity regulator (sodium malate), humectant (glycerine), flavours, colours (carminic acid, paprika oleoresin, copper chlorophyllin, turmeric, vegetable carbon)","additive_flags":"Artificial colours"},
    {"barcode":"8000500205051","product_name":"Tronky Nocciola","brands":"Ferrero","ingredients_text":"Zucker, haselnüsse 19%, weizenmehl, pflanzliche fette (palm, shea), süssmolkenpulver, fettarmer kakao, magermilchpulver, kakaobutter, kakaomasse, vollmilchpulver, emulgator lecithine (soja), butterreinfett, backtriebmittel: natriumhydrogencarbonat, ammoniumcarbonate; salz, aromen","additive_flags":"Clean"},
    {"barcode":"4902505085697","product_name":"Rad Pen","brands":"Various","ingredients_text":"NON-FOOD — Stationery","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"5050083563133","product_name":"All-Bran Golden Crunch","brands":"Kellogg's","ingredients_text":"Wheat bran (26%), rice flour, sugar, wheat flour, sunflower oil, maize flour, salt, skimmed milk powder, flavouring, barley malt extract, emulsifiers (sunflower lecithin, soy lecithin), ammonium bicarbonate, sodium bicarbonate, dextrose. Vitamins & minerals: niacin, iron, vitamin b6, vitamin b2 (riboflavin), vitamin b1 (thiamin), folic acid, vitamin d, vitamin b12","additive_flags":"Clean"},
    {"barcode":"5000112643008","product_name":"Coca-Cola Zero Sugar Cinnamon","brands":"Coca-Cola","ingredients_text":"Wasser, kohlensäure, farbstoff e 150d, säuerungsmittel phosphorsäure, süßungsmittel (aspartam, acesulfam k), natürliches aroma, aroma koffein, säureregulator natriumcitrate","additive_flags":"INS 150d Caramel"},
    {"barcode":"9556404120277","product_name":"Pepsi Black","brands":"Pepsi","ingredients_text":"Carbonated water, colouring, phosphoric acid, sweeteners (aspartame, sucralose, acesulfame k), sodium citrate, flavouring (contains caffeine), preservatives (potassium sorbate, sodium benzoate), citric acid","additive_flags":"INS 202 + INS 211 preservatives"},
    {"barcode":"5449000132499","product_name":"Fanta Orange 1.75L","brands":"Fanta/Coca-Cola","ingredients_text":"Water, fructose glucose syrup, orange juice from concentrate (5%), carbon dioxide, dietary acid: citric acid and malic acid, acidity regulator: sodium gluconate, natural aromas, sweeteners: sodium cyclamate and sodium saccharine, antioxidant: ascorbic acid, stabilizer: guar gum, dye: beta-carotene","additive_flags":"Clean"},
    {"barcode":"5449000224026","product_name":"Coca Cola Zero Decafeine","brands":"Coca Cola/Coca-Cola-Light","ingredients_text":"Eau gazéifiée, colorant: e150d; acide phosphorique, édulcorants: aspartame","additive_flags":"INS 150d Caramel"},
    {"barcode":"64100236189","product_name":"Vector","brands":"Kellogg's","ingredients_text":"Rice, whole grain wheat, sugars (sugar, corn syrup, blackstrap molasses, honey, malted barley syrup), roasted soybeans, vegetable oil, soy protein concentrate, whole grain oats, rice flour, salt, natural flavour, wheat flakes, cinnamon, baking soda, soy lecithin, mixed tocopherols (for freshness), vitamins and minerals: ascorbic acid (vitamin c), dicalcium phosphate, magnesium oxide, niacinamide, zinc oxide, biotin, iron, d-calcium pantothenate, potassium iodide, vitamin a palmitate, manganese sulfate monohydrate, copper oxide","additive_flags":"Clean"},
    {"barcode":"2000000133479","product_name":"Kellogg's Extra Nocciole Caramellate","brands":"Kellogg's","ingredients_text":"Fiocchi d'avena integrali (51%), zucchero, olio di palma non idrogenato, farina di frumento, nocciole caramellate (6%) (nocciole, zucchero, antiossidanti {e464, e306}), cocco disidratato, cereali croccanti aromatizzati alla nocciola (riso croccante {farina di riso, farina di frumento, zucchero, farina di frumento maltato, siero di latte in polvere, sale, olio di colza non idrogenato, emulsionante [e471]}, zucchero, aroma naturale), melassa, sale, estratto di malto d'orzo, cannella","additive_flags":"Clean"},
    {"barcode":"8901725012977","product_name":"Sunfeast Marie Light","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, refined palm oil, invert sugar syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifiers (INS 471, INS 322)","additive_flags":"Clean"},
    {"barcode":"8901725016166","product_name":"Choco Fills","brands":"Sunfeast","ingredients_text":"Choco crème (sugar, refined palmolein, cocoa solids), refined wheat flour, sugar, invert syrup, liquid glucose, cocoa solids, milk solids, butter, raising agents, emulsifiers, salt","additive_flags":"Clean"},
    {"barcode":"8909081000256","product_name":"Dark Fantasy Sandwich Crème","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cocoa solids, invert syrup, milk solids, raising agents, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8909081000317","product_name":"Dark Fantasy Sandwich Crème","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cocoa solids, invert syrup, milk solids, raising agents, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8904188607933","product_name":"Green Chana Frozen","brands":"Saurbhi","ingredients_text":"Green chickpeas (frozen)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904340700397","product_name":"Pulse Litchi Flavour","brands":"Pass Pass","ingredients_text":"Sugar, glucose syrup, lychee flavour, acidity regulator, colours","additive_flags":"Verify colours"},
    {"barcode":"8904340700359","product_name":"Pulse Orange","brands":"Pass Pass","ingredients_text":"Sugar, glucose syrup, orange flavour, acidity regulator, colours","additive_flags":"Verify colours"},
    {"barcode":"8906172543807","product_name":"Black Forest","brands":"Hocco","ingredients_text":"Refined wheat flour, sugar, eggs, cocoa solids, edible vegetable oil, raising agents, emulsifiers, cherry flavour, colours","additive_flags":"Clean"},
    {"barcode":"8906097400179","product_name":"Coriander Powder","brands":"Zoff","ingredients_text":"Coriander powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908009186461","product_name":"Sport Evolve Performance Plant Protein Tropical Mango","brands":"Plix","ingredients_text":"Plant protein blend (pea, rice, soy), tropical mango flavour, sweetener (stevia), emulsifier","additive_flags":"Clean"},
    {"barcode":"8901117250000","product_name":"Prolyte ORS Orange Flavour","brands":"Cipla Health","ingredients_text":"Glucose, sodium chloride, potassium chloride, sodium citrate, orange flavour","additive_flags":"ORS — Regulated"},
    {"barcode":"8901719130724","product_name":"Parle 20-20 Gold","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, invert syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 322)","additive_flags":"Clean"},
    {"barcode":"8904300201018","product_name":"Coconut Crunchy","brands":"Various","ingredients_text":"Refined wheat flour, sugar, coconut, edible vegetable oil, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725013004","product_name":"Marie Light Family Pack","brands":"Sunfeast/ITC","ingredients_text":"Refined wheat flour, sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906009073729","product_name":"Big & Bold Fruit Blast","brands":"Unibic","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, dried fruits, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725000622","product_name":"Sunfeast Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901063164321","product_name":"Tiger Kreemz Orange","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, invert syrup, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8901063162549","product_name":"Marie Gold","brands":"Britannia","ingredients_text":"Refined wheat flour (73%), sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers (INS 471, INS 322)","additive_flags":"Clean"},
    {"barcode":"8902268011144","product_name":"Dream Lite","brands":"Anmol","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901052011742","product_name":"Rusk","brands":"Tata SoulFull","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, milk solids, raising agents, emulsifier, artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8904344626228","product_name":"Moon Original","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8904258703879","product_name":"ABC Juice","brands":"Raw Pressed","ingredients_text":"Apple, beetroot, carrot juice blend","additive_flags":"Clean"},
    {"barcode":"8904270005401","product_name":"Marie Go Round","brands":"Sunder","ingredients_text":"Refined wheat flour, sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901448904054","product_name":"Wafy Break","brands":"Various","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, flavours, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906021927062","product_name":"Apis Deseeded Dates","brands":"Apis","ingredients_text":"Deseeded dates (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8903023007709","product_name":"More Chironji","brands":"More","ingredients_text":"Chironji (charoli seeds)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901725003838","product_name":"Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906097402562","product_name":"Zoff Clove Whole","brands":"Zoff","ingredients_text":"Whole cloves (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906002348473","product_name":"Lobia Safed","brands":"Rajdhani","ingredients_text":"White cowpeas (lobia)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902901222517","product_name":"Ajwain","brands":"Good Life","ingredients_text":"Ajwain (carom seeds)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906006525504","product_name":"Top Start","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901063371026","product_name":"Marie Gold","brands":"Britannia","ingredients_text":"Refined wheat flour (73%), sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers (INS 471, INS 322)","additive_flags":"Clean"},
    {"barcode":"8901058866216","product_name":"Coffee Mocha","brands":"Nestlé","ingredients_text":"Instant coffee, sugar, milk solids, cocoa solids, emulsifier, flavours","additive_flags":"Clean"},
    {"barcode":"8901552007689","product_name":"Kantola","brands":"Ashoka","ingredients_text":"Refined wheat flour, potato, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901719255144","product_name":"Parle-G","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, invert syrup, refined palm oil, salt, skimmed milk powder, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 471), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901719404412","product_name":"Hide & Seek","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cocoa solids, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901719703034","product_name":"Krack Jack Original","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, salt, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901719656828","product_name":"FAB!","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, fruit jam, invert syrup, raising agents, emulsifiers, colours","additive_flags":"Clean"},
    {"barcode":"8901153001529","product_name":"Soan Papdi","brands":"Various","ingredients_text":"Sugar, gram flour, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906032016977","product_name":"Soya Chunks","brands":"Nutrela","ingredients_text":"Defatted soya flour","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906026995028","product_name":"Brimune Aloe Vera Juice 500ML","brands":"Various","ingredients_text":"Aloe vera juice, preservative","additive_flags":"Clean"},
    {"barcode":"8901725019419","product_name":"Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725000646","product_name":"Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8902901222357","product_name":"Phool Makhana","brands":"Good Life","ingredients_text":"Makhana (fox nuts)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901155301443","product_name":"Gits Gulabi Jamun","brands":"Gits","ingredients_text":"Milk solids, sugar, edible vegetable oil, cardamom, rose water","additive_flags":"Clean"},
    {"barcode":"8909081003905","product_name":"Rich Chocolate Cookies","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, cocoa solids, edible vegetable oil, invert syrup, raising agents, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8906001024798","product_name":"Four Cheese","brands":"Go","ingredients_text":"Milk solids, salt, emulsifying salts, preservative (INS 200), cheese blend","additive_flags":"INS 200 preservative"},
    {"barcode":"8903605017706","product_name":"Soy Sauce","brands":"Various","ingredients_text":"Water, soybean extract, salt, sugar, vinegar, acidity regulator, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8906010504021","product_name":"Balaji Wafers","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8906010504007","product_name":"Balaji Wafers","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8901719656613","product_name":"Parle Hide & Seek Fab Orange","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, cocoa solids, invert syrup, milk solids, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8906024450512","product_name":"Green Tea Natural","brands":"Various","ingredients_text":"Green tea (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906024451335","product_name":"Green Tea Lemon and Honey","brands":"Various","ingredients_text":"Green tea, lemon flavour, honey","additive_flags":"Clean"},
    {"barcode":"8901030456381","product_name":"Taaza Tea","brands":"Brooke Bond","ingredients_text":"100% black tea (CTC blend)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901719124402","product_name":"Magix Orange","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, invert syrup, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8901719122040","product_name":"Coconut","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, coconut, edible vegetable oil, invert syrup, raising agents, emulsifier, artificial coconut flavour","additive_flags":"Clean"},
    {"barcode":"8901719124396","product_name":"Magix Elaichi","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cardamom flavour, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8904006313367","product_name":"Oura","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901030825552","product_name":"Protein Plus","brands":"Horlicks","ingredients_text":"Milk solids, malted cereals, sugar, cocoa solids, wheat flour, minerals, vitamins, emulsifier (INS 471)","additive_flags":"Clean"},
    {"barcode":"8904132926806","product_name":"Good Life Besan","brands":"Good Life","ingredients_text":"Gram flour (besan)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908003746708","product_name":"ORS Lemon Drink","brands":"Electrorush","ingredients_text":"Glucose, sodium chloride, potassium chloride, sodium citrate, lemon flavour","additive_flags":"ORS — Regulated"}
]

elevated_count = 0
added_count = 0
purged_count = 0

for item in batch_41_rows:
    barcode = str(item["barcode"]).strip()
    pname = item["product_name"].strip()
    brand = item["brands"].strip()
    ing = item["ingredients_text"].strip()
    flags = item.get("additive_flags", "")
    
    # Check if non-food
    if "NON-FOOD" in ing.upper() or "NON-FOOD" in flags.upper() or "PURGE" in flags.upper():
        df_all = df_all[df_all['barcode'] != barcode]
        df_confirmed = df_confirmed[df_confirmed['barcode'] != barcode]
        df_needs_ver = df_needs_ver[df_needs_ver['barcode'] != barcode]
        purged_count += 1
        continue

    # Update or add in master DB
    idx_all = df_all[df_all['barcode'] == barcode].index
    status_tag = 'CONFIRMED_INDIA_890' if barcode.startswith('890') else 'CONFIRMED_FOREIGN'
    if len(idx_all) > 0:
        df_all.loc[idx_all, 'product_name'] = pname
        df_all.loc[idx_all, 'brands'] = brand
        df_all.loc[idx_all, 'ingredients_text'] = ing
    else:
        new_row = {
            'barcode': barcode,
            'product_name': pname,
            'brands': brand,
            'ingredients_text': ing,
            'sold_in_india_status': status_tag,
            'ingredient_confidence': 'HIGH',
            'status': 'KEEP',
            'data_source': 'Brand Official Publication',
            'source_license': 'User-submitted',
            'collection_method': 'API/CSV Import'
        }
        df_all = pd.concat([df_all, pd.DataFrame([new_row])], ignore_index=True)

    # Check if in needs_ver, promote to confirmed
    idx_nv = df_needs_ver[df_needs_ver['barcode'] == barcode].index
    if len(idx_nv) > 0:
        df_needs_ver = df_needs_ver[df_needs_ver['barcode'] != barcode]
        elevated_count += 1

    # Upsert in confirmed
    idx_c = df_confirmed[df_confirmed['barcode'] == barcode].index
    if len(idx_c) > 0:
        df_confirmed.loc[idx_c, 'product_name'] = pname
        df_confirmed.loc[idx_c, 'brands'] = brand
        df_confirmed.loc[idx_c, 'ingredients_text'] = ing
        df_confirmed.loc[idx_c, 'sold_in_india_status'] = status_tag
        df_confirmed.loc[idx_c, 'ingredient_confidence'] = 'HIGH'
        df_confirmed.loc[idx_c, 'status'] = 'KEEP'
    else:
        conf_row = {
            'barcode': barcode,
            'product_name': pname,
            'brands': brand,
            'ingredients_text': ing,
            'sold_in_india_status': status_tag,
            'ingredient_confidence': 'HIGH',
            'status': 'KEEP',
            'data_source': 'Brand Official Publication',
            'source_license': 'User-submitted',
            'collection_method': 'API/CSV Import'
        }
        df_confirmed = pd.concat([df_confirmed, pd.DataFrame([conf_row])], ignore_index=True)
        added_count += 1

# Save updated files
df_all.to_csv(all_supabase_csv, index=False)
df_confirmed.to_csv(confirmed_csv, index=False)
df_needs_ver.to_csv(needs_ver_csv, index=False)

print(f"Batch 41 Processing Summary:")
print(f"  Elevated from Needs Verification to Confirmed: {elevated_count}")
print(f"  Newly added to Confirmed: {added_count}")
print(f"  Purged Non-Food Barcodes: {purged_count}")
print(f"  Final Master CSV Count: {len(df_all)}")
print(f"  Final Confirmed CSV Count: {len(df_confirmed)}")
print(f"  Final Needs Verification CSV Count: {len(df_needs_ver)}")
