import os
import sys
import pandas as pd
import re

sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = r"c:\Users\thout\Downloads\check it"

all_supabase_csv = os.path.join(BASE_DIR, "all_supabase_products.csv")
confirmed_csv = os.path.join(BASE_DIR, "india_products_confirmed.csv")
needs_ver_csv = os.path.join(BASE_DIR, "india_products_needs_verification.csv")

print("=== EXECUTING BATCH 15 INGREDIENTS INTEGRATION & PURGE ===")

df_all = pd.read_csv(all_supabase_csv, dtype=str)
df_confirmed = pd.read_csv(confirmed_csv, dtype=str) if os.path.exists(confirmed_csv) else pd.DataFrame()
df_needs_ver = pd.read_csv(needs_ver_csv, dtype=str) if os.path.exists(needs_ver_csv) else pd.DataFrame()

for df in [df_all, df_confirmed, df_needs_ver]:
    if not df.empty and 'barcode' in df.columns:
        df['barcode'] = df['barcode'].astype(str).str.strip()

batch_15_rows = [
    {"barcode":"8901063165618","product_name":"Little Hearts","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322)","additive_flags":"Clean"},
    {"barcode":"8901063165670","product_name":"Britannia Little Hearts","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, milk solids, raising agents, salt, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901063016934","product_name":"Britannia 5050","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, salt, raising agents, emulsifier, artificial butter flavour","additive_flags":"Clean"},
    {"barcode":"8901063013278","product_name":"Britannia 5050","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, salt, raising agents, emulsifier, artificial butter flavour","additive_flags":"Clean"},
    {"barcode":"8901063139186","product_name":"Bourbon","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cocoa solids, invert syrup, raising agents, salt, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8901063139213","product_name":"Treat Jim Jam","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), invert syrup, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322), artificial vanilla flavour, colours (INS 122, INS 110)","additive_flags":"INS 122 + INS 110"},
    {"barcode":"8901063139374","product_name":"Britannia Bourbon 200g","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), cocoa solids, invert syrup, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifiers (INS 322, INS 471), artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8901063028258","product_name":"Britannia Nice Time","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, coconut (12%), edible vegetable oil (palm), invert syrup, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322), artificial coconut flavour","additive_flags":"Clean"},
    {"barcode":"8901063012578","product_name":"Britannia Milk Bikis","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, milk solids, edible vegetable oil (palm), invert syrup, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901063017399","product_name":"Britannia 50-50 Maska Chaska","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), invert syrup, salt, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 322), artificial butter flavour","additive_flags":"Clean"},
    {"barcode":"8901063014206","product_name":"Britannia Vita Marie Gold","brands":"Britannia","ingredients_text":"Refined wheat flour (70%), sugar, refined palm oil, invert sugar syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifiers (INS 471, INS 322), added vitamins & minerals","additive_flags":"Clean"},
    {"barcode":"8901063138162","product_name":"Britannia NutriChoice Arrowroot","brands":"Britannia","ingredients_text":"Whole wheat flour, arrowroot flour, sugar, edible vegetable oil (palm), raising agents, salt, emulsifiers, added vitamins & minerals","additive_flags":"Clean"},
    {"barcode":"8901063142817","product_name":"Britannia NutriChoice Digestive 125g","brands":"Britannia","ingredients_text":"Whole wheat flour (71%), sugar, edible vegetable oil (palm), raising agents (INS 503(ii), INS 500(ii)), salt, emulsifiers (INS 471, INS 322), added vitamins & minerals","additive_flags":"Clean"},
    {"barcode":"8901063029323","product_name":"Britannia Jim Jam","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), invert syrup, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322), artificial vanilla flavour, colours (INS 122, INS 110)","additive_flags":"INS 122 + INS 110"},
    {"barcode":"8901063363960","product_name":"Britannia Gobbles Chocolate Cake","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, eggs, edible vegetable oil (palm), glucose syrup, cocoa solids (3%), raising agents (INS 500(ii), INS 503(ii)), emulsifiers (INS 471, INS 475), preservative (INS 202), artificial chocolate flavour, colour (INS 150c)","additive_flags":"INS 202 preservative"},
    {"barcode":"8901063146938","product_name":"Britannia Winkin Cow Bourbon Shake","brands":"Britannia","ingredients_text":"Toned milk, sugar, cocoa solids, artificial chocolate flavour, stabilizers (INS 466, INS 407), emulsifier (INS 471), colour (INS 150c)","additive_flags":"INS 150c"},
    {"barcode":"8901063146952","product_name":"Britannia Winkin Cow Strawberry Shake","brands":"Britannia","ingredients_text":"Toned milk, sugar, strawberry flavour, stabilizers (INS 466, INS 407), emulsifier (INS 471), colour (INS 122)","additive_flags":"INS 122 Carmoisine"},
    {"barcode":"8901063092709","product_name":"Britannia Good Day Cashew","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil (palm), sugar, cashew nuts (4.5%), invert syrup, milk solids, butter (0.6%), raising agents (INS 503(i), INS 500(i)), salt, emulsifier (soya lecithin INS 322)","additive_flags":"Clean"},
    {"barcode":"8901063094291","product_name":"Britannia Good Day Pista Badam","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil (palm), sugar, pistachio (3%), almond (2%), invert syrup, milk solids, raising agents (INS 503(i), INS 500(i)), salt, emulsifier (soya lecithin INS 322)","additive_flags":"Clean"},
    {"barcode":"8901063136779","product_name":"Britannia Good Day Choco Almond","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil (palm), sugar, cocoa solids, almond (3%), invert syrup, milk solids, raising agents (INS 503(i), INS 500(i)), salt, emulsifier (soya lecithin INS 322)","additive_flags":"Clean"},
    {"barcode":"8901063342910","product_name":"Britannia Brown Bread","brands":"Britannia","ingredients_text":"Whole wheat flour (approx. 50%), refined wheat flour, water, sugar, edible vegetable oil, gluten, yeast, iodized salt, preservative (INS 282), emulsifiers (INS 471, INS 472e)","additive_flags":"INS 282 preservative"},
    {"barcode":"8901063343528","product_name":"Britannia Vitarich Sandwich Bread","brands":"Britannia","ingredients_text":"Refined wheat flour, water, sugar, edible vegetable oil, gluten, yeast, iodized salt, preservative (INS 282), emulsifiers (INS 471, INS 472e), vitamins","additive_flags":"INS 282 preservative"},
    {"barcode":"8901719135477","product_name":"Parle-G Gold","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, invert syrup, refined palm oil, salt, skimmed milk powder, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 471), dough conditioner, artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901719123801","product_name":"Parle Monaco Classic","brands":"Parle","ingredients_text":"Refined wheat flour, edible vegetable oil (palm), salt, sugar, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 322), artificial butter flavour","additive_flags":"Clean"},
    {"barcode":"8901719124006","product_name":"Parle Krackjack","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), invert syrup, salt, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 322), artificial butter flavour","additive_flags":"Clean"},
    {"barcode":"8901719136801","product_name":"Parle Hide & Seek Milano Creme","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), cocoa solids, invert syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 322), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901719136757","product_name":"Parle Hide & Seek Finest Choco","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), cocoa solids (6%), invert syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 322), artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8901719137846","product_name":"Parle Milano Vanilla","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), invert syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 322), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901719126970","product_name":"Parle 20-20 Cashew Biscuits","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), cashew nuts (8%), invert syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901719114038","product_name":"Parle Fab! Jam","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, fruit jam (pineapple, apple), edible vegetable oil (palm), invert syrup, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322), colours (INS 110, INS 102)","additive_flags":"INS 110 + INS 102"},
    {"barcode":"8901719127236","product_name":"Parle Rusk","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), invert syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901719119286","product_name":"Parle Mango Bite","brands":"Parle","ingredients_text":"Sugar, glucose syrup, mango pulp, acidity regulator (INS 330), artificial mango flavour, colour (INS 160c)","additive_flags":"Clean"},
    {"barcode":"8901719110023","product_name":"Parle Hide & Seek Centre Filled Cookies","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), cocoa solids, invert syrup, milk solids, raising agents, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8901719506345","product_name":"Parle Kreams Gold Cardamom","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), invert syrup, milk solids, cardamom, raising agents, emulsifiers, artificial cardamom flavour","additive_flags":"Clean"},
    {"barcode":"8901719123443","product_name":"Parle Kismis","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, raisins, edible vegetable oil (palm), invert syrup, raising agents, emulsifiers, salt","additive_flags":"Clean"},
    {"barcode":"8901725017545","product_name":"Sunfeast Nice","brands":"ITC","ingredients_text":"Refined wheat flour, sugar, coconut, edible vegetable oil (palm), invert syrup, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322), artificial coconut flavour","additive_flags":"Clean"},
    {"barcode":"8901725015916","product_name":"Sunfeast Dark Fantasy Choco Fills","brands":"ITC","ingredients_text":"Choco crème (sugar, refined palmolein, refined palm oil, cocoa solids), refined wheat flour, sugar, invert syrup, liquid glucose, edible vegetable oil, cocoa solids, milk solids, butter, raising agents (INS 503(ii), INS 500(i)), emulsifiers (INS 322, INS 471), salt","additive_flags":"Clean"},
    {"barcode":"8901725016265","product_name":"Sunfeast Dark Fantasy Bourbon","brands":"ITC","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), cocoa solids, invert syrup, raising agents (INS 503(ii), INS 500(i)), emulsifiers (INS 322, INS 471), salt, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8901725000622","product_name":"Sunfeast Mom's Magic Cashew & Almond","brands":"ITC","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725006143","product_name":"Sunfeast Marie Light","brands":"ITC","ingredients_text":"Refined wheat flour, sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725119201","product_name":"Sunfeast Yippee! Noodles","brands":"ITC","ingredients_text":"Instant noodles: Refined wheat flour (78.4%), refined palm oil, iodized salt, wheat gluten, thickeners (INS 508, INS 412); Masala: spices, dehydrated vegetables, sugar, salt, flavour enhancers (INS 621, INS 627, INS 631)","additive_flags":"INS 621 MSG"},
    {"barcode":"8901725114022","product_name":"Sunfeast Yippee! Magic Masala","brands":"ITC","ingredients_text":"Instant noodles: Refined wheat flour, refined palm oil, iodized salt, wheat gluten, thickeners; Masala: spices, dehydrated vegetables, sugar, salt, flavour enhancers (INS 621)","additive_flags":"INS 621 MSG"},
    {"barcode":"8909081010033","product_name":"Bingo Chilli Cheese Baked Puff","brands":"ITC","ingredients_text":"Refined wheat flour, edible vegetable oil (palm), cheese powder, spices, salt, sugar, flavour enhancers (INS 621), colours (INS 160c), raising agents","additive_flags":"INS 621 MSG"},
    {"barcode":"8901725013714","product_name":"Bingo Mad Angles Achaari Masti","brands":"ITC","ingredients_text":"Corn grits, edible vegetable oil (palmolein), rice grits, gram flour, spices, salt, sugar, flavour enhancers (INS 621, INS 627, INS 631), acidity regulators, colours (INS 160c)","additive_flags":"INS 621 MSG + INS 160c"},
    {"barcode":"8901725004217","product_name":"Bingo Tedhe Medhe Tomato","brands":"ITC","ingredients_text":"Corn grits, edible vegetable oil (palmolein), rice grits, gram flour, spices, salt, sugar, tomato powder, flavour enhancers (INS 621, INS 627, INS 631), acidity regulators, colours (INS 160c)","additive_flags":"INS 621 MSG + INS 160c"},
    {"barcode":"8906009079127","product_name":"Unibic Milk Cookies","brands":"Unibic","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), milk solids, invert syrup, raising agents, salt, emulsifiers, artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8906009070902","product_name":"Unibic Honey Oatmeal","brands":"Unibic","ingredients_text":"Whole wheat flour, oats, sugar, honey, edible vegetable oil (palm), invert syrup, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906009071602","product_name":"Unibic Choco Nut","brands":"Unibic","ingredients_text":"Refined wheat flour, sugar, cocoa solids, edible vegetable oil (palm), invert syrup, raising agents, salt, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8906009070520","product_name":"Unibic Orange Splash Cookies","brands":"Unibic","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), orange flavour, invert syrup, raising agents, salt, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8906009077314","product_name":"Unibic Honey Oatmeal Cookies","brands":"Unibic","ingredients_text":"Whole wheat flour, oats, sugar, honey, edible vegetable oil (palm), invert syrup, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906009073958","product_name":"Unibic Coconut Cookies","brands":"Unibic","ingredients_text":"Refined wheat flour, sugar, coconut, edible vegetable oil (palm), invert syrup, raising agents, salt, emulsifiers, artificial coconut flavour","additive_flags":"Clean"},
    {"barcode":"8901928112009","product_name":"Bisk Farm Nice","brands":"Bisk Farm","ingredients_text":"Refined wheat flour, sugar, coconut, edible vegetable oil (palm), invert syrup, raising agents, salt, emulsifier, artificial coconut flavour","additive_flags":"Clean"},
    {"barcode":"8901928300741","product_name":"Bisk Farm Top Gold","brands":"Bisk Farm","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), invert syrup, milk solids, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906017862520","product_name":"Bisk Farm Burst Wafers","brands":"Bisk Farm","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), cocoa solids, invert syrup, raising agents, emulsifiers, artificial chocolate flavour, antioxidant (INS 319)","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8906033742844","product_name":"McVitie's Digestive Multi 7 Grain","brands":"McVitie's","ingredients_text":"Whole wheat flour, oats, barley, rye, millet, corn, rice flour, sugar, edible vegetable oil (palm), invert syrup, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906033742851","product_name":"McVitie's Hobnobs","brands":"McVitie's","ingredients_text":"Whole wheat flour, oats, sugar, edible vegetable oil (palm), invert syrup, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906033746040","product_name":"McVitie's Hobnobs Oats Cookies","brands":"McVitie's","ingredients_text":"Whole wheat flour, oats, sugar, edible vegetable oil (palm), invert syrup, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725101374","product_name":"Sunfeast Dark Fantasy Original 75g","brands":"ITC","ingredients_text":"Choco crème (sugar, refined palmolein, refined palm oil, cocoa solids), refined wheat flour, sugar, invert syrup, liquid glucose, edible vegetable oil, cocoa solids, milk solids, butter, raising agents, emulsifiers, salt","additive_flags":"Clean"},
    {"barcode":"8901725136215","product_name":"Sunfeast Dark Fantasy BIG Choco Fills","brands":"ITC","ingredients_text":"Choco crème (sugar, refined palmolein, refined palm oil, cocoa solids), refined wheat flour, sugar, invert syrup, liquid glucose, cocoa solids, milk solids, butter, raising agents, emulsifiers, salt","additive_flags":"Clean"},
    {"barcode":"8901063368026","product_name":"Britannia Gobbles Fruit Cake 55g","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, eggs, edible vegetable oil (palm), glucose syrup, mixed fruit peel (2%), raising agents (INS 500(ii), INS 503(ii)), emulsifiers (INS 471, INS 475), preservative (INS 202), artificial flavours, colour (INS 160a)","additive_flags":"INS 202 preservative"},
    {"barcode":"8901063325074","product_name":"Britannia Toastea","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil (palm), invert syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), salt, emulsifier (INS 322), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8904063226372","product_name":"Haldiram's Veggie And Paneer Momos","brands":"Haldiram's","ingredients_text":"Refined wheat flour, paneer, vegetables (cabbage, carrot, onion), edible vegetable oil, spices, salt, sugar, soy sauce","additive_flags":"Clean"},
    {"barcode":"8904063281234","product_name":"Haldiram's Phulka Roti","brands":"Haldiram's","ingredients_text":"Whole wheat flour, water, edible vegetable oil, salt","additive_flags":"Clean"},
    {"barcode":"8904063254696","product_name":"Haldiram's Aloo Bhujia","brands":"Haldiram's","ingredients_text":"Potato flakes & starch, edible vegetable oil (palmolein), gram flour, iodized salt, spices (red chilli, cumin), colour (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904004403770","product_name":"Haldiram's Moong Dal","brands":"Haldiram's","ingredients_text":"Moong dal, edible vegetable oil (palmolein), iodized salt, spices (red chilli, black pepper, asafoetida)","additive_flags":"Clean"},
    {"barcode":"8904004403534","product_name":"Haldiram's Tasty Nuts","brands":"Haldiram's","ingredients_text":"Peanuts, edible vegetable oil (palmolein), iodized salt, spices (red chilli, black pepper)","additive_flags":"Clean"},
    {"barcode":"8904063216403","product_name":"Haldiram's Khatta Meetha","brands":"Haldiram's","ingredients_text":"Rice flakes, edible vegetable oil (palmolein), sugar, peanuts, sago, iodized salt, spices, raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904063216168","product_name":"Haldiram's Bombay Mix","brands":"Haldiram's","ingredients_text":"Rice flakes, gram flour, edible vegetable oil (palmolein), peanuts, sago, iodized salt, spices, raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904063230133","product_name":"Haldiram's Cornflakes Mixture","brands":"Haldiram's","ingredients_text":"Corn flakes, edible vegetable oil (palmolein), peanuts, sago, iodized salt, spices, sugar, raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904063203441","product_name":"Haldiram's Ratlami Mixture","brands":"Haldiram's","ingredients_text":"Rice flakes, gram flour, edible vegetable oil (palmolein), peanuts, sago, iodized salt, spices (red chilli, cumin, black pepper), raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904063200570","product_name":"Haldiram's Chai Puri","brands":"Haldiram's","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, salt, spices, raising agents","additive_flags":"Clean"},
    {"barcode":"8904063253262","product_name":"Haldiram's Boondi","brands":"Haldiram's","ingredients_text":"Gram flour (besan), edible vegetable oil (palmolein), iodized salt, spices, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904063258410","product_name":"Haldiram's Yellow Banana Chips","brands":"Haldiram's","ingredients_text":"Banana, edible vegetable oil (coconut/palmolein), iodized salt","additive_flags":"Clean"},
    {"barcode":"8904063254573","product_name":"Haldiram's Tea Time Khari","brands":"Haldiram's","ingredients_text":"Refined wheat flour, edible vegetable oil, salt, raising agents","additive_flags":"Clean"},
    {"barcode":"8904063253415","product_name":"Haldiram's Roasted Chana Cracker Heeng Jeera","brands":"Haldiram's","ingredients_text":"Roasted chana, edible vegetable oil (palmolein), iodized salt, spices (asafoetida, cumin, red chilli)","additive_flags":"Clean"},
    {"barcode":"8904063254450","product_name":"Haldiram's Punjabi Tadka","brands":"Haldiram's","ingredients_text":"Rice flakes, gram flour, edible vegetable oil (palmolein), peanuts, sago, iodized salt, spices (cumin, turmeric, red chilli), raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8906010500344","product_name":"Balaji Wafers Salted","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, salt","additive_flags":"Clean"},
    {"barcode":"8906010500511","product_name":"Balaji Wafers Chataka Pataka","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, spices, salt, sugar, acidity regulators, colours","additive_flags":"Clean"},
    {"barcode":"8906010500610","product_name":"Balaji Wafers Masala Masti","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, spices, salt, sugar, flavour enhancers (INS 621), colours (INS 160c)","additive_flags":"INS 621 MSG"},
    {"barcode":"8906010500818","product_name":"Balaji Wafers Chatpata Chutney","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, spices, salt, sugar, acidity regulators, colours","additive_flags":"Clean"},
    {"barcode":"8906010501025","product_name":"Balaji Wafers Chilli Chatka","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, spices, salt, sugar, flavour enhancers (INS 621), colours (INS 160c)","additive_flags":"INS 621 MSG"},
    {"barcode":"8901262150095","product_name":"Amul Gold Milk 200ml","brands":"Amul","ingredients_text":"Standardized milk (4.5% fat, 8.5% SNF), vitamins A & D","additive_flags":"Clean"},
    {"barcode":"8901262153577","product_name":"Amul Taaza Toned Milk 200ml","brands":"Amul","ingredients_text":"Toned milk (3.0% fat, 8.5% SNF), vitamins A & D","additive_flags":"Clean"},
    {"barcode":"8901262010436","product_name":"Amul White Unsalted Butter","brands":"Amul","ingredients_text":"Pasteurized milk cream","additive_flags":"Clean"},
    {"barcode":"8901262030243","product_name":"Amul Ghee","brands":"Amul","ingredients_text":"Milk solids (pure cow ghee)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901262030250","product_name":"Amul Pure Ghee","brands":"Amul","ingredients_text":"Milk solids (pure cow ghee)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901262200271","product_name":"Amul Dahi","brands":"Amul","ingredients_text":"Pasteurized toned milk, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8901262180030","product_name":"Amul Paneer","brands":"Amul","ingredients_text":"Milk solids, citric acid (coagulant)","additive_flags":"Clean"},
    {"barcode":"8901262020404","product_name":"Amul Cheese Slices","brands":"Amul","ingredients_text":"Milk solids, salt, emulsifying salts (INS 331, INS 452), preservative (INS 200), colour (INS 160a)","additive_flags":"INS 200 preservative"},
    {"barcode":"8901262020091","product_name":"Amul Cheese Cubes","brands":"Amul","ingredients_text":"Milk solids, salt, emulsifying salts (INS 331, INS 452), preservative (INS 200)","additive_flags":"INS 200 preservative"},
    {"barcode":"8901262151375","product_name":"Amul Cool Kesar","brands":"Amul","ingredients_text":"Toned milk, sugar, kesar flavour, stabilizers (INS 466, INS 407), emulsifier (INS 471), colour (INS 160a)","additive_flags":"Clean"},
    {"barcode":"8901262151429","product_name":"Amul Kool Coffee","brands":"Amul","ingredients_text":"Toned milk, sugar, coffee, stabilizers, emulsifier, colour (INS 150c)","additive_flags":"INS 150c"},
    {"barcode":"8901262200622","product_name":"Amul Masti","brands":"Amul","ingredients_text":"Pasteurised toned milk, milk solids, active culture","additive_flags":"Clean"},
    {"barcode":"8901262174565","product_name":"Amul Punjabi Samosa","brands":"Amul","ingredients_text":"Refined wheat flour, potato, peas, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901262222471","product_name":"Amul Instant Mashed Potato","brands":"Amul","ingredients_text":"Dehydrated potato flakes, salt, emulsifier (INS 471), antioxidant (INS 304)","additive_flags":"Clean"},
    {"barcode":"8901262200172","product_name":"Amul Lassi 1L","brands":"Amul","ingredients_text":"Toned milk, sugar, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8901262178853","product_name":"Amul Aloo Tikki","brands":"Amul","ingredients_text":"Potato, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8901262071680","product_name":"Amul Hazelnut Chocolate","brands":"Amul","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, hazelnuts, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901262171557","product_name":"Amul Chocolate Family Pack","brands":"Amul","ingredients_text":"Toned milk, sugar, cocoa solids, edible vegetable oil, stabilizers, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901262223539","product_name":"Amul Chocolate Cookies","brands":"Amul","ingredients_text":"Refined wheat flour, sugar, cocoa solids, edible vegetable oil, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901262153423","product_name":"Amul High Protein Milk","brands":"Amul","ingredients_text":"Standardized milk, milk protein, vitamins","additive_flags":"Clean"},
    {"barcode":"8901262080101","product_name":"Amul Spray Infant Milk Food","brands":"Amul","ingredients_text":"Demineralized whey, vegetable oils, skimmed milk powder, lactose, minerals, vitamins","additive_flags":"Regulated infant food"},
    {"barcode":"8901262120029","product_name":"Amul Mithai Mate","brands":"Amul","ingredients_text":"Milk solids, sugar","additive_flags":"Clean"},
    {"barcode":"8901262070843","product_name":"Amul Tropical Orange","brands":"Amul","ingredients_text":"Toned milk, sugar, orange flavour, stabilizers, emulsifiers, colours","additive_flags":"Verify colours"},
    {"barcode":"8901262175869","product_name":"Amul Shalimar","brands":"Amul","ingredients_text":"Toned milk, sugar, flavour, stabilizers","additive_flags":"Clean"},
    {"barcode":"8901262220125","product_name":"Amul Sandwich Bread","brands":"Amul","ingredients_text":"Refined wheat flour, water, sugar, milk solids, edible vegetable oil, yeast, salt, preservative (INS 282)","additive_flags":"INS 282 preservative"},
    {"barcode":"8901058018493","product_name":"Maggi 2-Minute Noodles Masala","brands":"Nestlé","ingredients_text":"Noodles: Refined wheat flour (maida), palm oil, iodized salt, wheat gluten, thickeners (INS 508, INS 412), acidity regulators (INS 501(i), INS 500(i)); Tastemaker: salt, onion, sugar, coriander, chilli, turmeric, garlic, cumin, fenugreek, antioxidant (INS 319)","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8901058000221","product_name":"Maggi 2 Minute Noodles","brands":"Nestlé","ingredients_text":"Noodles: Refined wheat flour, palm oil, iodized salt, wheat gluten, thickeners (INS 508, INS 412), acidity regulators; Tastemaker: salt, spices, sugar, flavour enhancers (INS 621), antioxidant (INS 319)","additive_flags":"INS 621 MSG + INS 319 TBHQ"},
    {"barcode":"8901058901580","product_name":"Maggi Special Masala Noodles","brands":"Nestlé","ingredients_text":"Noodles: Refined wheat flour, palm oil, salt, wheat gluten, thickeners, acidity regulators; Tastemaker: salt, spices, sugar, flavour enhancers (INS 621), antioxidant (INS 319)","additive_flags":"INS 621 MSG + INS 319 TBHQ"},
    {"barcode":"8901058854107","product_name":"Maggi Oats Masala Noodles","brands":"Nestlé","ingredients_text":"Oats flour, refined wheat flour, palm oil, salt, thickeners, acidity regulators; Tastemaker: salt, spices, sugar, flavour enhancers (INS 621), antioxidant (INS 319)","additive_flags":"INS 621 MSG + INS 319 TBHQ"},
    {"barcode":"8901058009699","product_name":"Maggi Atta Noodles","brands":"Nestlé","ingredients_text":"Whole wheat flour (atta), palm oil, salt, wheat gluten, thickeners, acidity regulators; Tastemaker: salt, spices, flavour enhancers (INS 621), antioxidant (INS 319)","additive_flags":"INS 621 MSG + INS 319 TBHQ"},
    {"barcode":"8901058006643","product_name":"Maggi 2 Minutes Noodles Masala","brands":"Nestlé","ingredients_text":"Noodles: Refined wheat flour, palm oil, iodized salt, wheat gluten, thickeners (INS 508, INS 412), acidity regulators; Tastemaker: salt, onion, sugar, spices, antioxidant (INS 319)","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8901058002270","product_name":"Maggi Spicy Garlic Noodles","brands":"Nestlé","ingredients_text":"Noodles: Refined wheat flour, palm oil, salt, thickeners; Tastemaker: salt, garlic, chilli, spices, flavour enhancers (INS 621), antioxidant (INS 319)","additive_flags":"INS 621 MSG + INS 319 TBHQ"},
    {"barcode":"8901058013665","product_name":"Maggi Hot and Sweet Noodles","brands":"Nestlé","ingredients_text":"Noodles: Refined wheat flour, palm oil, salt, thickeners; Tastemaker: salt, sugar, chilli, garlic, flavour enhancers (INS 621), antioxidant (INS 319)","additive_flags":"INS 621 MSG + INS 319 TBHQ"},
    {"barcode":"8901058866711","product_name":"Maggi Veg Atta Noodles 290g","brands":"Nestlé","ingredients_text":"Whole wheat flour, palm oil, salt, thickeners; Tastemaker: salt, spices, flavour enhancers (INS 621), antioxidant (INS 319)","additive_flags":"INS 621 MSG + INS 319 TBHQ"},
    {"barcode":"8901058016116","product_name":"KitKat 50","brands":"Nestlé","ingredients_text":"Refined wheat flour, sugar, cocoa butter, milk solids, cocoa mass, emulsifier (INS 322), yeast, salt, raising agent (INS 500(ii)), flavouring","additive_flags":"Clean"},
    {"barcode":"8901058023558","product_name":"KitKat Dark Chocolate Minis","brands":"Nestlé","ingredients_text":"Refined wheat flour, sugar, cocoa butter, cocoa solids, milk solids, emulsifier (INS 322), yeast, salt, raising agent (INS 500(ii)), flavouring","additive_flags":"Clean"},
    {"barcode":"8901058905472","product_name":"Kit Kat","brands":"Nestlé","ingredients_text":"Refined wheat flour, sugar, cocoa butter, milk solids, cocoa mass, emulsifier (INS 322), yeast, salt, raising agent (INS 500(ii)), flavouring","additive_flags":"Clean"},
    {"barcode":"8901058852141","product_name":"KitKat Caramel Chocolate Coated Wafer","brands":"Nestlé","ingredients_text":"Refined wheat flour, sugar, cocoa butter, milk solids, glucose syrup, emulsifier (INS 322), yeast, salt, raising agent, flavouring","additive_flags":"Clean"},
    {"barcode":"8901058010701","product_name":"Nestlé Munch Vanilla Flavour","brands":"Nestlé","ingredients_text":"Sugar, refined wheat flour, hydrogenated vegetable oil (palm), milk solids, cocoa solids, emulsifier (INS 322), salt, raising agent (INS 500(ii)), artificial vanilla flavour","additive_flags":"Hydrogenated oil"},
    {"barcode":"8901058900361","product_name":"Nestlé Munch Nuts","brands":"Nestlé","ingredients_text":"Sugar, refined wheat flour, hydrogenated vegetable oil (palm), peanuts, milk solids, cocoa solids, emulsifier (INS 322), salt, raising agent","additive_flags":"Hydrogenated oil"},
    {"barcode":"8901058875577","product_name":"Milkybar","brands":"Nestlé","ingredients_text":"Sugar, milk solids, cocoa butter, emulsifier (INS 322), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901058016055","product_name":"Nescafé Classic","brands":"Nestlé","ingredients_text":"100% instant coffee","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901058865660","product_name":"Nescafé Gold Cappuccino","brands":"Nestlé","ingredients_text":"Instant coffee, sugar, milk solids, glucose syrup, hydrogenated vegetable oil (palm kernel), salt, stabilizers (INS 340(ii), INS 452(i)), emulsifier (INS 471), anticaking agent (INS 551)","additive_flags":"Hydrogenated oil"},
    {"barcode":"8901058011401","product_name":"Nescafé Ice Roast","brands":"Nestlé","ingredients_text":"Coffee beans (100% instant coffee)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901058014723","product_name":"Nescafé Sunrise","brands":"Nestlé","ingredients_text":"Coffee, chicory","additive_flags":"Clean"},
    {"barcode":"8901058869453","product_name":"EveryDay Dairy Whitener","brands":"Nestlé","ingredients_text":"Milk solids, sugar, emulsifier (INS 322), stabilizers","additive_flags":"Clean"},
    {"barcode":"8901058007060","product_name":"Milkmaid Mini","brands":"Nestlé","ingredients_text":"Milk solids, sugar","additive_flags":"Clean"},
    {"barcode":"8901058897500","product_name":"Nestlé Nan Pro 2","brands":"Nestlé","ingredients_text":"Demineralized whey, vegetable oils, skimmed milk powder, lactose, minerals, vitamins, emulsifier","additive_flags":"Regulated infant food"},
    {"barcode":"8901058018400","product_name":"Nestlé Cerelac","brands":"Nestlé","ingredients_text":"Wheat flour, sugar, milk solids, minerals, vitamins, emulsifier (INS 322)","additive_flags":"Regulated infant food"},
    {"barcode":"8901058004922","product_name":"Maggi Rich Tomato Ketchup","brands":"Nestlé","ingredients_text":"Tomato paste, sugar, water, vinegar, salt, spices, acidity regulator (INS 260), preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901058008388","product_name":"Maggi Hot & Sweet Tomato Chilli Sauce","brands":"Nestlé","ingredients_text":"Tomato paste, sugar, water, vinegar, salt, chilli, garlic, acidity regulator (INS 260), preservative (INS 211), thickener (INS 1422)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901058003055","product_name":"Maggi Pazzta Cheese Macaroni","brands":"Nestlé","ingredients_text":"Macaroni: Durum wheat semolina, salt; Tastemaker: milk solids, cheese powder, sugar, salt, palm oil, thickeners (INS 1422, INS 412), flavour enhancers (INS 621, INS 627, INS 631), artificial cheese flavour, colour (INS 160a)","additive_flags":"INS 621 MSG"},
    {"barcode":"8901058014846","product_name":"Maggi Pazzta Cheesy Tomato Twist","brands":"Nestlé","ingredients_text":"Macaroni: Durum wheat semolina, salt; Tastemaker: tomato powder, milk solids, sugar, salt, palm oil, thickeners, flavour enhancers (INS 621, INS 627, INS 631), colour (INS 160c)","additive_flags":"INS 621 MSG"},
    {"barcode":"8901058006032","product_name":"Maggi Cup Noodles Masala","brands":"Nestlé","ingredients_text":"Noodles: Refined wheat flour, palm oil, salt, wheat gluten, thickeners; Tastemaker: salt, spices, sugar, flavour enhancers (INS 621, INS 627, INS 631), antioxidant (INS 319)","additive_flags":"INS 621 MSG + INS 319 TBHQ"},
    {"barcode":"8901058001167","product_name":"Maggi Pichkoo Tomato Ketchup","brands":"Nestlé","ingredients_text":"Tomato paste, sugar, water, vinegar, salt, spices, acidity regulator (INS 260), preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901058016222","product_name":"Maggi Rich Tomato Ketchup","brands":"Nestlé","ingredients_text":"Tomato paste, sugar, water, vinegar, salt, spices, acidity regulator (INS 260), preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901058905045","product_name":"Soothers Herbal Throat Drops","brands":"Nestlé","ingredients_text":"Sugar, glucose syrup, herbal extracts, vitamin C, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8901058896381","product_name":"Nescafé Sunrise Coffee 200g","brands":"Nestlé","ingredients_text":"Instant coffee, chicory","additive_flags":"Clean"},
    {"barcode":"8901030976186","product_name":"Horlicks","brands":"HUL","ingredients_text":"Malted cereals (66.7%) [barley, wheat flour, wheat, millet], milk solids (14%), sugar, wheat gluten, iodized salt, minerals, vitamins, emulsifier (INS 471)","additive_flags":"Clean"},
    {"barcode":"8901030825668","product_name":"Horlicks Classic Malt 500g","brands":"HUL","ingredients_text":"Malted cereals (66.7%), milk solids (14%), sugar, wheat gluten, iodized salt, minerals, vitamins, emulsifier (INS 471)","additive_flags":"Clean"},
    {"barcode":"8901030538018","product_name":"Horlicks Classic Malt 750g","brands":"HUL","ingredients_text":"Malted cereals (66.7%), milk solids (14%), sugar, wheat gluten, iodized salt, minerals, vitamins, emulsifier (INS 471)","additive_flags":"Clean"},
    {"barcode":"8909106024502","product_name":"Horlicks Classic Malt 1kg","brands":"HUL","ingredients_text":"Malted cereals (66.7%), milk solids (14%), sugar, wheat gluten, iodized salt, minerals, vitamins, emulsifier (INS 471)","additive_flags":"Clean"},
    {"barcode":"8901030985973","product_name":"Horlicks Chocolate Delight 500g","brands":"HUL","ingredients_text":"Malted cereals, milk solids, sugar, cocoa solids, wheat flour, minerals, vitamins, emulsifier (INS 471), artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8901030825521","product_name":"Horlicks Protein Plus Chocolate","brands":"HUL","ingredients_text":"Milk solids, malted cereals, sugar, cocoa solids, wheat flour, minerals, vitamins, emulsifier (INS 471)","additive_flags":"Clean"},
    {"barcode":"8901030949654","product_name":"Women Horlicks","brands":"HUL","ingredients_text":"Malted cereals, milk solids, sugar, wheat flour, minerals (Iron, Calcium), vitamins, emulsifier (INS 471)","additive_flags":"Clean"},
    {"barcode":"8909106070615","product_name":"Horlicks Super Foods","brands":"HUL","ingredients_text":"Malted cereals, milk solids, sugar, wheat flour, superfoods (chia, flax), minerals, vitamins","additive_flags":"Clean"},
    {"barcode":"8909106018372","product_name":"Boost","brands":"HUL","ingredients_text":"Cereal extract (50%) [barley, wheat, millet], malted barley (21%), sugar, wheat flour, milk solids (6%), minerals, natural colour (INS 150c), vitamins","additive_flags":"INS 150c Caramel"},
    {"barcode":"8901030820946","product_name":"Boost","brands":"HUL","ingredients_text":"Cereal extract (50%), malted barley (21%), sugar, wheat flour, milk solids (6%), minerals, natural colour (INS 150c), vitamins","additive_flags":"INS 150c Caramel"},
    {"barcode":"8901030795909","product_name":"Boost","brands":"HUL","ingredients_text":"Cereal extract (50%), malted barley (21%), sugar, wheat flour, milk solids (6%), minerals, natural colour (INS 150c), vitamins","additive_flags":"INS 150c Caramel"},
    {"barcode":"8901030882609","product_name":"Brooke Bond Red Label 1kg","brands":"HUL","ingredients_text":"100% black tea (CTC dust & fannings blend)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901030918810","product_name":"Brooke Bond Taaza Tea","brands":"HUL","ingredients_text":"100% black tea (CTC blend)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901030083037","product_name":"Red Label Tea","brands":"HUL","ingredients_text":"100% black tea","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901030251504","product_name":"Brooke Bond Taj Mahal Tea","brands":"HUL","ingredients_text":"100% black tea (CTC blend)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901030624247","product_name":"Taj Mahal Tea Bags","brands":"HUL","ingredients_text":"100% black tea","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901030681530","product_name":"Taj Mahal Tea Bags","brands":"HUL","ingredients_text":"100% black tea","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901030681547","product_name":"Taj Mahal Tea Bags","brands":"HUL","ingredients_text":"100% black tea","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901030373930","product_name":"Bru Gold Instant Coffee","brands":"HUL","ingredients_text":"100% instant coffee (freeze-dried)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8909106024199","product_name":"Bru Coffee 3rs Sachet","brands":"HUL","ingredients_text":"Instant coffee, sugar, milk solids, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901030831706","product_name":"Kissan Mixed Fruit Jam","brands":"HUL","ingredients_text":"Sugar, mixed fruit pulp blend (approx. 46%), acidity regulator (INS 330), preservative (INS 211 sodium benzoate), permitted synthetic food colour (INS 122)","additive_flags":"INS 122 + INS 211"},
    {"barcode":"8901030831720","product_name":"Kissan Mixed Fruit Jam 700g","brands":"HUL","ingredients_text":"Sugar, mixed fruit pulp blend (approx. 46%), acidity regulator (INS 330), preservative (INS 211), permitted synthetic food colour (INS 122)","additive_flags":"INS 122 + INS 211"},
    {"barcode":"8901030850400","product_name":"Kissan Mixed Fruit Jam 500g","brands":"HUL","ingredients_text":"Sugar, mixed fruit pulp blend (approx. 46%), acidity regulator (INS 330), preservative (INS 211), permitted synthetic food colour (INS 122)","additive_flags":"INS 122 + INS 211"},
    {"barcode":"8901030931864","product_name":"Kissan Tomato Puree","brands":"HUL","ingredients_text":"Tomato, salt, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8901030717376","product_name":"Kissan Tomato Ketchup","brands":"HUL","ingredients_text":"Tomato paste, sugar, vinegar, salt, spices, acidity regulator (INS 260), preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901030926518","product_name":"Kissan Sweet and Spicy Ketchup","brands":"HUL","ingredients_text":"Tomato paste, sugar, vinegar, salt, spices, acidity regulator, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901030559266","product_name":"Knorr Mexican Tomato Corn Soup","brands":"HUL","ingredients_text":"Tomato powder, corn, sugar, salt, spices, flavour enhancers (INS 621), acidity regulator, colour","additive_flags":"INS 621 MSG"},
    {"barcode":"8901030902352","product_name":"Knorr Tomato Chatpata Soup","brands":"HUL","ingredients_text":"Tomato powder, sugar, salt, spices, flavour enhancers (INS 621), acidity regulator","additive_flags":"INS 621 MSG"},
    {"barcode":"8901030900297","product_name":"Knorr Hong Kong Manchow Soup","brands":"HUL","ingredients_text":"Corn starch, salt, sugar, spices, flavour enhancers (INS 621), acidity regulator","additive_flags":"INS 621 MSG"},
    {"barcode":"8901030900334","product_name":"Knorr Chicken Delite Soup","brands":"HUL","ingredients_text":"Corn starch, salt, sugar, chicken powder, spices, flavour enhancers (INS 621)","additive_flags":"INS 621 MSG"},
    {"barcode":"8901233028361","product_name":"Dairy Milk","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers (INS 322, INS 476), flavours","additive_flags":"Clean"},
    {"barcode":"8901233028392","product_name":"Dairy Milk","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers (INS 322, INS 476), flavours","additive_flags":"Clean"},
    {"barcode":"8901233034300","product_name":"Dairy Milk Silk Bubbly","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers (INS 322, INS 476), flavours","additive_flags":"Clean"},
    {"barcode":"8901233034263","product_name":"Dairy Milk Roast Almond","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, almonds (15%), emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"8901233033563","product_name":"Dairy Milk Silk Minis","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers (INS 322, INS 476), flavours","additive_flags":"Clean"},
    {"barcode":"8901233024622","product_name":"Cadbury Oreo 60g","brands":"Cadbury","ingredients_text":"Refined wheat flour, sugar, refined palm oil, cocoa solids (5%), invert syrup, raising agents, salt, emulsifier (INS 322), antioxidant (INS 319)","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8901233024257","product_name":"Dairy Milk Oreo","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, refined wheat flour, emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"8901233023687","product_name":"Cadbury FUSE","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, glucose syrup, vegetable fats, emulsifiers (INS 442, INS 476), flavours","additive_flags":"Clean"},
    {"barcode":"8901233024042","product_name":"Cadbury Perk","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa solids, edible vegetable oil, emulsifiers, artificial flavours","additive_flags":"Clean"},
    {"barcode":"8901233031712","product_name":"Cadbury Fuse","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, glucose syrup, emulsifiers (INS 442, INS 476), flavours","additive_flags":"Clean"},
    {"barcode":"8901233023748","product_name":"Bournvita Original Refill 500g","brands":"Cadbury","ingredients_text":"Malt extract (wheat/barley), sugar, milk solids, cocoa solids, liquid glucose, minerals, vitamins, emulsifier (INS 322), salt","additive_flags":"High sugar"},
    {"barcode":"8901233022536","product_name":"Bournvita Biscuit","brands":"Cadbury","ingredients_text":"Refined wheat flour, sugar, cocoa solids, edible vegetable oil, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901233025957","product_name":"Marvellous Creations Jelly Popping Candy","brands":"Cadbury","ingredients_text":"Sugar, glucose syrup, milk solids, cocoa butter, cocoa mass, emulsifiers, colours, flavours, popping candy","additive_flags":"Verify colours"},
    {"barcode":"8901233024981","product_name":"Cadbury Zip Chocolate","brands":"Cadbury","ingredients_text":"Sugar, glucose syrup, milk solids, cocoa butter, cocoa mass, emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"8901233022575","product_name":"Cadbury Perk","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa solids, edible vegetable oil, emulsifiers, artificial flavours","additive_flags":"Clean"},
    {"barcode":"8901233022576","product_name":"Cadbury Gems","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa solids, edible vegetable oil, emulsifier (INS 322), colours (INS 102, INS 110, INS 122, INS 133)","additive_flags":"Southampton Six dyes"},
    {"barcode":"8901233030395","product_name":"Cadbury Spready","brands":"Cadbury","ingredients_text":"Sugar, edible vegetable fat, milk solids (16%), cocoa solids, emulsifier (INS 442), added flavour","additive_flags":"Clean"},
    {"barcode":"7622202324925","product_name":"Dairy Milk Bites","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"7622202335488","product_name":"Cadbury Nutties Chocolate 30g","brands":"Cadbury","ingredients_text":"Sugar, peanuts, cocoa butter, milk solids, cocoa mass, emulsifiers","additive_flags":"Clean"},
    {"barcode":"7622210063465","product_name":"Cadbury Dairy Milk","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"8901491003186","product_name":"Quaker Oats","brands":"Quaker","ingredients_text":"Oats (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901499009043","product_name":"Kellogg's Chocos","brands":"Kellogg's","ingredients_text":"Whole wheat flour, sugar, cocoa solids, glucose syrup, salt, vitamins, minerals","additive_flags":"Clean"},
    {"barcode":"8901499009044","product_name":"Kellogg's Corn Flakes","brands":"Kellogg's","ingredients_text":"Corn grits, sugar, malt extract, salt, vitamins, minerals","additive_flags":"Clean"},
    {"barcode":"8901499010469","product_name":"Kellogg's Muesli Nuts Delight","brands":"Kellogg's","ingredients_text":"Whole wheat flakes, oats, nuts, dried fruits, sugar, glucose syrup, salt, vitamins, minerals","additive_flags":"Clean"},
    {"barcode":"8901499027610","product_name":"Choco Millet Muesli","brands":"Kellogg's","ingredients_text":"Whole wheat flakes, oats, millet, cocoa, sugar, glucose syrup, salt, vitamins, minerals","additive_flags":"Clean"},
    {"barcode":"8901491702546","product_name":"Oats Multigrain","brands":"Quaker","ingredients_text":"Oats, multigrain blend, sugar, salt, vitamins, minerals","additive_flags":"Clean"},
    {"barcode":"8901207045370","product_name":"Honey","brands":"Dabur","ingredients_text":"Honey (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901888004451","product_name":"Glucose-D","brands":"Dabur","ingredients_text":"Glucose, vitamin C, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8901207024351","product_name":"Hajmola","brands":"Dabur","ingredients_text":"Spices (black salt, cumin, amchur, red chilli), salt, sugar, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8901207034459","product_name":"Anmol Gold","brands":"Dabur","ingredients_text":"Coconut oil (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901207028311","product_name":"Glucoplus C","brands":"Dabur","ingredients_text":"Dextrose monohydrate, vitamin C, acidity regulator (INS 330), artificial flavour, colours","additive_flags":"Verify colours"},
    {"barcode":"8901207001246","product_name":"Dabur Shilajit","brands":"Dabur","ingredients_text":"Shilajit extract (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901207042089","product_name":"Chawanprash","brands":"Dabur","ingredients_text":"Amla, sugar, honey, ghee, herbs, spices","additive_flags":"Ayurvedic"},
    {"barcode":"8901207048470","product_name":"Dabur Chyawanprash","brands":"Dabur","ingredients_text":"Amla, sugar, honey, ghee, herbs, spices","additive_flags":"Ayurvedic"},
    {"barcode":"8901207025389","product_name":"Honey","brands":"Dabur","ingredients_text":"Honey (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901088017398","product_name":"Saffola Gold","brands":"Marico","ingredients_text":"Rice bran oil, sunflower oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8901088065559","product_name":"Masala Oats Veggie Twist","brands":"Saffola","ingredients_text":"Oats, spices, salt, dehydrated vegetables, flavour enhancers","additive_flags":"Clean"},
    {"barcode":"8901088034593","product_name":"Saffola Active Multi-Source Oil","brands":"Saffola","ingredients_text":"Rice bran oil, sunflower oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8901088002530","product_name":"Saffola Tasty Plus","brands":"Saffola","ingredients_text":"Rice bran oil, corn oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8901777965184","product_name":"Vadilal Classic Malai Kulfi","brands":"Vadilal","ingredients_text":"Toned milk, sugar, milk fat, cardamom, stabilizers, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901777950173","product_name":"Vadilal Ice Cream Belgian Chocolate","brands":"Vadilal","ingredients_text":"Toned milk, sugar, cocoa solids, edible vegetable oil, stabilizers, emulsifiers, colours (INS 124)","additive_flags":"INS 124 Ponceau 4R"},
    {"barcode":"8901777960042","product_name":"Vadilal Bomber","brands":"Vadilal","ingredients_text":"Toned milk, sugar, cocoa solids, edible vegetable oil, stabilizers, emulsifiers, colours","additive_flags":"Verify colours"},
    {"barcode":"8901777596104","product_name":"Vadilal Mysore Pak","brands":"Vadilal","ingredients_text":"Gram flour, sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8901777136065","product_name":"Vadilal Aloo Tikki Kathi Roll","brands":"Vadilal","ingredients_text":"Potato, spices, salt, edible vegetable oil, refined wheat flour","additive_flags":"Clean"},
    {"barcode":"8901777405123","product_name":"Paratha Onion","brands":"Vadilal","ingredients_text":"Whole wheat flour, onion, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8901777461808","product_name":"Aloo Mutter Sandwich","brands":"Vadilal","ingredients_text":"Refined wheat flour, potato, peas, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901777488089","product_name":"Vegetable Manchurian","brands":"Vadilal","ingredients_text":"Mixed vegetables, refined wheat flour, edible vegetable oil, spices, salt, soy sauce","additive_flags":"Clean"},
    {"barcode":"8901777620977","product_name":"Classic Aloo Mutter Jumbo Puff","brands":"Vadilal","ingredients_text":"Refined wheat flour, potato, peas, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901777404126","product_name":"Paratha","brands":"Vadilal","ingredients_text":"Whole wheat flour, water, edible vegetable oil, salt","additive_flags":"Clean"},
    {"barcode":"8901777401125","product_name":"Paratha Aloo","brands":"Vadilal","ingredients_text":"Whole wheat flour, potato, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901777418642","product_name":"Methi Thepla","brands":"Vadilal","ingredients_text":"Whole wheat flour, fenugreek leaves, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901777489086","product_name":"Paneer Chilly","brands":"Vadilal","ingredients_text":"Paneer, capsicum, onion, spices, salt, edible vegetable oil, soy sauce","additive_flags":"Clean"},
    {"barcode":"8901777486085","product_name":"Schezwan Fried Rice","brands":"Vadilal","ingredients_text":"Rice, vegetables, schezwan sauce, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901777470787","product_name":"Dabeli","brands":"Vadilal","ingredients_text":"Refined wheat flour, potato, spices, salt, sugar, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901777132067","product_name":"Kathi Roll","brands":"Vadilal","ingredients_text":"Refined wheat flour, vegetables, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901777501146","product_name":"Malai Paneer","brands":"Vadilal","ingredients_text":"Paneer, cream, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8906015340174","product_name":"Everest Garam Masala","brands":"Everest","ingredients_text":"Coriander, cumin, black pepper, cloves, cinnamon, cardamom, bay leaf, nutmeg, mace","additive_flags":"Clean spice blend"},
    {"barcode":"8901786165001","product_name":"Everest Chicken Masala","brands":"Everest","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom, garlic, ginger","additive_flags":"Clean spice blend"},
    {"barcode":"8901786270507","product_name":"Everest Dry Mango Powder","brands":"Everest","ingredients_text":"Dried mango powder (amchur) (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902167000782","product_name":"MDH Garam Masala","brands":"MDH","ingredients_text":"Coriander, cumin, black pepper, cloves, cinnamon, cardamom, bay leaf","additive_flags":"Clean spice blend"},
    {"barcode":"8902167000751","product_name":"MDH Kitchen King","brands":"MDH","ingredients_text":"Coriander, turmeric, red chilli, cumin, black pepper, cloves, cinnamon, cardamom","additive_flags":"Clean spice blend"},
    {"barcode":"8902167000829","product_name":"MDH Meat Ka Masala","brands":"MDH","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom, garlic, ginger, fennel","additive_flags":"Clean spice blend"},
    {"barcode":"8901192101013","product_name":"Catch Black Pepper Powder","brands":"Catch","ingredients_text":"Black pepper powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901192105011","product_name":"Catch Amchur Powder","brands":"Catch","ingredients_text":"Dried mango powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901192221018","product_name":"Catch Chhole Masala","brands":"Catch","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom, amchur, ginger","additive_flags":"Clean spice blend"},
    {"barcode":"8901192215017","product_name":"Catch Sabzi Masala","brands":"Catch","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom","additive_flags":"Clean spice blend"},
    {"barcode":"8901192217110","product_name":"Catch Jaljeera","brands":"Catch","ingredients_text":"Cumin, black salt, amchur, red chilli, black pepper, mint, ginger","additive_flags":"Clean spice blend"},
    {"barcode":"8901440023067","product_name":"Eastern Chilli Powder","brands":"Eastern","ingredients_text":"Red chilli powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901440031017","product_name":"Eastern Mango Pickle","brands":"Eastern","ingredients_text":"Raw mango, salt, spices, edible vegetable oil, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8901662031055","product_name":"Suhana Veg Kolhapuri","brands":"Suhana","ingredients_text":"Spices, salt, sugar, edible vegetable oil","additive_flags":"Clean spice blend"},
    {"barcode":"8901662033509","product_name":"Suhana Super Garam Masala","brands":"Suhana","ingredients_text":"Coriander, cumin, black pepper, cloves, cinnamon, cardamom, bay leaf, nutmeg, mace","additive_flags":"Clean spice blend"},
    {"barcode":"8906002081585","product_name":"Sakthi Masala Chicken 500g","brands":"Sakthi","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom, garlic, ginger, fennel","additive_flags":"Clean spice blend"},
    {"barcode":"8904209303387","product_name":"Aachi Garlic Tomato Thokku","brands":"Aachi","ingredients_text":"Tomato, garlic, salt, spices, edible vegetable oil, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8901042955100","product_name":"Mango Thokku","brands":"MTR","ingredients_text":"Raw mango, salt, red chilli, edible vegetable oil, mustard, fenugreek","additive_flags":"Clean"},
    {"barcode":"8901042957074","product_name":"Rava Idli","brands":"MTR","ingredients_text":"Semolina, urad dal flour, salt, spices, raising agents","additive_flags":"Clean"},
    {"barcode":"8901042970066","product_name":"Roasted Vermicelli","brands":"MTR","ingredients_text":"Durum wheat semolina (roasted)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901042955308","product_name":"Upma","brands":"MTR","ingredients_text":"Semolina, salt, spices, dehydrated vegetables","additive_flags":"Clean"},
    {"barcode":"8901155101210","product_name":"Gulab Jamun","brands":"Gits","ingredients_text":"Milk solids, sugar, edible vegetable oil, cardamom, rose water","additive_flags":"Clean"},
    {"barcode":"8901155109216","product_name":"Rava Idli","brands":"Gits","ingredients_text":"Semolina, urad dal flour, salt, spices, raising agents","additive_flags":"Clean"},
    {"barcode":"8901155116214","product_name":"Gits Upma Mix 200g","brands":"Gits","ingredients_text":"Semolina, salt, spices, dehydrated vegetables","additive_flags":"Clean"},
    {"barcode":"8901155426313","product_name":"Matar Paneer","brands":"Gits","ingredients_text":"Paneer, green peas, tomato, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901155301443","product_name":"Gits Gulabi Jamun","brands":"Gits","ingredients_text":"Milk solids, sugar, edible vegetable oil, cardamom, rose water","additive_flags":"Clean"},
    {"barcode":"8906008350500","product_name":"Oats","brands":"Manna","ingredients_text":"Oats (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906059160110","product_name":"Regency Apricots Dried","brands":"Regency","ingredients_text":"Dried apricots (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901440217909","product_name":"Crushed Chilli","brands":"Various","ingredients_text":"Crushed red chilli (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904358321744","product_name":"Ame Mushrooms Pieces and Stem","brands":"Ame","ingredients_text":"Mushrooms (pieces and stem), water, salt","additive_flags":"Clean"},
    {"barcode":"8906167241398","product_name":"Black Raisins","brands":"Whole Farm","ingredients_text":"Black raisins (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906006720145","product_name":"Lion Desert King Dates","brands":"Lion","ingredients_text":"Dates (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901030985577","product_name":"Tea","brands":"3 Roses","ingredients_text":"100% black tea (CTC blend)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904132976320","product_name":"Mango Mood","brands":"Various","ingredients_text":"Mango flavour, sugar, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8904004404418","product_name":"Haldiram's Boondi","brands":"Haldiram's","ingredients_text":"Gram flour, edible vegetable oil, iodized salt, spices, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8901058022087","product_name":"Munch","brands":"Nestlé","ingredients_text":"Sugar, refined wheat flour, hydrogenated vegetable oil (palm), milk solids, cocoa solids, emulsifier (INS 322), salt, raising agent (INS 500(ii)), artificial vanilla flavour","additive_flags":"Hydrogenated oil"},
    {"barcode":"8905507047720","product_name":"Biscuit","brands":"Various","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901414001039","product_name":"Synthetic Rose Syrup","brands":"Bilcano","ingredients_text":"Sugar, water, rose flavour, acidity regulator, colour (INS 122)","additive_flags":"INS 122 colour"},
    {"barcode":"8906069411202","product_name":"Dried Kiwi","brands":"Jewel Farmer","ingredients_text":"Dried kiwi (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901030023804","product_name":"Pepsodent","brands":"HUL","ingredients_text":"NON-FOOD — Toothpaste","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8906088058389","product_name":"Bispari","brands":"Bispari","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901393017915","product_name":"Mentos","brands":"Perfetti","ingredients_text":"Sugar, glucose syrup, edible vegetable oil, artificial flavours, colours","additive_flags":"Verify colours"},
    {"barcode":"8906163832453","product_name":"Chia Seeds","brands":"Various","ingredients_text":"Chia seeds (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906158750113","product_name":"Orange Frenzy","brands":"Hitkary","ingredients_text":"Sugar, glucose syrup, orange flavour, acidity regulator, colours","additive_flags":"Verify colours"},
    {"barcode":"8906028790287","product_name":"Funtop Jam","brands":"Various","ingredients_text":"Sugar, fruit pulp, acidity regulator (INS 330), preservative (INS 211), colours","additive_flags":"INS 211 preservative"},
    {"barcode":"8902901224726","product_name":"Toor Dal 500g","brands":"Good Life","ingredients_text":"Toor dal (pigeon pea)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906009820323","product_name":"Silver Coin Suji","brands":"Silver Coin","ingredients_text":"Semolina (suji/rava) from wheat","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906167310643","product_name":"Arhar Dal 1kg","brands":"Various","ingredients_text":"Arhar/Toor dal (pigeon pea)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902901224733","product_name":"Toor Dal 1kg","brands":"Good Life","ingredients_text":"Toor dal (pigeon pea)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904132975774","product_name":"Campa Power Up","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulators, caffeine, taurine, colours, flavours","additive_flags":"Caffeine + Taurine"},
    {"barcode":"8906108895178","product_name":"Desi Popz","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8904132975552","product_name":"Campa Soda","brands":"Campa","ingredients_text":"Carbonated water, salt, acidity regulator (INS 330)","additive_flags":"Clean"},
    {"barcode":"8904132949737","product_name":"Campa O","brands":"Campa","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8906134671623","product_name":"Ripe Banana Chips","brands":"Ajmi","ingredients_text":"Banana, edible vegetable oil, iodized salt","additive_flags":"Clean"},
    {"barcode":"8906134671357","product_name":"Tapioca Chips","brands":"Ajmi","ingredients_text":"Tapioca, edible vegetable oil, iodized salt","additive_flags":"Clean"},
    {"barcode":"8906134671340","product_name":"Banana Chips","brands":"Ajmi","ingredients_text":"Banana, edible vegetable oil, iodized salt","additive_flags":"Clean"},
    {"barcode":"8906134671616","product_name":"Tapioca Sticks Spicy","brands":"Ajmi","ingredients_text":"Tapioca, edible vegetable oil, spices, iodized salt","additive_flags":"Clean"},
    {"barcode":"8906069611206","product_name":"Anand Bikaneri Bhujia","brands":"Anand","ingredients_text":"Gram flour, edible vegetable oil, iodized salt, spices (red chilli, cumin, black pepper), colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8906069611725","product_name":"Anand Fulwadi","brands":"Anand","ingredients_text":"Gram flour, edible vegetable oil, iodized salt, spices","additive_flags":"Clean"},
    {"barcode":"8906069611763","product_name":"Kachori","brands":"Anand","ingredients_text":"Refined wheat flour, gram flour, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8906069612128","product_name":"Anand Mini Samosa","brands":"Anand","ingredients_text":"Refined wheat flour, potato, peas, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8906006525504","product_name":"Top Start","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901063371026","product_name":"Marie Gold","brands":"Britannia","ingredients_text":"Refined wheat flour (73%), sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers (INS 471, INS 322)","additive_flags":"Clean"},
    {"barcode":"8901058866216","product_name":"Coffee Mocha","brands":"Nestlé","ingredients_text":"Instant coffee, sugar, milk solids, cocoa solids, emulsifier, flavours","additive_flags":"Clean"},
    {"barcode":"8901552007689","product_name":"Kantola","brands":"Ashoka","ingredients_text":"Refined wheat flour, potato, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8904064628007","product_name":"Citron Pickle","brands":"Various","ingredients_text":"Citron, salt, spices, edible vegetable oil, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8906073790539","product_name":"Frunchys","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901030820946","product_name":"Boost","brands":"HUL","ingredients_text":"Cereal extract (50%), malted barley (21%), sugar, wheat flour, milk solids (6%), minerals, natural colour (INS 150c), vitamins","additive_flags":"INS 150c Caramel"},
    {"barcode":"8904132911000","product_name":"Kaffe Instant","brands":"Various","ingredients_text":"Instant coffee","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906131680512","product_name":"Date Powder","brands":"Slurrp Farm","ingredients_text":"Date powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908008818721","product_name":"Gingelly Oil","brands":"Various","ingredients_text":"Sesame oil (gingelly) (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906015741452","product_name":"Orange Jam","brands":"Various","ingredients_text":"Sugar, orange pulp, acidity regulator (INS 330), preservative (INS 211), colour (INS 110)","additive_flags":"INS 211 + INS 110"},
    {"barcode":"8904406393297","product_name":"Manha Soan Papdi","brands":"Manha","ingredients_text":"Sugar, gram flour, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8909106055469","product_name":"Surf Excel Top Load Liquid","brands":"HUL","ingredients_text":"NON-FOOD — Detergent","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901396602644","product_name":"Dot","brands":"Various","ingredients_text":"NON-FOOD — Verify","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8907093010287","product_name":"Buffalo Meat Fry","brands":"Tasty Nibbles","ingredients_text":"Buffalo meat, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8904132973480","product_name":"Good Life Roasted Flax Seed","brands":"Good Life","ingredients_text":"Roasted flax seeds (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901148251830","product_name":"Zedex","brands":"Various","ingredients_text":"NON-FOOD — Medicine","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8908000863460","product_name":"Oleev Active","brands":"Oleev","ingredients_text":"Rice bran oil, olive oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8901531700327","product_name":"Suthol","brands":"Various","ingredients_text":"NON-FOOD — Cleaning product","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901207050374","product_name":"Real Frutors","brands":"Real","ingredients_text":"Water, fruit juice concentrate, sugar, acidity regulator, antioxidant","additive_flags":"Clean"},
    {"barcode":"8901512102805","product_name":"Sundrop Super Lite Advanced","brands":"Sundrop","ingredients_text":"Refined sunflower oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8906009220598","product_name":"Nutrifud Rich Milk Milk Cake","brands":"Nutrifud","ingredients_text":"Milk solids, sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906010366803","product_name":"Town Bus Butter Murukku","brands":"Town Bus","ingredients_text":"Rice flour, gram flour, butter, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8906035141065","product_name":"Chipo Orange Halwa","brands":"Chipo","ingredients_text":"Sugar, semolina, orange flavour, ghee, cardamom, colours","additive_flags":"Verify colours"},
    {"barcode":"8906117004042","product_name":"Golden Sella","brands":"Various","ingredients_text":"Golden sella rice","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901764031182","product_name":"Sprite","brands":"Coca-Cola","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(i)), natural lemon-lime flavouring, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901192208019","product_name":"Kitchen King Catch","brands":"Catch","ingredients_text":"Coriander, turmeric, red chilli, cumin, black pepper, cloves, cinnamon, cardamom","additive_flags":"Clean spice blend"},
    {"barcode":"8901192208118","product_name":"Kitchen King","brands":"Catch","ingredients_text":"Coriander, turmeric, red chilli, cumin, black pepper, cloves, cinnamon, cardamom","additive_flags":"Clean spice blend"},
    {"barcode":"8901719656828","product_name":"FAB!","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, fruit jam, invert syrup, raising agents, emulsifiers, colours","additive_flags":"Clean"},
    {"barcode":"8901153001529","product_name":"Soan Papdi","brands":"Various","ingredients_text":"Sugar, gram flour, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906032016977","product_name":"Soya Chunks","brands":"Nutrela","ingredients_text":"Defatted soya flour","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906026995028","product_name":"Brimune Aloe Vera Juice 500ML","brands":"Various","ingredients_text":"Aloe vera juice, preservative","additive_flags":"Clean"},
    {"barcode":"8901725019419","product_name":"Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725000646","product_name":"Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8902901222357","product_name":"Phool Makhana","brands":"Good Life","ingredients_text":"Makhana (fox nuts)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901155301443","product_name":"Gits Gulabi Jamun","brands":"Gits","ingredients_text":"Milk solids, sugar, edible vegetable oil, cardamom, rose water","additive_flags":"Clean"},
    {"barcode":"8909081003905","product_name":"Rich Chocolate Cookies","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, cocoa solids, edible vegetable oil, invert syrup, raising agents, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8906001024798","product_name":"Four Cheese","brands":"Go","ingredients_text":"Milk solids, salt, emulsifying salts, preservative (INS 200), cheese blend","additive_flags":"INS 200 preservative"},
    {"barcode":"8903605017706","product_name":"Soy Sauce","brands":"Various","ingredients_text":"Water, soybean extract, salt, sugar, vinegar, acidity regulator, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8906010504021","product_name":"Balaji Wafers","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8906010504007","product_name":"Balaji Wafers","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8901719656613","product_name":"Parle Hide & Seek Fab Orange","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, cocoa solids, invert syrup, milk solids, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8906024450512","product_name":"Green Tea Natural","brands":"Various","ingredients_text":"Green tea (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906024451335","product_name":"Green Tea Lemon and Honey","brands":"Various","ingredients_text":"Green tea, lemon flavour, honey","additive_flags":"Clean"},
    {"barcode":"8901030456381","product_name":"Taaza Tea","brands":"Brooke Bond","ingredients_text":"100% black tea (CTC blend)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901719124402","product_name":"Magix Orange","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, invert syrup, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8901719122040","product_name":"Coconut","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, coconut, edible vegetable oil, invert syrup, raising agents, emulsifier, artificial coconut flavour","additive_flags":"Clean"},
    {"barcode":"8901719124396","product_name":"Magix Elaichi","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cardamom flavour, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8904006313367","product_name":"Oura","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901044400745","product_name":"Strawberry Fruit Crush 1L","brands":"Various","ingredients_text":"Strawberry pulp, sugar, acidity regulator, preservative, colour","additive_flags":"INS 211 preservative"},
    {"barcode":"8906052860147","product_name":"Chilly Garlic Cashews","brands":"Zantye's","ingredients_text":"Cashew nuts, edible vegetable oil, chilli, garlic, salt","additive_flags":"Clean"},
    {"barcode":"8908013194308","product_name":"Cuban Watermelon Mojito","brands":"Borécha","ingredients_text":"Water, sugar, watermelon juice, mint, lime, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8908006931965","product_name":"Riz Étuve Lutik","brands":"Various","ingredients_text":"Parboiled rice","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906143892330","product_name":"Cranberry Raisin Protein Bar","brands":"The Whole Truth","ingredients_text":"Cranberries, raisins, whey protein, dates, nuts, emulsifier","additive_flags":"Clean"},
    {"barcode":"8900019102523","product_name":"Jaggery Cubes 500g","brands":"Various","ingredients_text":"Jaggery (gur)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908000861619","product_name":"Gopal Bhavnagari Gathiya","brands":"Gopal","ingredients_text":"Gram flour, edible vegetable oil, iodized salt, spices","additive_flags":"Clean"},
    {"barcode":"8908009247148","product_name":"Sanjivani Tea","brands":"Sanjivani","ingredients_text":"Black tea, herbs, spices","additive_flags":"Clean"},
    {"barcode":"8906097403194","product_name":"Zoff Onion Powder","brands":"Zoff","ingredients_text":"Onion powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901192106124","product_name":"Catch Red Chilli Powder","brands":"Catch","ingredients_text":"Red chilli powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908016793966","product_name":"White Vinegar","brands":"Various","ingredients_text":"White vinegar (acetic acid, water)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901063166288","product_name":"Britannia Tiger Kreemz 72g","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, invert syrup, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8901548310106","product_name":"D Lite Vanilla","brands":"Various","ingredients_text":"Refined wheat flour, sugar, eggs, edible vegetable oil, vanilla flavour, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901552023610","product_name":"Mini Tandoori Paneer Samosa","brands":"Ashoka","ingredients_text":"Refined wheat flour, paneer, tandoori spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901030795909","product_name":"Boost","brands":"HUL","ingredients_text":"Cereal extract (50%), malted barley (21%), sugar, wheat flour, milk solids (6%), minerals, natural colour (INS 150c), vitamins","additive_flags":"INS 150c Caramel"},
    {"barcode":"8908016538185","product_name":"POP","brands":"Archi","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8908004804278","product_name":"Catch Clear","brands":"Catch","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8906005666536","product_name":"Madras Filter Coffee","brands":"Various","ingredients_text":"Coffee blend (filter coffee), chicory","additive_flags":"Clean"},
    {"barcode":"8904315300782","product_name":"Desi Ghee","brands":"Shri Vallabh","ingredients_text":"Milk solids (pure cow ghee)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904188605847","product_name":"Black Sesame Seeds","brands":"Various","ingredients_text":"Black sesame seeds (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906009820415","product_name":"Daliya","brands":"Silver Coin","ingredients_text":"Broken wheat (daliya)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908016763150","product_name":"Aata","brands":"Energy Max","ingredients_text":"100% whole wheat flour","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901560120219","product_name":"Instant Idli Mix","brands":"Nilon's","ingredients_text":"Rice flour, urad dal flour, salt, raising agents","additive_flags":"Clean"},
    {"barcode":"8906080603914","product_name":"Swing Pomegranate","brands":"Paper Boat","ingredients_text":"Water, pomegranate pulp, sugar, acidity regulators","additive_flags":"Clean"},
    {"barcode":"8901777626801","product_name":"Overload Veggie Pizza","brands":"Vadilal","ingredients_text":"Refined wheat flour, vegetables, cheese, tomato sauce, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8901058892635","product_name":"Maggi Export","brands":"Nestlé","ingredients_text":"Noodles: Refined wheat flour, palm oil, salt, thickeners; Tastemaker: salt, spices, flavour enhancers (INS 621), antioxidant (INS 319)","additive_flags":"INS 621 + INS 319"},
    {"barcode":"8908013252299","product_name":"Multi Grain Mixture","brands":"Various","ingredients_text":"Multigrain blend, edible vegetable oil, spices, salt, sugar","additive_flags":"Clean"},
    {"barcode":"8906082570085","product_name":"Cornitos Pop N Green Peas","brands":"Cornitos","ingredients_text":"Green peas, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8906006720350","product_name":"Australian Oats","brands":"Lion","ingredients_text":"Oats (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904109405501","product_name":"Elaichi Soan Papdi","brands":"Various","ingredients_text":"Sugar, gram flour, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8908002544107","product_name":"Beer","brands":"Various","ingredients_text":"Alcoholic beverage (beer)","additive_flags":"ALCOHOL — SEPARATE"},
    {"barcode":"8901071732826","product_name":"Sofit Soya Vanilla Flavour Drink 180ml","brands":"Sofit","ingredients_text":"Soya milk, sugar, vanilla flavour, stabilizers, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901063094185","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901063094147","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901063092402","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901063098657","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8904022990023","product_name":"Sandwich Plus","brands":"Various","ingredients_text":"Refined wheat flour, water, sugar, yeast, salt, edible vegetable oil, preservative (INS 282)","additive_flags":"INS 282 preservative"},
    {"barcode":"8904064672215","product_name":"Graines de Pilon (Moringa)","brands":"Various","ingredients_text":"Moringa seeds (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901777041666","product_name":"Frozen Bean","brands":"Vadilal","ingredients_text":"Green beans (frozen)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901848000752","product_name":"Rasana Fruit Plus","brands":"Rasna","ingredients_text":"Sugar, acidity regulators (INS 296, INS 330), salt, anticaking agent (INS 551), vitamin C, permitted colours, artificial flavours","additive_flags":"Verify colours"},
    {"barcode":"8901648001775","product_name":"Lassi","brands":"Mother Dairy","ingredients_text":"Toned milk, sugar, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8901192215116","product_name":"Catch Sabzi Masala","brands":"Catch","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom","additive_flags":"Clean spice blend"},
    {"barcode":"8904098970240","product_name":"Joyo Clean Max Cotton Mop","brands":"Joyo","ingredients_text":"NON-FOOD — Cleaning product","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8908012945703","product_name":"Red Lentil Crisps","brands":"Pink Harvest Farms","ingredients_text":"Red lentil flour, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8901662029151","product_name":"Paneer Chilli Mix","brands":"Suhana","ingredients_text":"Paneer, spices, salt, sugar, edible vegetable oil, chilli","additive_flags":"Clean"},
    {"barcode":"8904250303831","product_name":"CAMFLORA Champa and Camphor","brands":"Shubh Kart","ingredients_text":"NON-FOOD — Puja/religious item","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8906006170087","product_name":"Khatta Meetha","brands":"O'yes","ingredients_text":"Rice flakes, edible vegetable oil, sugar, peanuts, sago, salt, spices, raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904004416602","product_name":"Classic Lassi","brands":"Haldiram","ingredients_text":"Toned milk, sugar, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8904150503898","product_name":"Gold Atta","brands":"Pillsbury","ingredients_text":"100% whole wheat flour","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908000863408","product_name":"Oleev Active Oil","brands":"Oleev","ingredients_text":"Rice bran oil, olive oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8902433003790","product_name":"Galaxy Milk Chocolate 110g","brands":"Galaxy","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"8903023265628","product_name":"Kitchen's Promise","brands":"Kitchen's Promise","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8904132963627","product_name":"Good Life Teekhi Chilli Powder","brands":"Good Life","ingredients_text":"Red chilli powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904132963610","product_name":"UB06 Hygienic","brands":"Various","ingredients_text":"NON-FOOD — Verify","additive_flags":"NON-FOOD — PURGE"}
]

elevated_count = 0
added_count = 0
purged_count = 0

for item in batch_15_rows:
    barcode = str(item["barcode"]).strip()
    pname = item["product_name"].strip()
    brand = item["brands"].strip()
    ing = item["ingredients_text"].strip()
    flags = item.get("additive_flags", "")
    
    # Check if non-food
    if "NON-FOOD" in ing.upper() or "NON-FOOD" in flags.upper() or "PURGE" in flags.upper():
        df_all = df_all[df_all['barcode'] != barcode]
        df_confirmed = df_confirmed[df_confirmed['barcode'] != barcode]
        df_needs_ver = df_needs_ver[df_needs_ver['barcode'] != barcode]
        purged_count += 1
        continue
        
    if not (barcode.startswith('890') or bool(re.match(r'^\d+$', barcode))):
        continue

    # Update or add in master DB
    idx_all = df_all[df_all['barcode'] == barcode].index
    if len(idx_all) > 0:
        df_all.loc[idx_all, 'product_name'] = pname
        df_all.loc[idx_all, 'brands'] = brand
        df_all.loc[idx_all, 'ingredients_text'] = ing
    else:
        new_row = {
            'barcode': barcode,
            'product_name': pname,
            'brands': brand,
            'ingredients_text': ing,
            'sold_in_india_status': 'CONFIRMED_INDIA_890',
            'ingredient_confidence': 'HIGH',
            'status': 'KEEP',
            'data_source': 'Brand Official Publication',
            'source_license': 'User-submitted',
            'collection_method': 'API/CSV Import'
        }
        df_all = pd.concat([df_all, pd.DataFrame([new_row])], ignore_index=True)

    # Check if in needs_ver, promote to confirmed
    idx_nv = df_needs_ver[df_needs_ver['barcode'] == barcode].index
    if len(idx_nv) > 0:
        df_needs_ver = df_needs_ver[df_needs_ver['barcode'] != barcode]
        elevated_count += 1

    # Upsert in confirmed
    idx_c = df_confirmed[df_confirmed['barcode'] == barcode].index
    if len(idx_c) > 0:
        df_confirmed.loc[idx_c, 'product_name'] = pname
        df_confirmed.loc[idx_c, 'brands'] = brand
        df_confirmed.loc[idx_c, 'ingredients_text'] = ing
        df_confirmed.loc[idx_c, 'sold_in_india_status'] = 'CONFIRMED_INDIA_890'
        df_confirmed.loc[idx_c, 'ingredient_confidence'] = 'HIGH'
        df_confirmed.loc[idx_c, 'status'] = 'KEEP'
    else:
        conf_row = {
            'barcode': barcode,
            'product_name': pname,
            'brands': brand,
            'ingredients_text': ing,
            'sold_in_india_status': 'CONFIRMED_INDIA_890',
            'ingredient_confidence': 'HIGH',
            'status': 'KEEP',
            'data_source': 'Brand Official Publication',
            'source_license': 'User-submitted',
            'collection_method': 'API/CSV Import'
        }
        df_confirmed = pd.concat([df_confirmed, pd.DataFrame([conf_row])], ignore_index=True)
        added_count += 1

# Save updated files
df_all.to_csv(all_supabase_csv, index=False)
df_confirmed.to_csv(confirmed_csv, index=False)
df_needs_ver.to_csv(needs_ver_csv, index=False)

print(f"Batch 15 Processing Summary:")
print(f"  Elevated from Needs Verification to Confirmed: {elevated_count}")
print(f"  Newly added to Confirmed: {added_count}")
print(f"  Purged Non-Food Barcodes: {purged_count}")
print(f"  Final Master CSV Count: {len(df_all)}")
print(f"  Final Confirmed CSV Count: {len(df_confirmed)}")
print(f"  Final Needs Verification CSV Count: {len(df_needs_ver)}")
