import os
import sys
import pandas as pd

sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = r"c:\Users\thout\Downloads\check it"

all_supabase_csv = os.path.join(BASE_DIR, "all_supabase_products.csv")
confirmed_csv = os.path.join(BASE_DIR, "india_products_confirmed.csv")
needs_ver_csv = os.path.join(BASE_DIR, "india_products_needs_verification.csv")

print("=== EXECUTING BATCH 36 INGREDIENTS INTEGRATION & PURGE ===")

df_all = pd.read_csv(all_supabase_csv, dtype=str)
df_confirmed = pd.read_csv(confirmed_csv, dtype=str) if os.path.exists(confirmed_csv) else pd.DataFrame()
df_needs_ver = pd.read_csv(needs_ver_csv, dtype=str) if os.path.exists(needs_ver_csv) else pd.DataFrame()

for df in [df_all, df_confirmed, df_needs_ver]:
    if not df.empty and 'barcode' in df.columns:
        df['barcode'] = df['barcode'].astype(str).str.strip()

batch_36_rows = [
    {"barcode":"7613033639524","product_name":"P'tit Souper Macaroni Tomates Courgettes","brands":"Nestlé/Bébé Nestlé","ingredients_text":"Légumes 66% (purée de tomates 40%, carottes 12%, courgettes 10%, oignons), lait écrémé reconstitué 14.5%, pâtes cuites 12% (eau, semoule de blé dur, blanc d'oeuf), amidon, gruyère fondu (gruyère (lait), eau, beurre, épaississant: gomme de xanthane), lait écrémé en poudre 1.15%, huiles végétales (colza, tournesol), sel marin, basilic","additive_flags":"Clean baby food"},
    {"barcode":"8410199026729","product_name":"Doritos Rib Session","brands":"Doritos","ingredients_text":"Maíz, aceite de colza, aroma a barbacoa rib'session (dextrosa, tomate en polvo, pimentón en polvo, proteína vegetal hidrolizada, azúcar, cebolla en polvo, correctores de acidez (acetatos de sodio, ácido cítrico, ácido málico), aromas, potenciador del sabor (glutamato monosódico), cloruro potásico, ajo en polvo, sal, melaza en polvo, colorante (extracto de pimentón), maltodextrina ahumada, aceite de girasol ahumado), antioxidantes (extractos de romero, ácido ascórbico, extracto rico en tocoferoles, ácido cítrico)","additive_flags":"INS 621 MSG"},
    {"barcode":"28400090896","product_name":"Nacho Cheese","brands":"Doritos","ingredients_text":"Corn, vegetable oil (corn, canola, soybean, and/or sunflower oil), corn maltodextrin, and less than 2% of cheddar cheese (milk, cheese cultures, salt, enzymes), salt, whey, monosodium glutamate, buttermilk, romano cheese (milk, cheese cultures, salt, enzymes), whey protein concentrate, onion powder, potassium salt, corn flour, natural & artificial flavors, dextrose, tomato powder, lactose, spices, artificial color (yellow 6, yellow 5, red 40), lactic acid, citric acid, sugar, garlic powder, skim milk, red and green bell peppers, disodium inosinate, and disodium guanylate","additive_flags":"INS 621 MSG + Artificial colours"},
    {"barcode":"2000000088174","product_name":"Snickers HI Protein","brands":"Snickers","ingredients_text":"Protéines de lait, 30.8% sirop de fructose et glucose, 20% chocolat au lait (sucre, beurre de cacao, lait entier en poudre, pâte de cacao, émulsifiant: lécithine de soja, arômes), 6.9% sirop de sorbitol, protéines de lait hydrolysées, huile de soja, maltodextrine, arômes, sel, émulsifiant: lécithine de soja, vitamines (acide ascorbique, nicotinamide, vitamine e, pantothénate de calcium, chlorhydrate de pyridoxine, riboflavine, chlorhydrate de thiamine, biotine, cyanocobalamine), huile végétale, colorant: bêta-carotène","additive_flags":"Clean"},
    {"barcode":"28400334402","product_name":"Sabritas Doritos Tortilla Chips","brands":"Frito-Lay/Doritos","ingredients_text":"Corn, vegetable oil (sunflower, corn, and/or canola oil), salt, maltodextrin (made from corn), sugar, mono sodium glutamate, garlic powder, spices, corn syrup solids, onion powder, brown sugar, citric acid, sodium diacetate, natural flavor, orange juice","additive_flags":"INS 621 MSG"},
    {"barcode":"7613034041197","product_name":"Stracciatella Chocolat Crème Glacée","brands":"Nestlé","ingredients_text":"Lait écrémé, crème 24%, sucre, sirop de glucose, petit-lait en poudre, lait écrémé en poudre, chocolat au lait 1.5% [sucre, beurre de cacao, lait entier en poudre, pâte de cacao, émulsifiant (lécithine de tournesol), extrait de vanille], cacao maigre en poudre 1%, noisettes, jaune d'oeuf, beurre de cacao, pâte de cacao, protéine de lait, concentrés de fruits, légumes et plantes (pomme, carotte, hibiscus, betterave rouge), stabilisants (farine de graines de caroube, gomme guar), noisettes partiellement dégraissées, arôme naturel, mélasse, émulsifiant (lécithine de tournesol), extrait de vanille","additive_flags":"Clean"},
    {"barcode":"78000023756","product_name":"Fruit Punch Flavored Energy Drink Lemon","brands":"Venom/Pepsi","ingredients_text":"Carbonated water, corn syrup, glucose, citric acid, maltodextrin, taurine, sodium citrate, l-carnitine, inositol, caffeine, sodium benzoate (preservative), potassium sorbate (preservative), niacinamide (vitamin b3), natural flavors, sucralose, red 40, ginseng extract, pyridoxine hydrochloride (vitamin b6), guarana extract, riboflavin (vitamin b2), cyanocobalamin (vitamin b12)","additive_flags":"INS 211 + INS 202 preservatives + Red 40"},
    {"barcode":"7613287409430","product_name":"Yogolino Mango","brands":"Nestlé","ingredients_text":"Leche fermentada (76.3%) [leche, agua, fermentos lácteos (contienen leche), espesante (pectina)], puré de mango (20%), almidón de maíz, aroma natural","additive_flags":"Clean"},
    {"barcode":"3760010610169","product_name":"Les Petites Sardines à l'Huile d'Olives et au Citron","brands":"La Marseillaise","ingredients_text":"Sardines (sprats: sprattus sprattus) 60%, huile d'olive 31%, tranche de citron 7%, sel 1.5%, arôme de citron 0.08%. Source d'omega-3. Zone de pêche: FAO 27.11.1d","additive_flags":"Clean"},
    {"barcode":"5000159364850","product_name":"Mars Minis Pouch","brands":"Mars","ingredients_text":"Sugar, glucose syrup, cocoa butter, full cream milk powder, cocoa mass, sunflower oil, butter fat (from milk), lactose, whey powder (from milk), barley malt extract, salt, emulsifier (soya lecithin), egg white powder, palm fat, milk protein, natural vanilla extract, (may contain: peanut, hazelnut). Milk chocolate contains milk solids 14% minimum","additive_flags":"Clean"},
    {"barcode":"8852756925043","product_name":"Granola Boost","brands":"Kellogg's","ingredients_text":"Wholegrain oat, sugar, wheat protein, wheat flour, rice semolina, palm oil, goji berry, dried blueberry, vitamins, minerals (e, d, b3, folic acid, b2, b6, b1, calcium carbonate, ferric pyrophosphate), glucose syrup, honey, malted barley, salt, natural vanilla flavour, antioxidant (mixed tocopherol)","additive_flags":"Clean"},
    {"barcode":"54490123","product_name":"Coca-Cola","brands":"Coca-Cola","ingredients_text":"Water, sugar, carbonic acid, dye e150d, acidifier phosphoric acid, natural flavor, flavor caffeine","additive_flags":"INS 150d Caramel"},
    {"barcode":"8906076133289","product_name":"Protein Chips Korean Kimchi","brands":"The Baker's Dozen","ingredients_text":"Multi grain blend (urad dal, jowar, chickpea, soya protein isolate, tapioca starch, rice bran oil, spices and condiments (red chilli powder, green chilli powder, cumin, caraway seed, ginger, nutmeg, clove, cinnamon), dried vegetable powder (garlic & onion), soya sauce powder, salt, citric acid","additive_flags":"Clean"},
    {"barcode":"8901262110303","product_name":"Whey Shake","brands":"Amul","ingredients_text":"Whey protein concentrate, cocoa powder (3%), chocolate vanilla flavor, INS 355, beta-galactosidase","additive_flags":"Clean"},
    {"barcode":"52018329","product_name":"Pepsi","brands":"Pepsi","ingredients_text":"Boisson gazeuse rafraîchissante aux extraits végétaux. Ingrédients: eau gazéifiée, sucre, colorant (caramel e150d), acidifiant (acide phosphorique), arômes (dont extraits végétaux et caféine)","additive_flags":"INS 150d Caramel"},
    {"barcode":"7501008016572","product_name":"Choco Krispies","brands":"Kellogg's","ingredients_text":"Cuadritos de cereal (mezcla de cereales (harina de maíz de grano entero (mín. 15%), harina de trigo, sémola de maíz), azúcar, cocoa, maltodextrina, aceite de palmiste, saborizante chocolate vainilla, malta, colorantes artificiales (caramelo IV, amarillo no. 5, rojo no. 40, azul no. 2), sal), cobertura sabor chocolate (mín. 45%) (azúcar, grasa vegetal, leche descremada, fibra, cocoa natural en polvo, emulsificante (lecitina de soya), saborizante idéntico al natural vainillina)","additive_flags":"Artificial colours (Yellow 5, Red 40, Blue 2)"},
    {"barcode":"6221134013023","product_name":"Snickers 200g","brands":"Snickers","ingredients_text":"شوكولاتة بالحليب (35%) بالنوجة الطرية (14%) والكراميل (28%) مع الفول السوداني (22%). المكونات: سكر، شراب الجلوكوز، فول سوداني، مسحوق الحليب منزوع الدسم، زبدة الكاكاو، كتلة الكاكاو، دهن نباتي غير مهدرج (دهن النخيل)، لاكتوز، دسم الحليب، ملح، مستحلب من مصدر نباتي ليسيثين الصويا (إي 322)، مستخلص بروتين الحليب. مشتقة من حليب البقر. يحتوي المنتج على حليب، فول سوداني، صويا. قد يحتوي على بيض، بندق","additive_flags":"Clean"},
    {"barcode":"8902080304028","product_name":"7Up Lemon 250ml","brands":"PepsiCo","ingredients_text":"Carbonated water, sugar, acidity regulators (330, 331, 296), flavour (natural flavouring substances), preservative (211), stabilizer (436)","additive_flags":"INS 211 preservative"},
    {"barcode":"8908000339446","product_name":"Instant Premix Original","brands":"KarakTea","ingredients_text":"Sucrose, milk powder, tea extract, maltodextrin","additive_flags":"Clean"},
    {"barcode":"3181411323906","product_name":"Alouettes Sans Tête","brands":"Marseillaises","ingredients_text":"Viande (57%) bovine fraîche (gîte noix) en fines tranches roulées en alouettes sur poitrine de porc, ail déshydraté, persil déshydraté en poudre (viandes origine UE). 5 alouettes cuisinées en sauce (43%), avec pulpe de tomates, lardons de porc VPF, fond de bœuf, oignons, carottes, vin blanc, poireaux, sel, ail, poivre, herbes aromatiques","additive_flags":"Clean"},
    {"barcode":"38000184956","product_name":"Queso","brands":"Pringles","ingredients_text":"Papas deshidratadas, aceite de algodón, almidón de maíz, harina de maíz amarillo desgerminado, harina de arroz, maltodextrina, mono y diglicéridos (emulsificante), sal, dextrosa, aceite de coco, suero de leche, glutamato monosódico (acentuador del aroma), cebolla en polvo, azúcar, queso cheddar, queso azul, ácido láctico (regulador de la acidez), leche descremada, sabores naturales y artificiales a queso, ácido cítrico (regulador de la acidez), mantequilla, caseinato de sodio, extracto de levadura, inosinato disódico (acentuador del aroma), guanilato disódico (acentuador del aroma), colorantes artificiales [amarillo 5 (tartrazina), amarillo 6 (amarillo ocaso), amarillo 5 laca (tartrazina), amarillo 6 laca (amarillo ocaso)], dextrosa de trigo","additive_flags":"INS 621 MSG + INS 102 + INS 110 colours"},
    {"barcode":"3168930168102","product_name":"Lay's Recette à l'Ancienne Nature Maxi Format","brands":"Lay's","ingredients_text":"Potatoes (66%), vegetable oils (sunflower, rapeseed, maize in varying proportions), salt","additive_flags":"Clean"},
    {"barcode":"28400655552","product_name":"Doritos Dinamita","brands":"Doritos","ingredients_text":"Corn, vegetable oil (corn, canola, and/or sunflower oil), and 2% or less of the following: maltodextrin (made from corn), salt, citric acid, sugar, monosodium glutamate, artificial color (red 40 lake, yellow 6 lake), hydrolyzed corn gluten, yeast extract, sodium diacetate, cheddar cheese (milk, cheese cultures, salt, enzymes), modified corn starch, natural flavor, onion powder, whey, corn syrup solids, garlic powder, romano cheese (part-skim cow's milk, cheese cultures, salt, enzymes), buttermilk, whey protein concentrate, disodium inosinate, and disodium guanylate","additive_flags":"INS 621 MSG + Artificial colours"},
    {"barcode":"5449000265098","product_name":"Coca-Cola Energy","brands":"Coca-Cola","ingredients_text":"Carbonated water, sugar, dextrose, colour (e150d), acid (e338), caffeine (0.03%), preservatives (e211, e202), natural flavourings, vitamins (niacin (b3) and b6), guarana extract (0.001%)","additive_flags":"INS 150d + INS 211 + INS 202"},
    {"barcode":"28400415309","product_name":"Doritos Spicy Nacho","brands":"Doritos","ingredients_text":"Corn, vegetable oil (sunflower, corn, and/or canola oil), maltodextrin (made from corn), salt, whey, monosodium glutamate, buttermilk, romano cheese (cow's milk, cheese cultures, salt, enzymes), cheddar cheese (milk, cheese cultures, salt, enzymes), corn starch, onion powder, garlic powder, dextrose, natural and artificial flavor, spices, lactose, sodium caseinate, artificial color (including yellow 6, yellow 5, red 40), lactic acid, citric acid, sugar, garlic powder, skim milk, red and green bell peppers, disodium inosinate, and disodium guanylate","additive_flags":"INS 621 MSG + Artificial colours"},
    {"barcode":"5449000265104","product_name":"Coca-Cola Energy No Sugar","brands":"The Coca-Cola Company","ingredients_text":"Sparkling water, acids (citric acid, phosphoric acid), natural flavourings, colour (caramel e150d), acidity regulator (sodium bicarbonate), sweeteners (acesulfame k, sucralose), caffeine (0.03%); preservatives (sodium benzoate, potassium sorbate), vitamins (niacin (b3), vitamin b6), guarana extract (0.001%)","additive_flags":"INS 150d + INS 211 + INS 202"},
    {"barcode":"8906100881643","product_name":"Masala Jeera Kashmira","brands":"Hajoori","ingredients_text":"Carbonated water, cane sugar, iodised salt, acidity regulator - citric acid (e330), permitted class II preservative - sodium benzoate (e211), contains permitted food colour - caramel-IV (e150d), and added natural and nature identical flavouring substances of jeera (cumin) and spices","additive_flags":"INS 211 + INS 150d"},
    {"barcode":"8904083300809","product_name":"Cow Ghee","brands":"Milky Mist","ingredients_text":"Milk fat","additive_flags":"Clean single-ingredient"},
    {"barcode":"5053827197212","product_name":"Fruit Winders Strawberry Flavour","brands":"Kellogg's","ingredients_text":"Fruit (70%) (pear puree from concentrate, strawberry puree from concentrate {23%}), glucose syrup, maltodextrin, sugar, palm oil, gelling agent (pectin), emulsifiers (mono and diglycerides of fatty acids), natural flavouring, elderberry juice concentrate, citric acid, acidity regulator (sodium citrate), antioxidant (ascorbic acid), malic acid","additive_flags":"Clean"},
    {"barcode":"7613287115782","product_name":"Smarties","brands":"Nestlé","ingredients_text":"Sugar, cocoa butter, milk solids, cocoa mass, colours, emulsifiers","additive_flags":"Clean"},
    {"barcode":"9300682047500","product_name":"Maltesers","brands":"Mars","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, malt extract (barley), glucose syrup, vegetable fat, maltodextrin, emulsifiers (soy lecithin, 492), raising agents (501, 500), vegetable gum (440), salt, flavour. Milk chocolate contains cocoa solids 25%, milk solids 23%","additive_flags":"Clean"},
    {"barcode":"8886467103438","product_name":"Sour Cream & Onion","brands":"Pringles","ingredients_text":"Dehydrated potato, vegetable oils, wheat starch, rice flour, emulsifier (471), maltodextrin, salt, whey powder, flavour enhancers (621, 631, 627), dextrose, onion powder, sugar, flavour, non-fat milk powder, sour cream powder, food acids (330, 270, 296), cultured non-fat milk, sodium caseinate, yeast extract","additive_flags":"INS 621 + INS 631 + INS 627"},
    {"barcode":"5000159461849","product_name":"Twix 6pk 300g","brands":"MARS NORGE AS","ingredients_text":"Socker/sukker, glukossirap/glukosesirup, vetemjöl/hvedemel/hvetemel (17%), palmfett, kakaosmör/kakaosmør, skummjölkspulver, kakaomassa/masse, laktos, melkefett, myse-pulver, fettreducerat/fedtfattigt kakaopulver, salt, emulgeringsmedel (sojalecitin), jäsningsmedel/hævemiddel (e500), naturlig vaniljekstrakt. Minst 25% kakaotørstof","additive_flags":"Clean"},
    {"barcode":"8902082805004","product_name":"Grape Squash","brands":"Grandma's","ingredients_text":"Water, sugar, grape juice, citric acid (e-330), contains permitted class II preservative e211, e202, added synthetic flavour (grape) and permitted synthetic food colour (code-e 110, e 122, e 124, e 133)","additive_flags":"INS 211 + INS 202 + INS 110 + INS 122 + INS 124 + INS 133"},
    {"barcode":"38000291906","product_name":"Protein Meal Bars","brands":"Kellogg's","ingredients_text":"Soy protein isolate, sugar, soluble corn fiber, vegetable oil (palm and palm kernel oil with sorbitan tristearate, soybean and palm oil with tbhq for freshness), peanut butter (peanuts), fructose, inulin, corn syrup, dextrose, cocoa processed with alkali, rice, whole grain wheat, water, contains 2% or less of vegetable glycerin, sorbitol, salt, wheat bran, peanut oil, natural flavors, soluble wheat fiber, whey, soy lecithin, malt flavor, sesame seed oil, bht for freshness, almond flour. Vitamins and minerals: calcium carbonate, vitamin c (ascorbic acid), vitamin e, niacinamide, zinc oxide, reduced iron, vitamin b6, vitamin b1, vitamin b2, vitamin a palmitate, vitamin b12, folic acid, vitamin d3","additive_flags":"INS 319 TBHQ + BHT"},
    {"barcode":"8710398517807","product_name":"Chips Tomato Ketchup","brands":"Heinz/Lay's","ingredients_text":"Potatoes, vegetable oils (sunflower, rapeseed, corn, in varying proportion), heinz tomato ketchup taste [sugar, flavours, whey powder (milk), tomato powder, potassium chloride, acidifier (citric acid), dye (paprika extract)], salt","additive_flags":"Clean"},
    {"barcode":"897581000396","product_name":"Peppermint Marshmallows","brands":"Dandies Marshmallows","ingredients_text":"(All vegan) Tapioca syrup, cane sugar, filtered water, tapioca starch, carrageenan, soy protein, natural peppermint flavor, beet juice concentrate","additive_flags":"Clean vegan"},
    {"barcode":"38000188725","product_name":"Cinnamon Cereal","brands":"Kellogg's","ingredients_text":"Milled corn, sugar, malt flavor, contains 2% or less of salt, cinnamon, natural flavor. Vitamins and minerals: iron (ferric phosphate), niacinamide, vitamin b6 (pyridoxine hydrochloride), vitamin b2 (riboflavin), vitamin b1 (thiamin hydrochloride), folic acid, vitamin d3, vitamin b12","additive_flags":"Clean"},
    {"barcode":"9310015249433","product_name":"Doritos Mountain Dew","brands":"Doritos","ingredients_text":"Corn, canola oil, sugar, dextrose, lime juice powder, fructose, flavours, maltodextrin, buttermilk powder (milk), flavour enhancer (621), salt, citrus beverage powder, colours (102, 133, 110, 100), sunflower oil, antioxidants (tocopherols, ascorbic acid, rosemary extract, citric acid). Contains gluten. Contains milk or milk products. Contains soybeans or soybean products","additive_flags":"INS 621 + INS 102 + INS 133 + INS 110 + INS 100"},
    {"barcode":"5449000017062","product_name":"Coca Cola Zero Zahăr cu Gust de Portocale și Vanilie","brands":"Coca-Cola Company","ingredients_text":"Apă, dioxid de carbon, colorant e150d, arome naturale inclusiv cafeină, îndulcitori: ciclamați, acesulfam-k și aspartam, acidifiant acid fosforic, corector de aciditate citrați de sodiu. Conține o sursă de fenilalanină","additive_flags":"INS 150d Caramel"},
    {"barcode":"5000328205939","product_name":"Doritos Chili Heatwave","brands":"Doritos","ingredients_text":"Corn (maize), vegetable oils (rapeseed, in varying proportions), chilli heatwave flavour (sugar, flavourings (contains soya, wheat), hydrolysed protein, acidity regulators (sodium acetates, citric acid, malic acid), flavour enhancers (monosodium glutamate, disodium 5'-ribonucleotides), onion powder, salt, garlic powder, potassium chloride, soybean, wheat, colour (paprika extract))","additive_flags":"INS 621 MSG"},
    {"barcode":"5449000229861","product_name":"Coca-Cola","brands":"Coca-Cola/Coke","ingredients_text":"Carbonated water, sugar, colour (caramel e150d), phosphoric acid, natural flavourings including caffeine","additive_flags":"INS 150d Caramel"},
    {"barcode":"38000228346","product_name":"Disney Princess","brands":"Kellogg's","ingredients_text":"Corn syrup, sugar, apple puree concentrate, modified food starch, water, gelatin. Contains 2% or less of citric acid, natural and artificial flavors, vitamin c (ascorbic acid), palm and coconut oil, carnauba wax, yellow 5, sodium citrate, red 40, blue 1","additive_flags":"Artificial colours (Yellow 5, Red 40, Blue 1)"},
    {"barcode":"47677254862","product_name":"Snickers Ice Cream","brands":"Snickers","ingredients_text":"Skim milk, sugar, peanuts, cream, corn syrup, coconut oil, milk, palm oil, less than 2% of: lactose, whey, chocolate, cocoa, milkfat, salt, soy lecithin, mono and diglycerides, carob bean gum, guar gum, carrageenan, artificial flavor","additive_flags":"Clean"},
    {"barcode":"8000550503299","product_name":"Orzoro","brands":"Nestlé","ingredients_text":"Orzo tostato macinato (roasted ground barley)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8410100025155","product_name":"Nesquik","brands":"Nestlé","ingredients_text":"Sugar, defatted cocoa (or 22.1%), vitamins (c, b, d), mineral (ferric pyrophosphate, zinc sulfate), aroma, cinnamon, salt, sunflower oil, emulsifier (soy lecithin)","additive_flags":"Clean"},
    {"barcode":"3168930160687","product_name":"Pepsi Max 7 x 33 cl + 1 Offerte","brands":"Diet Pepsi/Pepsi Zero","ingredients_text":"Eau gazéifiée, colorant (caramel e150d), édulcorants (aspartame, acésulfame k), acidifiants (acide phosphorique, acide citrique), correcteur d'acidité (citrate de sodium), arômes (dont extraits végétaux et caféine). Contient une source de phénylalanine","additive_flags":"INS 150d Caramel"},
    {"barcode":"9313820001500","product_name":"Pepsi 1.25","brands":"Pepsi","ingredients_text":"Carbonated water, sugar, colour (150d), food acid (338), caffeine, flavour","additive_flags":"INS 150d Caramel"},
    {"barcode":"5000159438537","product_name":"Maltesers","brands":"Mars","ingredients_text":"Sugar, skimmed milk powder, cocoa butter, glucose syrup, barley malt extract, cocoa mass, palm fat, milk fat, lactose, whey permeate (from milk), emulsifiers (soya lecithin, e492), wheat flour, palm kernel fat, raising agents (e341, e500, e501), palm kernel oil, wheat gluten, whey powder (from milk), salt, glazing agent (pectins), vanilla extract. Milk chocolate contains milk solids 14% minimum","additive_flags":"Clean"},
    {"barcode":"7622202276262","product_name":"Cadbury Cocoa Life","brands":"Cadbury","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"6914973203778","product_name":"Snickers","brands":"Snickers","ingredients_text":"Milk chocolate [sugar, cocoa butter, cocoa mass, skim milk powder, lactose, milk fat, vegetable fat (palm, shea, sunflower), emulsifier (soy lecithin), artificial flavour], peanuts (22%), glucose syrup, sugar, skim milk powder, vegetable fat (palm, shea, sunflower), salt, egg albumen powder, artificial flavour. Contains vegetable fats in addition of cocoa butter. Allergen: contains milk, soy, egg and peanuts. May contain: oat, wheat and tree nuts","additive_flags":"Clean"},
    {"barcode":"5000112597363","product_name":"Fanta Exotic 1.5L","brands":"Coca-Cola European Partners Norge","ingredients_text":"Kullsyreholdig vann, sukker, råsaft fra konsentrat 3% (appelsin 2.6%, pasjonsfrukt 0.2%, fersken 0.2%), citrus ekstrakt, surhetsregulerende middel (e330), frukt- og vegetabilsk konsentrat (solbær, gulrot, svartsurbær, hylleblomst, sitron, saflor), naturlige aromaer, stabilisator (e445, e414)","additive_flags":"Clean"},
    {"barcode":"5900951283987","product_name":"Snickers Creamy Peanut Butter","brands":"Snickers","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"5900951261060","product_name":"Шоколадний Батончик Snickers з Горіхами","brands":"Snickers","ingredients_text":"Молочний шоколад (35%) - цукор, какао-масло, какао терте, знежирене молоко, молочний жир, лактоза, суха молочна сироватка, емульгатор (соєвий лецитин), натуральний ароматизатор (екстракт ванілі); карамель (27%): глюкозний сироп, цукор, сухе знежирене молоко, олія соняшникова, олія пальмова, лактоза, суха молочна сироватка, сіль, натуральний ароматизатор (екстракт ванілі); смажений арахіс (22%); нуга (16%): глюкозний сироп, цукор, сіль, олія пальмова, сухий яєчний білок, молочний білок","additive_flags":"Clean"},
    {"barcode":"4260261960260","product_name":"Coca-Cola Cherry","brands":"Coca-Cola","ingredients_text":"Wasser, Glukose-Fruktose-Sirup, Kohlensäure, Farbstoff E150d, Säuerungsmittel: Phosphorsäure E338, Aroma, Aroma Koffein","additive_flags":"INS 150d Caramel"},
    {"barcode":"5056357910764","product_name":"Snickers","brands":"Mars Chocolate","ingredients_text":"Sugar, palm oil, skimmed milk powder, lactose, whey powder (milk), fat-reduced cocoa, peanuts (4.5%), milk fat, cocoa mass, cocoa butter, emulsifier (sunflower lecithin), salt, flavouring, caramelized sugar syrup, egg white powder","additive_flags":"Clean"},
    {"barcode":"38000270888","product_name":"Chocolatey Sweetened Rice Cereal","brands":"Kellogg's","ingredients_text":"Rice, sugar, cocoa processed with alkali, hydrogenated vegetable oil (coconut, soybean and/or cottonseed), salt, malt flavor, artificial flavor","additive_flags":"Hydrogenated oil"},
    {"barcode":"7613287109583","product_name":"Lion Mini 234g","brands":"Nestlé/Lion Minis","ingredients_text":"Sugar, glucose syrup, milk solids, cocoa butter, cocoa mass, refined wheat flour, emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"64100143135","product_name":"Rice Krispies","brands":"Kellogg's","ingredients_text":"Rice, sugars (sugar, corn and barley malt extract), salt, sunflower lecithin, vitamins and minerals: iron phosphate, niacinamide, thiamine hydrochloride, cholecalciferol (vitamin d3), pyridoxine hydrochloride, d-calcium pantothenate, folic acid. Contains: barley","additive_flags":"Clean"},
    {"barcode":"8904063223036","product_name":"Mexilla Flaming Hot","brands":"Haldiram's","ingredients_text":"Corn (70%), edible vegetable oil (palmolein, cotton seed, rice bran), spices and condiments [(red/chilli powder (1%), garlic powder, onion powder, rice flour, paprika extract (INS 160c)], iodised salt, sugar powder, hydrolysed vegetable (soy) powder, acidity regulators (INS 330, INS 296, INS 340), flavour enhancers (INS 627, INS 631), anticaking agent (INS 551), stabiliser (INS 414), natural and nature identical flavouring substances","additive_flags":"INS 627 + INS 631"},
    {"barcode":"5059319014210","product_name":"All Bran Fruit'n Fibre","brands":"Kellogg's","ingredients_text":"Volkorentarwe (70%), gedroogd fruit (25%) (rozijnen, sultana's, kokosnoot, banaan {banaan, kokosolie, suiker}, appel), suiker, gerstemoutextract, zout, niacine, ijzer, vitamine b6, riboflavine, thiamine, foliumzuur, vitamine d, vitamine b12. Bevat mogelijk gluten uit andere granen, noten, soja. Allergie-informatie bevat: tarwe, gerst, glutenbevattende granen. Kan bevatten: soja, noten","additive_flags":"Clean"},
    {"barcode":"5059319021836","product_name":"Rice Krispies","brands":"Kellogg's","ingredients_text":"Rice, sugar, salt, barley malt extract, niacin, iron, vitamin b6, riboflavin, thiamin, folic acid, vitamin d, vitamin b12","additive_flags":"Clean"},
    {"barcode":"8901042968711","product_name":"Hing - Compounded Asafoetida Powder","brands":"MTR","ingredients_text":"Wheat flour (63.5%), gum arabic, asafoetida","additive_flags":"Clean"},
    {"barcode":"5053827206211","product_name":"Barres Céréales WKK Kellogg's Graines de Tournesol et Chia","brands":"Kellogg's","ingredients_text":"Cacahuètes (47%), raisins secs (33%), avoine sans gluten, graines de tournesol (4%), jus de pomme concentré, graines de chia salvia hispanica (2.5%)","additive_flags":"Clean"},
    {"barcode":"38000114717","product_name":"Pancakes Maple","brands":"Kellogg's","ingredients_text":"Whole wheat flour, water, sugar, vegetable oil (soybean, palm, palm kernel, and/or canola oil), buttermilk, eggs, contains 2% or less of leavening (baking soda, sodium aluminum phosphate, monocalcium phosphate), fructose, salt, corn cereal, rice flour, yellow corn flour, cornstarch, natural and artificial flavors, corn syrup, caramel color, malt extract, corn syrup solids, soy lecithin. Vitamins and minerals: vitamin a palmitate, reduced iron, niacinamide, vitamin b12, vitamin b6 (pyridoxine hydrochloride), vitamin b1 (thiamin hydrochloride), vitamin b2 (riboflavin)","additive_flags":"INS 150d Caramel"},
    {"barcode":"8906021075008","product_name":"Creamy Peanut Butter","brands":"5Star","ingredients_text":"Peanuts, sugar, edible vegetable oil, salt","additive_flags":"Clean"},
    {"barcode":"8906161220306","product_name":"Oppa Rice Hakka Noodles","brands":"Vatsa's","ingredients_text":"Rice, water","additive_flags":"Clean single-ingredient"},
    {"barcode":"850024326156","product_name":"Carolina Gold Rice","brands":"Marsh Hen Mill","ingredients_text":"Long grain rice","additive_flags":"Clean single-ingredient"},
    {"barcode":"8909081013737","product_name":"Strawberry Smoothie","brands":"Sunfeast","ingredients_text":"Water, milk solids (33.5%), sugar, strawberry pulp (7.4%), banana puree, strawberry chunks (3.9%), nata de coco, stabilizers (466, 418), acidity regulator (330), nature identical flavouring substances, chia seeds (0.16%), natural flavours and natural flavouring substances, antioxidant (300), sweetener (960) and colours (122, 110)","additive_flags":"INS 122 + INS 110 colours"},
    {"barcode":"44000077334","product_name":"Space Dunk","brands":"Oreo","ingredients_text":"Sugar, unbleached enriched flour (wheat flour, niacin, reduced iron, thiamine mononitrate [vitamin b1], riboflavin [vitamin b2], folic acid), palm oil, soybean and/or canola oil, cocoa (processed with alkali), corn starch, high fructose corn syrup, corn syrup, baking soda, salt, soy lecithin, blue 1 lake, chocolate, natural and artificial flavor, blue 2 lake, red 40, red 3, carbon dioxide","additive_flags":"Artificial colours (Blue 1, Blue 2, Red 40, Red 3)"},
    {"barcode":"5000159476966","product_name":"Maxi Barres","brands":"Mars","ingredients_text":"Sucre, lait écrémé (15%), sirop de glucose, crème légère (lait), eau, lait écrémé concentré sucré, beurre de cacao, matière grasse de noix de coco, pâte de cacao, matière grasse de palme, lait écrémé en poudre, extrait de malt d'orge, matière grasse du lait, lactose, petit-lait en poudre, cacao maigre, émulsifiants (lécithine de soja, e471, e477), stabilisants (e407, e410, e412), sel, extrait naturel de vanille, arôme naturel","additive_flags":"Clean"},
    {"barcode":"7613033641312","product_name":"Nestlé Naturnes Petits Pois+Carottes+Courgettes","brands":"Nestlé/Naturnes","ingredients_text":"Courgettes: légumes 55% (courgettes 30%, panais 11%, patates douces, pommes de terre, épinards 2%), eau de cuisson, maïs, amidon, huile de colza. Carottes: carottes 75%, eau de cuisson, huile de colza. Petits pois: petits pois 50%, eau de cuisson, huile de colza","additive_flags":"Clean baby food"},
    {"barcode":"5000159526937","product_name":"Galaxy Easter Egg","brands":"Galaxy/Mars","ingredients_text":"Sugar, cocoa butter, skimmed milk powder, cocoa mass, lactose and protein from whey (from milk), palm fat, whey powder (from milk), milk fat, emulsifier (soya lecithin), starch, maize protein, colour/colour (iron oxides and hydroxides), raising agent (e500), natural flavouring, natural vanilla extract. Milk chocolate contains milk solids 14% minimum and cocoa solids 25% minimum. Milk chocolate contains vegetable fats in addition to cocoa butter","additive_flags":"Clean"},
    {"barcode":"5000159311373","product_name":"ICE CREAM Snickers","brands":"Snickers","ingredients_text":"Woda, cukier, mleko odtłuszczone, mąka pszenna, syrop glukozowy, olej kokosowy, orzeszki ziemne, tłuszcz kokosowy, laktoza i białko z serwatki (mleko), tłuszcz kakaowy, słodzone odtłuszczone mleko skondensowane, syrop z cukru inwertowanego, miazga kakaowa, odtłuszczone mleko w proszku, tłuszcz mleczny, laktoza (mleko), serwatka w proszku (mleko), emulgatory (lecytyna sojowa, lecytyna słonecznikowa, e471, polirycynooleinian poliglicerolu), kakao o obniżonej zawartości tłuszczu, cukier palony, sól, stabilizatory (e407, e410, e412), substancja zagęszczająca (guma arabska), aromaty naturalne","additive_flags":"Clean"},
    {"barcode":"38000251030","product_name":"Chocolatey Dipped Flakes with Almonds","brands":"Kellogg's","ingredients_text":"Whole grain wheat, rice, sugar, almonds, wheat bran, hydrogenated vegetable oil (palm kernel, coconut, soybean and/or cottonseed), contains 2% or less of brown sugar syrup, milk, salt, milled corn, cocoa processed with alkali, semisweet chocolate (sugar, chocolate, dextrose), cocoa, natural flavor, malt flavor, modified tapioca starch, iodized salt (salt, potassium iodate), shellac, soy lecithin, bht for freshness. Vitamins and minerals: calcium carbonate, reduced iron, vitamin c (ascorbic acid), niacinamide, vitamin e acetate","additive_flags":"Hydrogenated oil + BHT"},
    {"barcode":"8851959127018","product_name":"น้ำอัดลม ตราโค้ก (Thai Coca-Cola)","brands":"Coca-Cola/โค้ก","ingredients_text":"น้ำตาล 10%, กรดคาร์บอนิก (INS 290), สารให้สี (INS 150d), สารควบคุมความเป็นกรด (INS 338), แต่งกลิ่นธรรมชาติ","additive_flags":"INS 150d Caramel"},
    {"barcode":"8906098670076","product_name":"Peri Peri Thriller Popcorn","brands":"Ultrapop","ingredients_text":"Popped corn, refined edible palmolein oil, iodized salt, sugar, spices and condiments (chili, coriander, herbs, garlic powder, onion powder, maltodextrin, dry mango powder, tomato powder), acidity regulator (e330, e334), flavor enhancer (e627, 631), added natural & nature identical flavouring substances","additive_flags":"INS 627 + INS 631"},
    {"barcode":"5000159558518","product_name":"Minis","brands":"Mars","ingredients_text":"Sucre, sirop de glucose, lait écrémé en poudre, beurre de cacao, pâte de cacao, huile de tournesol, perméat de lactosérum (lait), matière grasse de palme, cacao maigre en poudre, matière grasse du lait, extrait de malt d'orge, sel, émulsifiant (lécithine de soja), blanc d'oeuf en poudre. (Peut contenir: cacahuètes, fruits à coque)","additive_flags":"Clean"},
    {"barcode":"9300684108018","product_name":"Rice Crisps in Milk Chocolate","brands":"Nestlé","ingredients_text":"Milk chocolate (92%) (sugar, milk solids, cocoa butter, cocoa mass, vegetable fat, antioxidant (309), emulsifiers (soya lecithin, 475), flavour), rice crisp (8%) (rice flour, sugar, salt, emulsifier (471), dextrose, colour 160b (wheat)). Chocolate contains minimum 20% cocoa solids","additive_flags":"Clean"},
    {"barcode":"8906068355675","product_name":"Soya Chaap In Brine","brands":"Pachranga's Farm Fresh","ingredients_text":"Soy flour, wheat flour, plain flour, water, salt","additive_flags":"Clean"},
    {"barcode":"8904238426842","product_name":"Natural Jaggery Powder","brands":"RMP","ingredients_text":"Sugarcane jaggery","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906117091219","product_name":"Shortcuts Peanut Butter Wafer Bites","brands":"BRB","ingredients_text":"Peanut butter (54.5%), refined wheat flour, jaggery, milk solids, refined coconut oil, emulsifier (soy lecithin), iodized salt, baking soda, milk protein concentrate, butter & vanilla. Wheat","additive_flags":"Clean"},
    {"barcode":"8908022521058","product_name":"Evocus Water","brands":"Evocus","ingredients_text":"Treated drinking water with added minerals (potassium bicarbonate, potassium carbonate, magnesium sulphate, calcium sulphate)","additive_flags":"Clean"},
    {"barcode":"38000332159","product_name":"Eggo Waffles","brands":"Kellogg's","ingredients_text":"Water, enriched flour (wheat flour, niacin, reduced iron, vitamin b1 [thiamin mononitrate], vitamin b2 [riboflavin], folic acid), sugar, soy protein isolate, whey protein concentrate, vegetable oil (soybean, palm, canola and/or cottonseed), buttermilk, leavening (baking soda, sodium aluminum phosphate, monocalcium phosphate), salt, natural flavors, eggs, soy lecithin. Vitamins and minerals: iron, vitamin a palmitate, vitamin b6 (pyridoxine hydrochloride), vitamin b12. Contains wheat, soy, milk, and egg ingredients","additive_flags":"Clean"},
    {"barcode":"5000159487443","product_name":"Mars Xtra Choc","brands":"Mars","ingredients_text":"Sucre, sirop de glucose, pâte de cacao, beurre de cacao, lait entier en poudre, huile de tournesol, lait écrémé en poudre, cacao maigre, lactose, petit-lait en poudre, matière grasse du lait, extrait de malt d'orge, émulsifiant (lécithine de soja), sel, matière grasse de palme, blanc d'oeuf en poudre, protéine de lait, extrait naturel de vanille, arômes naturels","additive_flags":"Clean"},
    {"barcode":"7613033902437","product_name":"Maggi Saveur à l'Ancienne Velouté de Légumes au Comté A.O.C 81g","brands":"Maggi/Saveur à l'Ancienne","ingredients_text":"Légumes 49%: pomme de terre 39%, poireau 3.1%, oignon 3%, carotte, navet, petits pois; farine de blé, lait écrémé en poudre, exhausteur de goût: glutamate monosodique; arômes (lait) dont arôme fromage, crème en poudre (lait), sel, comté a.o.c. 3.2% (lait), huile de tournesol, ail, persil, curcuma, laurier, thym, extraits naturels de carotte et de céleri; antioxydant: bha. Peut contenir des traces de: œuf, poisson, crustacés","additive_flags":"INS 621 MSG + BHA"},
    {"barcode":"7613034331670","product_name":"Fitness Chocolate Negro","brands":"Nestlé","ingredients_text":"Whole wheat (40.3%), rice (29.5%), dark chocolate (20.5%) [cocoa (11.3%), sugar, milk fat, emulsifier (soy lecithin), natural vanilla aroma], sugar, whole oat flakes (5.6%), invert sugar syrup, barley malt extract (barley, barley malt), calcium carbonate, salt, glucose syrup, coating agents (arabic gum, polydextrose), molasses, antioxidant (extract rich in tocopherols), iron, niacin, pantothenic acid, vitamin b6, riboflavin, folic acid. May contain peanut","additive_flags":"Clean"},
    {"barcode":"0079200370213","product_name":"Nerds","brands":"Nestlé","ingredients_text":"Sugars (dextrose, sugar, corn syrup), malic acid, natural flavours, carnauba wax, brilliant blue fcf, tartrazine, sunset yellow fcf. May contain: egg","additive_flags":"INS 133 + INS 102 + INS 110 colours"},
    {"barcode":"44000087579","product_name":"Cinnamon Bun Flavored","brands":"Oreo","ingredients_text":"Sugar, unbleached enriched flour (wheat flour, niacin, reduced iron, thiamine mononitrate [vitamin b1], riboflavin [vitamin b2], folic acid), palm oil, soybean and/or canola oil, high fructose corn syrup, cornstarch, salt, baking soda, cinnamon, soy lecithin, natural and artificial flavor","additive_flags":"Clean"},
    {"barcode":"3023290025024","product_name":"Yaos Le Yaourt à la Grecque sur Lit de Marrons","brands":"Nestlé","ingredients_text":"Lait entier (65%), sucre (13%), crème (lait) (9.2%), eau, purée de marrons (5%), cacao maigre en poudre, jus de citron concentré, arôme naturel, amidon de maïs, épaississant (carraghénanes), poudre de lait écrémé, ferments lactiques. Fabriqué en France avec du lait français","additive_flags":"Clean"},
    {"barcode":"6001068312108","product_name":"Gold Cross","brands":"Nestlé","ingredients_text":"385 g","additive_flags":"Verify"},
    {"barcode":"8594008040288","product_name":"Mirinda","brands":"PepsiCo","ingredients_text":"(CZ) Voda, cukr/fruktózo-glukózový sirup, oxid uhličitý, pomerančová šťáva z koncentrátu (4%), kyseliny: kyselina citronová, konzervant: sorban draselný, antioxidant: kyselina askorbová, aroma, sladidla: acesulfam k a sukralóza, stabilizátor: arabská guma, barviva: beta-apo-8'-karotenal a karoteny. (SK) Voda, cukor/fruktózo-glukózový sirup, oxid uhličitý, pomarančová šťava z koncentrátu (4%), kyseliny: kyselina citrónová, konzervant: sorban draselný, antioxidant: kyselina askorbová, aróma, sladidlá: acesulfám k a sukralóza, stabilizátor: arabská guma, farbivá: beta-apo-8'-karotenál a karotény. (HU) Víz, cukor/fruktóz-glükóz szirup, szén-dioxid, sűrített narancslé (4%), étkezési sav: citromsav, tartósítószer: kálium-szorbát, antioxidáns: aszkorbinsav, aromák, édesítőszerek: aceszulfám k, szukralóz, stabilizátor: gumiarábikum, színezékek: béta-apo-8'-karotinal, karotin","additive_flags":"INS 202 preservative + Colours"},
    {"barcode":"70221009731","product_name":"Chocolate Candy Bar","brands":"Oreo","ingredients_text":"Sugar, palm oil, cocoa butter, nonfat milk, wheat flour, whey, chocolate, milkfat, contains less than 2% of hazelnut paste, soy lecithin, wheat starch, cocoa (processed with alkali), glucose-fructose syrup (glucose syrup, high fructose corn syrup), salt, potassium bicarbonate, baking soda, artificial flavor, sunflower lecithin","additive_flags":"Clean"},
    {"barcode":"5000159491211","product_name":"Inspiration Cappuccino","brands":"Mars/Twix","ingredients_text":"Sucre, lait écrémé, sirop de glucose, crème légère (lait), eau, lait écrémé concentré sucré, beurre de cacao, matière grasse de noix de coco, matière grasse de palme, pâte de cacao, farine de blé, lait écrémé en poudre, lactose, matière grasse du lait, petit-lait en poudre, cacao maigre, beurre (lait), émulsifiants (lécithine de soja, e471, e492), lait entier en poudre, arômes naturels, sel, stabilisants (e407, e410, e412), cacao en poudre, poudre à lever (e503), extrait naturel de vanille","additive_flags":"Clean"},
    {"barcode":"8846000010029","product_name":"Pepsi Twist","brands":"Pepsi","ingredients_text":"Carbonated water, sugar, caramel color, natural flavour, phosphoric acid, citric acid, sodium citrate, sodium benzoate, caffeine","additive_flags":"INS 150d + INS 211"},
    {"barcode":"0064100001497","product_name":"Céréales Müslix (Croustade Aux Pommes)","brands":"Kellogg's","ingredients_text":"Blé entier, avoine entière, flocons d'orge, sucre, son de blé, amandes, maïs, pommes déshydratées, riz, huile de copra, substances laitières modifiées, extrait de maïs et d'orge maltée, sel, riz croustillant (riz moulu, sucre, extrait d'orge maltée, sel), cannelle, mélasse verte, arôme naturel, mélange de tocophérols (pour conserver la fraîcheur), huile végétale, bht. Contient des ingrédients du blé, de l'avoine, de l'orge, de l'amande et du lait","additive_flags":"BHT"},
    {"barcode":"5000159506007","product_name":"Mars Choc Brownie Chocolate Bar 4X40G","brands":"Mars","ingredients_text":"Sugar, glucose syrup, skimmed milk powder, sunflower oil, cocoa mass, cocoa butter, fat reduced cocoa, milk fat, lactose and protein from whey (from milk), whey powder (from milk), palm fat, barley malt extract, emulsifier (soya lecithin), salt, egg white powder, milk protein, natural vanilla extract. (May contain: peanut). Milk chocolate contains milk solids 14% minimum","additive_flags":"Clean"},
    {"barcode":"8906010360085","product_name":"Ghee","brands":"GRB","ingredients_text":"Milk fat","additive_flags":"Clean single-ingredient"},
    {"barcode":"5449000294791","product_name":"Schwarzer Tee Pfirsich- & Holunderblütengeschmack Ohne Zucker (FuzeTea)","brands":"Coca-Cola","ingredients_text":"Gebrühter Schwarztee 98.5% (Wasser, konzentrierter Schwarztee-Aufguss), Pfirsichsaft aus Pfirsichsaftkonzentrat (1%), Säuerungsmittel (Citronensäure, Apfelsäure), Säureregulatoren (Natriumcitrate, Natriumgluconat), natürliches Pfirsich- und Holunderblütenaroma mit anderen natürlichen Aromen, Antioxidationsmittel Ascorbinsäure, Süßungsmittel (Sucralose, Steviolglycoside aus Stevia), Holunderblütenextrakt, 0% Zucker","additive_flags":"Clean"}
]

elevated_count = 0
added_count = 0
purged_count = 0

for item in batch_36_rows:
    barcode = str(item["barcode"]).strip()
    pname = item["product_name"].strip()
    brand = item["brands"].strip()
    ing = item["ingredients_text"].strip()
    flags = item.get("additive_flags", "")
    
    # Check if non-food
    if "NON-FOOD" in ing.upper() or "NON-FOOD" in flags.upper() or "PURGE" in flags.upper():
        df_all = df_all[df_all['barcode'] != barcode]
        df_confirmed = df_confirmed[df_confirmed['barcode'] != barcode]
        df_needs_ver = df_needs_ver[df_needs_ver['barcode'] != barcode]
        purged_count += 1
        continue

    # Update or add in master DB
    idx_all = df_all[df_all['barcode'] == barcode].index
    status_tag = 'CONFIRMED_INDIA_890' if barcode.startswith('890') else 'CONFIRMED_FOREIGN'
    if len(idx_all) > 0:
        df_all.loc[idx_all, 'product_name'] = pname
        df_all.loc[idx_all, 'brands'] = brand
        df_all.loc[idx_all, 'ingredients_text'] = ing
    else:
        new_row = {
            'barcode': barcode,
            'product_name': pname,
            'brands': brand,
            'ingredients_text': ing,
            'sold_in_india_status': status_tag,
            'ingredient_confidence': 'HIGH',
            'status': 'KEEP',
            'data_source': 'Brand Official Publication',
            'source_license': 'User-submitted',
            'collection_method': 'API/CSV Import'
        }
        df_all = pd.concat([df_all, pd.DataFrame([new_row])], ignore_index=True)

    # Check if in needs_ver, promote to confirmed
    idx_nv = df_needs_ver[df_needs_ver['barcode'] == barcode].index
    if len(idx_nv) > 0:
        df_needs_ver = df_needs_ver[df_needs_ver['barcode'] != barcode]
        elevated_count += 1

    # Upsert in confirmed
    idx_c = df_confirmed[df_confirmed['barcode'] == barcode].index
    if len(idx_c) > 0:
        df_confirmed.loc[idx_c, 'product_name'] = pname
        df_confirmed.loc[idx_c, 'brands'] = brand
        df_confirmed.loc[idx_c, 'ingredients_text'] = ing
        df_confirmed.loc[idx_c, 'sold_in_india_status'] = status_tag
        df_confirmed.loc[idx_c, 'ingredient_confidence'] = 'HIGH'
        df_confirmed.loc[idx_c, 'status'] = 'KEEP'
    else:
        conf_row = {
            'barcode': barcode,
            'product_name': pname,
            'brands': brand,
            'ingredients_text': ing,
            'sold_in_india_status': status_tag,
            'ingredient_confidence': 'HIGH',
            'status': 'KEEP',
            'data_source': 'Brand Official Publication',
            'source_license': 'User-submitted',
            'collection_method': 'API/CSV Import'
        }
        df_confirmed = pd.concat([df_confirmed, pd.DataFrame([conf_row])], ignore_index=True)
        added_count += 1

# Save updated files
df_all.to_csv(all_supabase_csv, index=False)
df_confirmed.to_csv(confirmed_csv, index=False)
df_needs_ver.to_csv(needs_ver_csv, index=False)

print(f"Batch 36 Processing Summary:")
print(f"  Elevated from Needs Verification to Confirmed: {elevated_count}")
print(f"  Newly added to Confirmed: {added_count}")
print(f"  Purged Non-Food Barcodes: {purged_count}")
print(f"  Final Master CSV Count: {len(df_all)}")
print(f"  Final Confirmed CSV Count: {len(df_confirmed)}")
print(f"  Final Needs Verification CSV Count: {len(df_needs_ver)}")
