import os
import sys
import pandas as pd

sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = r"c:\Users\thout\Downloads\check it"

all_supabase_csv = os.path.join(BASE_DIR, "all_supabase_products.csv")
confirmed_csv = os.path.join(BASE_DIR, "india_products_confirmed.csv")
needs_ver_csv = os.path.join(BASE_DIR, "india_products_needs_verification.csv")

print("=== EXECUTING BATCH 42 INGREDIENTS INTEGRATION & PURGE ===")

df_all = pd.read_csv(all_supabase_csv, dtype=str)
df_confirmed = pd.read_csv(confirmed_csv, dtype=str) if os.path.exists(confirmed_csv) else pd.DataFrame()
df_needs_ver = pd.read_csv(needs_ver_csv, dtype=str) if os.path.exists(needs_ver_csv) else pd.DataFrame()

for df in [df_all, df_confirmed, df_needs_ver]:
    if not df.empty and 'barcode' in df.columns:
        df['barcode'] = df['barcode'].astype(str).str.strip()

batch_42_rows = [
    {"barcode":"8906045636278","product_name":"Revital","brands":"Complément Alimentaire","ingredients_text":"NON-FOOD — Supplement","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901277018939","product_name":"Park Avenue Cool Blue","brands":"Park Avenue","ingredients_text":"NON-FOOD — Personal care product","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8904132919679","product_name":"Freshener Orchid Bloom","brands":"My Home","ingredients_text":"NON-FOOD — Air freshener","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8904132919709","product_name":"Freshener Lavender Trail","brands":"My Home","ingredients_text":"NON-FOOD — Air freshener","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901725111441","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8906080602832","product_name":"Swing Lush Lychee","brands":"Paper Boat","ingredients_text":"Water, lychee pulp, sugar, acidity regulators","additive_flags":"Clean"},
    {"barcode":"8904132948174","product_name":"Campa Cola 500ml","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulator (INS 338), colour (INS 150d), natural cola flavour, caffeine","additive_flags":"INS 150d + Caffeine"},
    {"barcode":"8904132948273","product_name":"Potato Chips","brands":"Alan's","ingredients_text":"Potato, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8909106018372","product_name":"Boost","brands":"HUL","ingredients_text":"Cereal extract (50%), malted barley (21%), sugar, wheat flour, milk solids (6%), minerals, natural colour (INS 150c), vitamins","additive_flags":"INS 150c Caramel"},
    {"barcode":"8902901224818","product_name":"Urad Dal Chhilka","brands":"Good Life","ingredients_text":"Urad dal with skin (whole)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901058016222","product_name":"Maggi Rich Tomato Ketchup","brands":"Maggi","ingredients_text":"Tomato paste, sugar, water, vinegar, salt, spices, acidity regulator (INS 260), preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901023019371","product_name":"Rat Glue Pad","brands":"HIT","ingredients_text":"NON-FOOD — Pest control product","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901192104229","product_name":"Catch Coriander 200g","brands":"Catch","ingredients_text":"Coriander powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904053502462","product_name":"Goldiee Red Chilli 200g","brands":"Goldiee","ingredients_text":"Red chilli powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902901222456","product_name":"Cardamom","brands":"Various","ingredients_text":"Cardamom (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906040251711","product_name":"Dates","brands":"Various","ingredients_text":"Dates (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8903241110793","product_name":"Pravin","brands":"Suhana","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"89080658","product_name":"Maggi","brands":"Maggi","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901786530120","product_name":"Food","brands":"Unknown Brand","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8908007380717","product_name":"Amar Lassi","brands":"Amar","ingredients_text":"Toned milk, sugar, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8901544064430","product_name":"Date","brands":"Various","ingredients_text":"Dates (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908000258211","product_name":"Jivo Olive Oil","brands":"Jivo","ingredients_text":"Olive oil (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902710508697","product_name":"Choco","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901542003035","product_name":"Complan","brands":"Complan","ingredients_text":"Milk solids (52%), sugar, peanut oil, maltodextrin, almonds, minerals, vitamins, colours (INS 100(i), INS 160b(ii))","additive_flags":"Natural colours"},
    {"barcode":"8901764042324","product_name":"Thums Up Charged","brands":"Coca-Cola","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 338, INS 330), caffeine, taurine, colour (INS 150d), natural cola flavour, vitamins","additive_flags":"INS 150d + Caffeine"},
    {"barcode":"8901764051258","product_name":"Limca","brands":"Limca","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(i)), stabilizers (INS 414, INS 471), preservative (INS 211), lime-lemon flavouring","additive_flags":"INS 211 preservative"},
    {"barcode":"8901764052408","product_name":"Limca 2L","brands":"Coca-Cola","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(i)), stabilizers (INS 414, INS 471), preservative (INS 211), lime-lemon flavouring","additive_flags":"INS 211 preservative"},
    {"barcode":"8908000589872","product_name":"Bindu Fizza Jeera","brands":"Bindu","ingredients_text":"Carbonated water, sugar, cumin flavour, acidity regulators, salt, preservative","additive_flags":"Clean"},
    {"barcode":"8904132975774","product_name":"Campa Power Up","brands":"Campa","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8906108895178","product_name":"Desi Popz","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8904132975552","product_name":"Campa Soda","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulators, flavours","additive_flags":"Clean"},
    {"barcode":"8904132975552","product_name":"Campa Soda","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulators, flavours","additive_flags":"Clean"},
    {"barcode":"8904132975552","product_name":"Campa Soda","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulators, flavours","additive_flags":"Clean"},
    {"barcode":"8904132975552","product_name":"Campa Soda","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulators, flavours","additive_flags":"Clean"},
    {"barcode":"8904132975552","product_name":"Campa Soda","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulators, flavours","additive_flags":"Clean"},
    {"barcode":"8904132975552","product_name":"Campa Soda","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulators, flavours","additive_flags":"Clean"},
    {"barcode":"8904132949737","product_name":"Campa O","brands":"Campa","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8906131680512","product_name":"Date Powder","brands":"Slurrp Farm","ingredients_text":"Date powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908008818721","product_name":"Gingelly Oil","brands":"Various","ingredients_text":"Sesame oil (gingelly) (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906015741452","product_name":"Orange Jam","brands":"Various","ingredients_text":"Sugar, orange pulp, acidity regulator (INS 330), preservative (INS 211), colour (INS 122)","additive_flags":"INS 122 + INS 211"},
    {"barcode":"8904406393297","product_name":"Manha Soan Papdi","brands":"Manha","ingredients_text":"Sugar, gram flour, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8901148251830","product_name":"Zedex","brands":"Various","ingredients_text":"NON-FOOD — Medicine","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8908000863460","product_name":"Oleev Active","brands":"Oleev","ingredients_text":"Rice bran oil, olive oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8901531700327","product_name":"Suthol","brands":"Various","ingredients_text":"NON-FOOD — Medicine","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901207050374","product_name":"Real Frutors","brands":"Real","ingredients_text":"Water, fruit juice concentrate, sugar, acidity regulator (INS 330), antioxidant (INS 300), flavours","additive_flags":"Clean"},
    {"barcode":"8904132965768","product_name":"Lobia Red","brands":"Simply Smart","ingredients_text":"Red cowpeas (lobia)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904132965836","product_name":"Rajma Sharmili","brands":"Simply Smart","ingredients_text":"Rajma (kidney beans)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904132965720","product_name":"Chat Chana","brands":"Simply Smart","ingredients_text":"Chickpeas, spices, salt","additive_flags":"Clean"},
    {"barcode":"8906167310742","product_name":"Moong Dal Small","brands":"Mark Premium","ingredients_text":"Moong dal (green gram)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901512102805","product_name":"Sundrop Super Lite Advanced","brands":"Sundrop","ingredients_text":"Refined sunflower oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8906009220598","product_name":"Nutrifud Rich Milk Milk Cake","brands":"Nutrifud","ingredients_text":"Milk solids, sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906414000914","product_name":"Sok Smaki Victorii Czerwony Burak 250","brands":"Various","ingredients_text":"Beetroot juice","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906157900571","product_name":"Sun Scoop","brands":"Sun Scoop","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8906006855472","product_name":"Doublet Bar Choco Fudge","brands":"Baskin Robbins","ingredients_text":"Toned milk, sugar, cocoa solids, edible vegetable oil, stabilizers, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906097590238","product_name":"Reload Electrolytes","brands":"Fast&Up","ingredients_text":"Electrolytes (sodium, potassium, magnesium), vitamins, flavours","additive_flags":"Supplement"},
    {"barcode":"8901484013895","product_name":"Vinegar","brands":"Various","ingredients_text":"Vinegar (acetic acid, water)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901725004576","product_name":"Bingo Hashtags","brands":"Bingo","ingredients_text":"Corn grits, edible vegetable oil, rice grits, gram flour, spices, salt, sugar, flavour enhancers (INS 621, INS 627, INS 631), colours (INS 160c)","additive_flags":"INS 621 MSG + INS 160c"},
    {"barcode":"8901719129582","product_name":"Parle Fultoss Baked","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901512557308","product_name":"Act Nachoz Cheese","brands":"Act II","ingredients_text":"Corn flour, edible vegetable oil, cheese powder, salt, spices, flavour enhancers","additive_flags":"Clean"},
    {"barcode":"8901719129575","product_name":"Parle Fultoss Baked","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901117283497","product_name":"Skoodle Drawing","brands":"Various","ingredients_text":"NON-FOOD — Stationery","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8902268013261","product_name":"Anmol Hit & Run Choco Chip Cookies","brands":"Anmol","ingredients_text":"Refined wheat flour, sugar, chocolate chips, edible vegetable oil, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901537076938","product_name":"Every Day Bamti Rice 5kg","brands":"Various","ingredients_text":"Basmati rice (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904132948860","product_name":"Ind Tibar Bamti 5kg","brands":"Various","ingredients_text":"Basmati rice (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901725019419","product_name":"Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725000646","product_name":"Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8902901222357","product_name":"Phool Makhana","brands":"Good Life","ingredients_text":"Makhana (fox nuts)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901155301443","product_name":"Gits Gulabi Jamun","brands":"Gits","ingredients_text":"Milk solids, sugar, edible vegetable oil, cardamom, rose water","additive_flags":"Clean"},
    {"barcode":"8904198801116","product_name":"Getmore Tingling Tomato","brands":"Unknown Brand","ingredients_text":"Potato, edible vegetable oil, tomato seasoning, salt, spices, flavour enhancers","additive_flags":"Clean"},
    {"barcode":"8901155304321","product_name":"Soan Papdi","brands":"Gits","ingredients_text":"Sugar, gram flour, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906022573886","product_name":"Moong Dal","brands":"Angur","ingredients_text":"Moong dal (green gram)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906112994607","product_name":"High Protein Madras Mix","brands":"Lo Foods/Protein Chef","ingredients_text":"Multigrain blend, whey protein, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8901648001775","product_name":"Lassi","brands":"Mother Dairy","ingredients_text":"Toned milk, sugar, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8901192215116","product_name":"Catch Sabzi Masala","brands":"Catch","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom","additive_flags":"Clean spice blend"},
    {"barcode":"8906006723023","product_name":"Dates Jam with Mango","brands":"Various","ingredients_text":"Dates, mango pulp, sugar, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8902042212583","product_name":"Gold Cup","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8908811489552","product_name":"Basmati Riz","brands":"Milan Food","ingredients_text":"Basmati rice (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"89085967","product_name":"Gamberi Croccanti","brands":"Bofrost","ingredients_text":"Shrimp, breadcrumbs, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8906019350254","product_name":"Amalas","brands":"Various","ingredients_text":"Indian gooseberry (amla), sugar","additive_flags":"Clean"},
    {"barcode":"8906035141522","product_name":"Chipo Gathiya","brands":"Chipo","ingredients_text":"Gram flour, edible vegetable oil, iodized salt, spices","additive_flags":"Clean"},
    {"barcode":"8904132949751","product_name":"Campa Cola 1L","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulator (INS 338), colour (INS 150d), natural cola flavour, caffeine","additive_flags":"INS 150d + Caffeine"},
    {"barcode":"8904132949775","product_name":"Campa Lemon Flv 1L","brands":"Reliance","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(i)), lime-lemon flavouring, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8904132949799","product_name":"Campa Orange Flv 1L","brands":"Reliance","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(iii)), orange juice concentrate, colours (INS 110, INS 102), artificial orange flavour, preservative (INS 211)","additive_flags":"INS 110 + INS 102"},
    {"barcode":"8906013183223","product_name":"Dr. Vaidyas Plant Protein Chocolate","brands":"Dr. Vaidyas","ingredients_text":"Plant protein blend, cocoa solids, sugar, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901414026421","product_name":"Besan Burfi","brands":"Bikano","ingredients_text":"Gram flour (besan), sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906002660704","product_name":"Coconad Edible Coconut Oil","brands":"KLF","ingredients_text":"Coconut oil (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901393017212","product_name":"Sour Belt","brands":"Chupa Chups","ingredients_text":"Sugar, glucose syrup, edible vegetable oil, sour flavour, acidity regulator, colours","additive_flags":"Verify colours"},
    {"barcode":"8901725016890","product_name":"B Natural Chatpata Jamun Juice","brands":"B Natural","ingredients_text":"Water, jamun juice concentrate, sugar, acidity regulator (INS 330), antioxidant (INS 300), flavours","additive_flags":"Clean"},
    {"barcode":"8901888007780","product_name":"Real Mixed Fruit Juice 180ml","brands":"Real","ingredients_text":"Water, mixed fruit juice concentrate, sugar, acidity regulator (INS 330), antioxidant (INS 300)","additive_flags":"Clean"},
    {"barcode":"8906080600784","product_name":"Paper Boat Delicious Low Sugar Anar","brands":"Paper Boat","ingredients_text":"Water, pomegranate pulp, sugar (low), acidity regulators","additive_flags":"Clean"},
    {"barcode":"8908001705196","product_name":"Paper Boat Jaljeera Drinks 200ml","brands":"Paper Boat","ingredients_text":"Water, jaggery, cumin, mint, spices, salt, acidity regulators","additive_flags":"Clean"},
    {"barcode":"8908001705806","product_name":"Paper Boat Chilli Guava","brands":"Paper Boat","ingredients_text":"Water, guava pulp, sugar, chilli, acidity regulators","additive_flags":"Clean"},
    {"barcode":"8906133401375","product_name":"Little Joys NutriMix Nutrition","brands":"Little Joys","ingredients_text":"Multigrain blend, milk solids, sugar, minerals, vitamins","additive_flags":"Clean"},
    {"barcode":"8906144491808","product_name":"Cold Coffee","brands":"Sleepy Owl","ingredients_text":"Instant coffee, milk solids, sugar, cocoa solids, emulsifier","additive_flags":"Clean"},
    {"barcode":"8904132902268","product_name":"Raskik Nimbu Pani","brands":"Raskik","ingredients_text":"Water, sugar, lemon juice, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8908003058245","product_name":"Satvik Foods Roasted Pumpkin Seed","brands":"Satvik Foods","ingredients_text":"Roasted pumpkin seeds, iodized salt","additive_flags":"Clean"},
    {"barcode":"8904063226587","product_name":"Mexilla Sweet Thai Chilli","brands":"Haldiram's","ingredients_text":"Corn flour, edible vegetable oil, sweet thai chilli seasoning, salt, spices, flavour enhancers (INS 621)","additive_flags":"INS 621 MSG"},
    {"barcode":"8901777467176","product_name":"Junglee Paneer Jumbo Grilled Sandwich","brands":"Vadilal","ingredients_text":"Refined wheat flour, paneer, vegetables, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901052008827","product_name":"Tetly Green Tea","brands":"Various","ingredients_text":"Green tea (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906082760493","product_name":"Guava Pulp","brands":"Various","ingredients_text":"Guava pulp (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906074087959","product_name":"Milagu Kuzhambu","brands":"Aswins Sweets & Snacks","ingredients_text":"Black pepper, tamarind, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901063093713","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8908019996005","product_name":"Kulith Pithi","brands":"Various","ingredients_text":"Horse gram flour (kulith)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906021920933","product_name":"Apis Honey","brands":"Apis","ingredients_text":"Organic honey (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908025722056","product_name":"Bharat Dal Chana Whole","brands":"Bharat Dal","ingredients_text":"Chana (chickpeas)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8903023013281","product_name":"More Choice Zahidi Dates","brands":"More Choice","ingredients_text":"Dates (Zahidi) (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904145954384","product_name":"Abbott Product","brands":"Abbott","ingredients_text":"NON-FOOD — Medicine/supplement","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8906151234498","product_name":"Baked Pizza Sticks","brands":"Snackible","ingredients_text":"Refined wheat flour, cheese, tomato sauce, vegetables, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8908003249834","product_name":"Organic Plain Buttermilk","brands":"Akshayakalpa Organic","ingredients_text":"Organic toned milk, water, salt, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8906104590329","product_name":"High Protein Paneer","brands":"Farm Connect","ingredients_text":"Milk solids, citric acid (coagulant)","additive_flags":"Clean"},
    {"barcode":"8901725018764","product_name":"Hot & Spicy Korean Style","brands":"Bingo","ingredients_text":"Corn grits, edible vegetable oil, rice grits, gram flour, Korean seasoning, spices, salt, sugar, flavour enhancers (INS 621), colours (INS 160c)","additive_flags":"INS 621 MSG + INS 160c"},
    {"barcode":"8906088541454","product_name":"Chicken 65","brands":"Nandus","ingredients_text":"Chicken, spices, salt, edible vegetable oil, refined wheat flour","additive_flags":"Clean"},
    {"barcode":"8901648095163","product_name":"Nandini Goodlife Skimmed","brands":"Nandini","ingredients_text":"Skimmed milk, vitamins A & D","additive_flags":"Clean"},
    {"barcode":"8906107173635","product_name":"Pizza Minis Loaded Chicken","brands":"Prasuma","ingredients_text":"Refined wheat flour, chicken, cheese, tomato sauce, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8901023018244","product_name":"Air Matic Violet Valley Bloom","brands":"Godrej","ingredients_text":"NON-FOOD — Air freshener","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901834001206","product_name":"Maaza","brands":"Coca-Cola","ingredients_text":"Water, mango pulp, sugar, acidity regulator (INS 330), antioxidant (INS 300)","additive_flags":"Clean"},
    {"barcode":"8902080305025","product_name":"7Up 250ml Can","brands":"PepsiCo","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(i)), natural lemon-lime flavouring, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8906035140686","product_name":"Chipo","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901207043239","product_name":"Real Guava Sip & Win","brands":"Real","ingredients_text":"Water, guava juice concentrate, sugar, acidity regulator (INS 330), antioxidant (INS 300)","additive_flags":"Clean"},
    {"barcode":"8904132952645","product_name":"Campa Orange 2L","brands":"Campa","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(iii)), orange juice concentrate, colours (INS 110, INS 102), artificial orange flavour, preservative (INS 211)","additive_flags":"INS 110 + INS 102"},
    {"barcode":"8901440206309","product_name":"Eastern Chilli Chicken Masala","brands":"Eastern","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, garlic, ginger, salt","additive_flags":"Clean spice blend"},
    {"barcode":"8901063092754","product_name":"Good Day Fruit & Nut","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, dried fruits, nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8906070060192","product_name":"Corn Mixture","brands":"Sharva's Snacks","ingredients_text":"Corn flakes, edible vegetable oil, peanuts, sago, salt, spices, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904002500570","product_name":"Badam Milk","brands":"MASQATI","ingredients_text":"Milk, almonds, sugar, cardamom","additive_flags":"Clean"},
    {"barcode":"8904113522003","product_name":"Agro Fresh Jaggery","brands":"Agro Fresh","ingredients_text":"Jaggery (gur)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908000137035","product_name":"Peanut Chikki","brands":"BMS Sweets","ingredients_text":"Peanuts, jaggery, glucose syrup","additive_flags":"Clean"},
    {"barcode":"8906050591852","product_name":"Banjaras","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8906005670427","product_name":"Salted Peanuts","brands":"Charliee","ingredients_text":"Roasted peanuts, iodized salt","additive_flags":"Clean"},
    {"barcode":"8908003714042","product_name":"Mysore Pak Konaka FOODS","brands":"Konaka","ingredients_text":"Gram flour, sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906020495081","product_name":"Ghee Laddoo","brands":"Various","ingredients_text":"Gram flour, sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906020490482","product_name":"Boondi Laddoo","brands":"Various","ingredients_text":"Gram flour, sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8901042960340","product_name":"Rasogolla","brands":"Various","ingredients_text":"Milk solids (chenna), sugar, cardamom","additive_flags":"Clean"},
    {"barcode":"8906108191334","product_name":"Farm Fresh Classic Eggs Pack Of 12","brands":"Licious","ingredients_text":"Eggs (12)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904459600335","product_name":"Kodo Millet Noodles","brands":"Satvyk","ingredients_text":"Kodo millet flour, salt","additive_flags":"Clean"},
    {"barcode":"8908004415443","product_name":"Orbix S","brands":"Various","ingredients_text":"NON-FOOD — Verify","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8908004415535","product_name":"Orbix L","brands":"Various","ingredients_text":"NON-FOOD — Verify","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8904063226563","product_name":"Mexilla Flamin' Hot Tortilla Chips","brands":"Haldiram's","ingredients_text":"Corn flour, edible vegetable oil, spices, salt, flavour enhancers (INS 621), colours (INS 160c)","additive_flags":"INS 621 MSG"},
    {"barcode":"8908015450075","product_name":"Steel Cut Oats","brands":"WeFeasto","ingredients_text":"Steel cut oats (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902979011532","product_name":"KESAR FLAVOURED MILK","brands":"Cavin's","ingredients_text":"Toned milk, sugar, kesar (saffron) flavour, stabilizers, emulsifiers, colour (INS 160a)","additive_flags":"Clean"},
    {"barcode":"8901725013387","product_name":"Chocolate Meltz","brands":"Dark Fantasy","ingredients_text":"Choco crème (sugar, refined palmolein, cocoa solids), refined wheat flour, sugar, invert syrup, liquid glucose, cocoa solids, milk solids, butter, raising agents, emulsifiers, salt","additive_flags":"Clean"},
    {"barcode":"8906043348104","product_name":"Salt Electrolytes","brands":"Supply 6","ingredients_text":"Electrolyte salts (sodium, potassium, magnesium)","additive_flags":"Clean"},
    {"barcode":"8906169990430","product_name":"Kerala Tapioca Chips","brands":"Sweet Karam Coffee","ingredients_text":"Tapioca, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8906083020459","product_name":"Assorted Nutri Bar","brands":"Mindful","ingredients_text":"Multigrain blend, nuts, dried fruits, honey, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8908000391482","product_name":"Wheafree","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8906021061650","product_name":"Molsis Zahidi Dates","brands":"Bolas Agro","ingredients_text":"Wet dates (Zahidi) (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902080304059","product_name":"7Up Super Duper 750ml","brands":"PepsiCo","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(i)), natural lemon-lime flavouring, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901491503013","product_name":"Yellow Salted Lays","brands":"Lay's","ingredients_text":"Potato, edible vegetable oil (palmolein, rice bran oil), iodized salt","additive_flags":"Clean"},
    {"barcode":"8902579001285","product_name":"Frooti Mix Fruit","brands":"Various","ingredients_text":"Water, mixed fruit juice concentrate, sugar, acidity regulator, flavours","additive_flags":"Clean"},
    {"barcode":"8901262070058","product_name":"Amul Fruit 'N' Nut","brands":"Amul","ingredients_text":"Cocoa solids, sugar, cocoa butter, almonds (8%), raisins (5%), emulsifiers (322,476), artificial flavouring substances (cocoa, vanilla)","additive_flags":"Clean"},
    {"barcode":"8000500348208","product_name":"Moments","brands":"Ferrero/Ferrero Rocher","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8850718809011","product_name":"Crisps Plain","brands":"Lay's","ingredients_text":"Potatoes, vegetable oil, salt","additive_flags":"Clean"},
    {"barcode":"3034580606991","product_name":"Unknown","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8850534118267","product_name":"Unknown","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"7046122277183","product_name":"Unknown","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"0712345678904","product_name":"Farb","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"7613035281783","product_name":"Nestle Pure Life Still Spring Water","brands":"Nestlé","ingredients_text":"Water","additive_flags":"Clean single-ingredient"},
    {"barcode":"8710398500472","product_name":"Chips","brands":"Lay's/Pepsico","ingredients_text":"Potatoes, vegetable oil, salt","additive_flags":"Clean"},
    {"barcode":"8901063164321","product_name":"Tiger Kreemz Orange","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, invert syrup, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8901063162549","product_name":"Marie Gold","brands":"Britannia","ingredients_text":"Refined wheat flour (73%), sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers (INS 471, INS 322)","additive_flags":"Clean"},
    {"barcode":"8902268011144","product_name":"Dream Lite","brands":"Anmol","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901052011742","product_name":"Rusk","brands":"Tata SoulFull","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, milk solids, raising agents, emulsifier, artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8904344626228","product_name":"Moon Original","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8904258703879","product_name":"ABC Juice","brands":"Raw Pressed","ingredients_text":"Apple, beetroot, carrot juice blend","additive_flags":"Clean"},
    {"barcode":"8904270005401","product_name":"Marie Go Round","brands":"Sunder","ingredients_text":"Refined wheat flour, sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901448904054","product_name":"Wafy Break","brands":"Various","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, flavours, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906021927062","product_name":"Apis Deseeded Dates","brands":"Apis","ingredients_text":"Deseeded dates (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8903023007709","product_name":"More Chironji","brands":"More","ingredients_text":"Chironji (charoli seeds)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901725003838","product_name":"Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906097402562","product_name":"Zoff Clove Whole","brands":"Zoff","ingredients_text":"Whole cloves (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906002348473","product_name":"Lobia Safed","brands":"Rajdhani","ingredients_text":"White cowpeas (lobia)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902901222517","product_name":"Ajwain","brands":"Good Life","ingredients_text":"Ajwain (carom seeds)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906006525504","product_name":"Top Start","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901063371026","product_name":"Marie Gold","brands":"Britannia","ingredients_text":"Refined wheat flour (73%), sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers (INS 471, INS 322)","additive_flags":"Clean"},
    {"barcode":"8901058866216","product_name":"Coffee Mocha","brands":"Nestlé","ingredients_text":"Instant coffee, sugar, milk solids, cocoa solids, emulsifier, flavours","additive_flags":"Clean"},
    {"barcode":"8901552007689","product_name":"Kantola","brands":"Ashoka","ingredients_text":"Refined wheat flour, potato, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901719255144","product_name":"Parle-G","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, invert syrup, refined palm oil, salt, skimmed milk powder, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 471), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901719404412","product_name":"Hide & Seek","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cocoa solids, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901719703034","product_name":"Krack Jack Original","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, salt, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8904188607933","product_name":"Green Chana Frozen","brands":"Saurbhi","ingredients_text":"Green chickpeas (frozen)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904340700397","product_name":"Pulse Litchi Flavour","brands":"Pass Pass","ingredients_text":"Sugar, glucose syrup, lychee flavour, acidity regulator, colours","additive_flags":"Verify colours"},
    {"barcode":"8904340700359","product_name":"Pulse Orange","brands":"Pass Pass","ingredients_text":"Sugar, glucose syrup, orange flavour, acidity regulator, colours","additive_flags":"Verify colours"},
    {"barcode":"8906172543807","product_name":"Black Forest","brands":"Hocco","ingredients_text":"Refined wheat flour, sugar, eggs, cocoa solids, edible vegetable oil, raising agents, emulsifiers, cherry flavour, colours","additive_flags":"Clean"},
    {"barcode":"8909081003905","product_name":"Rich Chocolate Cookies","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, cocoa solids, edible vegetable oil, invert syrup, raising agents, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8906001024798","product_name":"Four Cheese","brands":"Go","ingredients_text":"Milk solids, salt, emulsifying salts, preservative (INS 200), cheese blend","additive_flags":"INS 200 preservative"},
    {"barcode":"8903605017706","product_name":"Soy Sauce","brands":"Various","ingredients_text":"Water, soybean extract, salt, sugar, vinegar, acidity regulator, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8906010504021","product_name":"Balaji Wafers","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8906010504007","product_name":"Balaji Wafers","brands":"Balaji","ingredients_text":"Potato, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8901719656613","product_name":"Parle Hide & Seek Fab Orange","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, cocoa solids, invert syrup, milk solids, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8906024450512","product_name":"Green Tea Natural","brands":"Various","ingredients_text":"Green tea (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906024451335","product_name":"Green Tea Lemon and Honey","brands":"Various","ingredients_text":"Green tea, lemon flavour, honey","additive_flags":"Clean"},
    {"barcode":"8901030456381","product_name":"Taaza Tea","brands":"Brooke Bond","ingredients_text":"100% black tea (CTC blend)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901719124402","product_name":"Magix Orange","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, invert syrup, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8901719122040","product_name":"Coconut","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, coconut, edible vegetable oil, invert syrup, raising agents, emulsifier, artificial coconut flavour","additive_flags":"Clean"},
    {"barcode":"8901719124396","product_name":"Magix Elaichi","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cardamom flavour, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8904006313367","product_name":"Oura","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901030825552","product_name":"Protein Plus","brands":"Horlicks","ingredients_text":"Milk solids, malted cereals, sugar, cocoa solids, wheat flour, minerals, vitamins, emulsifier (INS 471)","additive_flags":"Clean"},
    {"barcode":"8904132926806","product_name":"Good Life Besan","brands":"Good Life","ingredients_text":"Gram flour (besan)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908003746708","product_name":"ORS Lemon Drink","brands":"Electrorush","ingredients_text":"Glucose, sodium chloride, potassium chloride, sodium citrate, lemon flavour","additive_flags":"ORS — Regulated"},
    {"barcode":"8901719130724","product_name":"Parle 20-20 Gold","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, invert syrup, milk solids, raising agents (INS 503(ii), INS 500(ii)), emulsifier (INS 322)","additive_flags":"Clean"},
    {"barcode":"8904300201018","product_name":"Coconut Crunchy","brands":"Various","ingredients_text":"Refined wheat flour, sugar, coconut, edible vegetable oil, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725013004","product_name":"Marie Light Family Pack","brands":"Sunfeast/ITC","ingredients_text":"Refined wheat flour, sugar, refined palm oil, invert sugar syrup, milk solids, raising agents, salt, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906009073729","product_name":"Big & Bold Fruit Blast","brands":"Unibic","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, dried fruits, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901725000622","product_name":"Sunfeast Mom's Magic","brands":"Sunfeast","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, cashew nuts, almonds, invert syrup, milk solids, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906097400179","product_name":"Coriander Powder","brands":"Zoff","ingredients_text":"Coriander powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908009186461","product_name":"Sport Evolve Performance Plant Protein Tropical Mango","brands":"Plix","ingredients_text":"Plant protein blend (pea, rice, soy), tropical mango flavour, sweetener (stevia), emulsifier","additive_flags":"Clean"},
    {"barcode":"8901117250000","product_name":"Prolyte ORS Orange Flavour","brands":"Cipla Health","ingredients_text":"Glucose, sodium chloride, potassium chloride, sodium citrate, orange flavour","additive_flags":"ORS — Regulated"},
    {"barcode":"8901721002934","product_name":"Prabhuji Rosogolla","brands":"Prabhuji","ingredients_text":"Milk solids (chenna), sugar, cardamom","additive_flags":"Clean"},
    {"barcode":"8903023305591","product_name":"Suraj Snakes Masala Muri","brands":"Suraj","ingredients_text":"Rice flakes, gram flour, edible vegetable oil, peanuts, sago, salt, spices, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8908000295285","product_name":"Mukharochak Nimki","brands":"Mukharochak","ingredients_text":"Refined wheat flour, edible vegetable oil, salt, spices, raising agents","additive_flags":"Clean"},
    {"barcode":"8908000295063","product_name":"Mukharochak Salty","brands":"Mukharochak","ingredients_text":"Refined wheat flour, edible vegetable oil, salt, spices, raising agents","additive_flags":"Clean"},
    {"barcode":"8901512558503","product_name":"Act Movie Theatre Butter","brands":"Act II","ingredients_text":"Popcorn kernels, edible vegetable oil (palmolein), salt, butter flavour, colour (INS 160a)","additive_flags":"Clean"},
    {"barcode":"8901058001433","product_name":"Rich Tomato Ketchup","brands":"Maggi","ingredients_text":"Tomato paste, sugar, water, vinegar, salt, spices, acidity regulator (INS 260), preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8904193411600","product_name":"Grand Masters","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901030686726","product_name":"Mixed Fruit Jam","brands":"Kissan","ingredients_text":"Sugar, mixed fruit pulp blend, acidity regulator (INS 330), preservative (INS 211), permitted synthetic food colour (INS 122)","additive_flags":"INS 122 + INS 211"},
    {"barcode":"8902080000203","product_name":"Nimbooz","brands":"7Up","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(i)), natural lemon-lime flavouring, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8906015741506","product_name":"BCOOL Strawberry Jam","brands":"Various","ingredients_text":"Sugar, strawberry pulp, acidity regulator (INS 330), preservative (INS 211), colour (INS 122)","additive_flags":"INS 122 + INS 211"},
    {"barcode":"8901808000457","product_name":"Weikfield Jelly Crystals Mix Strawberry Flavoured","brands":"Weikfield","ingredients_text":"Sugar, gelatin, acidity regulator, strawberry flavour, colour (INS 122)","additive_flags":"INS 122 colour"},
    {"barcode":"8905507001845","product_name":"First Crop Urad Masala Papad","brands":"First Crop","ingredients_text":"Urad dal flour, salt, spices, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901719123979","product_name":"Krackjack 400","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, salt, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8905507000817","product_name":"FB Strawberry Jam 500","brands":"Various","ingredients_text":"Sugar, strawberry pulp, acidity regulator (INS 330), preservative (INS 211), colour (INS 122)","additive_flags":"INS 122 + INS 211"},
    {"barcode":"8901719124860","product_name":"Parle","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901052004652","product_name":"Tata Tea Premium","brands":"Tata Tea","ingredients_text":"100% black tea (CTC blend)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901063016859","product_name":"50-50 Sweet & Salty","brands":"Britannia","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, salt, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8905507002125","product_name":"Arhar Dal 2kg","brands":"First Crop","ingredients_text":"Arhar/Toor dal (pigeon pea)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8905507002248","product_name":"Chana Dal 1kg","brands":"First Crop","ingredients_text":"Chana dal (split chickpeas)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902080013302","product_name":"Tropicana Apple 1L","brands":"Tropicana","ingredients_text":"Water, apple juice concentrate, sugar, acidity regulator (INS 330), antioxidant (INS 300)","additive_flags":"Clean"},
    {"barcode":"8901088716581","product_name":"Saffola Gold 5L","brands":"Marico","ingredients_text":"Rice bran oil, sunflower oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8905507023885","product_name":"FC Masala Twisteez","brands":"First Crop","ingredients_text":"Refined wheat flour, edible vegetable oil, spices, salt, sugar, flavour enhancers","additive_flags":"Clean"},
    {"barcode":"8906004620287","product_name":"Mustard Oil","brands":"Dhara","ingredients_text":"Mustard oil (kachi ghani)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8905507002675","product_name":"PB Health Drink Classic 500","brands":"Various","ingredients_text":"Malted cereals, milk solids, sugar, minerals, vitamins","additive_flags":"Clean"},
    {"barcode":"8901719115608","product_name":"Hide & Seek 120g Sandwiches Orange","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, orange flavour, cocoa solids, invert syrup, milk solids, raising agents, emulsifiers, colours (INS 110)","additive_flags":"INS 110 colour"},
    {"barcode":"8902901225013","product_name":"Chana Brown Small","brands":"Good Life","ingredients_text":"Brown chickpeas (small)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906009071015","product_name":"Unibic Wafer Biscuit Rich Chocolate","brands":"Unibic","ingredients_text":"Refined wheat flour, sugar, cocoa solids, edible vegetable oil, raising agents, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8906009071022","product_name":"Unibic Wafer Yummy Strawberry","brands":"Unibic","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, strawberry flavour, raising agents, emulsifiers, colours","additive_flags":"Clean"},
    {"barcode":"8901491003186","product_name":"Quaker Oats","brands":"Quaker","ingredients_text":"Oats (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901721009995","product_name":"Prabhuji Chana Barfi","brands":"Prabhuji","ingredients_text":"Gram flour, sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8904132964129","product_name":"Masoor Malka","brands":"Various","ingredients_text":"Masoor malka (split red lentils)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906095126873","product_name":"Wonderland Dry Fruits Combi","brands":"Wonderland","ingredients_text":"Almonds, cashews, raisins, pistachios","additive_flags":"Clean"},
    {"barcode":"8906059638596","product_name":"Greek Yogurt Smoothie Strawberry","brands":"Epigamia","ingredients_text":"Pasteurized milk, strawberry, sugar, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8902080003075","product_name":"Nimbooz","brands":"7Up","ingredients_text":"Carbonated water, sugar, acidity regulators (INS 330, INS 331(i)), natural lemon-lime flavouring, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8901808004769","product_name":"Weikfield Falooda Rose","brands":"Weikfield","ingredients_text":"Sugar, rose flavour, basil seeds, vermicelli, colours","additive_flags":"Verify colours"},
    {"barcode":"8901808003069","product_name":"Jelly Raspberry","brands":"Weikfield","ingredients_text":"Sugar, gelatin, acidity regulator, raspberry flavour, colour","additive_flags":"Verify colours"},
    {"barcode":"8907065118683","product_name":"Puramate Vanilla Essence","brands":"Puramate","ingredients_text":"Water, alcohol, vanilla extract","additive_flags":"Clean"},
    {"barcode":"8904406102172","product_name":"Chocolate Brownie Fudge","brands":"Get A Way","ingredients_text":"Refined wheat flour, sugar, cocoa solids, eggs, edible vegetable oil, raising agents, emulsifiers, chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8901262202220","product_name":"Dahi Yogurt","brands":"Amul","ingredients_text":"Pasteurized toned milk, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8908006217915","product_name":"Millet","brands":"Slurrp Farm","ingredients_text":"Millet flour, raising agents, salt","additive_flags":"Clean"},
    {"barcode":"8909106022034","product_name":"Comfort Morning Fresh","brands":"HUL","ingredients_text":"NON-FOOD — Fabric softener","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8909106022041","product_name":"Comfort Lily Fresh","brands":"HUL","ingredients_text":"NON-FOOD — Fabric softener","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8909106022089","product_name":"Comfort Morning Liquid 2L","brands":"HUL","ingredients_text":"NON-FOOD — Fabric softener","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901781000772","product_name":"Sunrise Sambar Masala","brands":"Sunrise/ITC","ingredients_text":"Coriander, turmeric, red chilli, fenugreek, cumin, black pepper, mustard, curry leaves","additive_flags":"Clean spice blend"},
    {"barcode":"8901781000550","product_name":"Sunrise Biryani Masala","brands":"Sunrise/ITC","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom, bay leaf, nutmeg","additive_flags":"Clean spice blend"},
    {"barcode":"8906010090906","product_name":"DLacta Cheese","brands":"D'Lecta","ingredients_text":"Milk solids, salt, emulsifying salts, preservative (INS 200)","additive_flags":"INS 200 preservative"},
    {"barcode":"8904043926650","product_name":"Tata Sampann Masoor Whole","brands":"Tata Sampann","ingredients_text":"Masoor dal (whole red lentils)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901781000796","product_name":"Sunrise Shukto Masala","brands":"Sunrise/ITC","ingredients_text":"Spices blend for shukto (Bengali dish)","additive_flags":"Clean spice blend"},
    {"barcode":"8901781000802","product_name":"Sunrise Tadka Masala","brands":"Sunrise","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, garlic","additive_flags":"Clean spice blend"},
    {"barcode":"8901781000680","product_name":"Sunrise Meat Masala","brands":"Sunrise","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom, garlic, ginger","additive_flags":"Clean spice blend"},
    {"barcode":"8901781000628","product_name":"Sunrise Machher Jhol Masala","brands":"Sunrise","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, mustard, fenugreek","additive_flags":"Clean spice blend"},
    {"barcode":"8902319040932","product_name":"Orange Cool Flavour Orofer Xt","brands":"EMCURE","ingredients_text":"NON-FOOD — Medicine/supplement","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901088760454","product_name":"Saffola Oats","brands":"Saffola","ingredients_text":"Oats (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901058006032","product_name":"Maggi Cup Noodles","brands":"Maggi","ingredients_text":"Noodles: Refined wheat flour, palm oil, salt, wheat gluten, thickeners; Tastemaker: salt, spices, sugar, flavour enhancers (INS 621, INS 627, INS 631), antioxidant (INS 319)","additive_flags":"INS 621 + INS 319"},
    {"barcode":"8901063026346","product_name":"NutriChoice Digestive","brands":"Britannia","ingredients_text":"Whole wheat flour (71%), sugar, edible vegetable oil (palm), raising agents (INS 503(ii), INS 500(ii)), salt, emulsifiers (INS 471, INS 322), added vitamins & minerals","additive_flags":"Clean"},
    {"barcode":"8901725008888","product_name":"Aashirvaad Shudh Chakki Atta","brands":"ITC","ingredients_text":"100% whole wheat flour","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906038230834","product_name":"Chicken Malai Tikka","brands":"Zorabian","ingredients_text":"Chicken, cream, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901747005599","product_name":"Instant Saffron Tea","brands":"Wagh Bakri","ingredients_text":"Black tea, saffron, spices, sugar, milk solids","additive_flags":"Clean"},
    {"barcode":"8906108530543","product_name":"Inchi Noodles","brands":"Various","ingredients_text":"Refined wheat flour, palm oil, salt, thickeners; Tastemaker: salt, spices, flavour enhancers (INS 621)","additive_flags":"INS 621 MSG"},
    {"barcode":"8904209303455","product_name":"Coriander Thokku","brands":"Aachi","ingredients_text":"Coriander, salt, spices, edible vegetable oil, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8901542000775","product_name":"Nycil Powder","brands":"Nycil","ingredients_text":"NON-FOOD — Talcum powder","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8904180000688","product_name":"Tandoori Curry Paste","brands":"Vik's","ingredients_text":"Spices, salt, sugar, tomato powder, onion powder, garlic, ginger, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8906044653108","product_name":"Tomato Paste","brands":"Ahlan","ingredients_text":"Tomato paste, salt","additive_flags":"Clean"},
    {"barcode":"8906107173642","product_name":"Veg Supreme Pizza Minis","brands":"Prasuma","ingredients_text":"Refined wheat flour, cheese, tomato sauce, vegetables, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8906153880310","product_name":"Gulkand","brands":"Two Brothers Organic Farms","ingredients_text":"Rose petals, sugar","additive_flags":"Clean"},
    {"barcode":"8906029140944","product_name":"Cut Mango Pickle","brands":"Mambalam Iyers","ingredients_text":"Raw mango, salt, spices, edible vegetable oil, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8908013673216","product_name":"Spirit 750ml Old","brands":"Various","ingredients_text":"Alcoholic beverage","additive_flags":"ALCOHOL — SEPARATE"},
    {"barcode":"8904004420487","product_name":"MixTURE ENGALURU","brands":"Haldiram's","ingredients_text":"Rice flakes, gram flour, edible vegetable oil, peanuts, sago, salt, spices, raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904004420418","product_name":"Spicy Mixture","brands":"Haldiram's","ingredients_text":"Rice flakes, gram flour, edible vegetable oil, peanuts, sago, salt, spices, raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8901063094185","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901063094147","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901063092402","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8901063098657","product_name":"Good Day","brands":"Britannia","ingredients_text":"Refined wheat flour, edible vegetable oil, sugar, cashew nuts, invert syrup, milk solids, raising agents, emulsifier","additive_flags":"Clean"},
    {"barcode":"8904022990023","product_name":"Sandwich Plus","brands":"Various","ingredients_text":"Refined wheat flour, water, sugar, yeast, salt, edible vegetable oil, preservative (INS 282)","additive_flags":"INS 282 preservative"},
    {"barcode":"8904064672215","product_name":"Graines de Pilon (Moringa)","brands":"Various","ingredients_text":"Moringa seeds (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901777041666","product_name":"Frozen Bean","brands":"Vadilal","ingredients_text":"Green beans (frozen)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901848000752","product_name":"Rasana Fruit Plus","brands":"Rasna","ingredients_text":"Sugar, acidity regulators (INS 296, INS 330), salt, anticaking agent (INS 551), vitamin C, permitted colours, artificial flavours","additive_flags":"Verify colours"},
    {"barcode":"8904098970240","product_name":"Joyo Clean Max Cotton Mop","brands":"Joyo","ingredients_text":"NON-FOOD — Cleaning product","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8908012945703","product_name":"Red Lentil Crisps","brands":"Pink Harvest Farms","ingredients_text":"Red lentil flour, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8901662029151","product_name":"Paneer Chilli Mix","brands":"Suhana","ingredients_text":"Paneer, spices, salt, sugar, edible vegetable oil, chilli","additive_flags":"Clean"},
    {"barcode":"8904250303831","product_name":"CAMFLORA Champa and Camphor","brands":"Shubh Kart","ingredients_text":"NON-FOOD — Puja/religious item","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8906006170087","product_name":"Khatta Meetha","brands":"O'yes","ingredients_text":"Rice flakes, edible vegetable oil, sugar, peanuts, sago, salt, spices, raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904004416602","product_name":"Classic Lassi","brands":"Haldiram","ingredients_text":"Toned milk, sugar, active lactic culture","additive_flags":"Clean"},
    {"barcode":"8904150503898","product_name":"Gold Atta","brands":"Pillsbury","ingredients_text":"100% whole wheat flour","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908000863408","product_name":"Oleev Active Oil","brands":"Oleev","ingredients_text":"Rice bran oil, olive oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8902433003790","product_name":"Galaxy Milk Chocolate 110g","brands":"Galaxy","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"8903236265628","product_name":"Kitchen's Promise","brands":"Kitchen's Promise","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8904132963627","product_name":"Good Life Teekhi Chilli Powder","brands":"Good Life","ingredients_text":"Red chilli powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904132963610","product_name":"UB06 Hygienic","brands":"Various","ingredients_text":"NON-FOOD — Verify","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8906009993423","product_name":"Plum Pudding Cake","brands":"Elite","ingredients_text":"Refined wheat flour, sugar, plums, eggs, edible vegetable oil, raising agents, emulsifiers, spices","additive_flags":"Clean"},
    {"barcode":"8901030985980","product_name":"Horlicks Chocolate Delight Flavour","brands":"Horlicks","ingredients_text":"Malted cereals, milk solids, sugar, cocoa solids, wheat flour, minerals, vitamins, emulsifier (INS 471), artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8904063226143","product_name":"Milk Cake","brands":"Haldiram","ingredients_text":"Milk solids (khoya), sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906107173703","product_name":"Pizza Minis","brands":"Prasuma","ingredients_text":"Refined wheat flour, cheese, tomato sauce, vegetables, edible vegetable oil, spices, salt","additive_flags":"Clean"},
    {"barcode":"8901058008494","product_name":"Nestle Koko Krunch 150g","brands":"Nestlé","ingredients_text":"Whole wheat flour, sugar, cocoa solids, glucose syrup, salt, vitamins, minerals","additive_flags":"Clean"},
    {"barcode":"8901779062102","product_name":"Saras","brands":"Saras","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901779900275","product_name":"Biriyani Masala","brands":"Saras","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, cloves, cinnamon, cardamom, bay leaf, nutmeg","additive_flags":"Clean spice blend"},
    {"barcode":"8901779052103","product_name":"Saras Sambar Powder","brands":"Saras","ingredients_text":"Coriander, turmeric, red chilli, fenugreek, cumin, black pepper, mustard, curry leaves","additive_flags":"Clean spice blend"},
    {"barcode":"8906030392776","product_name":"Tamarind","brands":"Various","ingredients_text":"Tamarind (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901779224104","product_name":"Saras Milk Ada Desert","brands":"Saras","ingredients_text":"Rice flakes, milk solids, sugar, cardamom, ghee","additive_flags":"Clean"},
    {"barcode":"8901779900404","product_name":"Saras Jack Fruit Cake","brands":"Saras","ingredients_text":"Jackfruit, refined wheat flour, sugar, eggs, edible vegetable oil, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8904132972339","product_name":"Green Cardamom","brands":"Good Life","ingredients_text":"Green cardamom (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904132917682","product_name":"Green Tea Honey and Lemon","brands":"Aarambh","ingredients_text":"Green tea, honey, lemon flavour","additive_flags":"Clean"},
    {"barcode":"8901262080040","product_name":"Amulspray","brands":"Amul","ingredients_text":"Demineralized whey, vegetable oils, skimmed milk powder, lactose, minerals, vitamins","additive_flags":"Regulated infant food"},
    {"barcode":"8901817671499","product_name":"Honig Madu","brands":"Various","ingredients_text":"Honey (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908018177115","product_name":"Roasted Pistachio","brands":"LGN","ingredients_text":"Roasted pistachios, iodized salt","additive_flags":"Clean"},
    {"barcode":"8906009070926","product_name":"Unibic Choco Rs 5","brands":"Unibic","ingredients_text":"Refined wheat flour, sugar, cocoa solids, edible vegetable oil, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8906097970108","product_name":"Rasam Powder","brands":"JPF","ingredients_text":"Coriander, cumin, turmeric, red chilli, black pepper, mustard, fenugreek, curry leaves","additive_flags":"Clean spice blend"},
    {"barcode":"8906054110721","product_name":"Good Bread","brands":"Various","ingredients_text":"Refined wheat flour, water, sugar, yeast, salt, edible vegetable oil, preservative (INS 282)","additive_flags":"INS 282 preservative"},
    {"barcode":"8901888004833","product_name":"Real Mosambi Fruit Juice","brands":"Real","ingredients_text":"Water, mosambi (sweet lime) juice concentrate, sugar, acidity regulator (INS 330), antioxidant (INS 300)","additive_flags":"Clean"},
    {"barcode":"8901393024234","product_name":"Juzt Jelly Strawberry","brands":"Alpenliebe","ingredients_text":"Sugar, glucose syrup, gelatin, strawberry flavour, acidity regulator, colours","additive_flags":"Verify colours"},
    {"barcode":"8906003210731","product_name":"Zinfandel Rosewein","brands":"Sulawesi Vineyards","ingredients_text":"Alcoholic beverage (wine)","additive_flags":"ALCOHOL — SEPARATE"},
    {"barcode":"8906069610247","product_name":"Jolliz Salty Chunks Moong Dal","brands":"Anand","ingredients_text":"Moong dal, edible vegetable oil, iodized salt, spices","additive_flags":"Clean"},
    {"barcode":"8908002105117","product_name":"Brown Bread","brands":"BakesFresh","ingredients_text":"Whole wheat flour, water, sugar, yeast, salt, edible vegetable oil, preservative (INS 282)","additive_flags":"INS 282 preservative"},
    {"barcode":"8904063204202","product_name":"Khatta Dhokla","brands":"Haldiram's","ingredients_text":"Gram flour, water, sugar, salt, spices, edible vegetable oil, raising agents","additive_flags":"Clean"},
    {"barcode":"8906154300329","product_name":"Aloo Bujia","brands":"Various","ingredients_text":"Potato flakes & starch, edible vegetable oil, gram flour, iodized salt, spices, colour (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8901262153270","product_name":"Amul Tru Orange Juice 150ml","brands":"Amul","ingredients_text":"Orange juice, water, sugar, acidity regulator (INS 330), antioxidant (INS 300)","additive_flags":"Clean"},
    {"barcode":"8901542003158","product_name":"Complan Rich Chocolate Flavour","brands":"Complan","ingredients_text":"Milk solids (52%), sugar, cocoa solids, maltodextrin, almonds, minerals, vitamins, colours (INS 100(i), INS 160b(ii))","additive_flags":"Natural colours"},
    {"barcode":"8901030976117","product_name":"Horlicks Classic Malt","brands":"Horlicks","ingredients_text":"Malted cereals (66.7%), milk solids (14%), sugar, wheat gluten, iodized salt, minerals, vitamins, emulsifier (INS 471)","additive_flags":"Clean"},
    {"barcode":"8901803001145","product_name":"Amrutanjan","brands":"Amrutanjan","ingredients_text":"NON-FOOD — Pain relief balm","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8906001050643","product_name":"Mathers Mango Pickle 200g","brands":"Mathers","ingredients_text":"Raw mango, salt, spices, edible vegetable oil, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8901155113114","product_name":"Gits Vermicelli Kheer","brands":"Gits","ingredients_text":"Vermicelli (durum wheat semolina), milk solids, sugar, cardamom, ghee, raisins","additive_flags":"Clean"},
    {"barcode":"8901808004554","product_name":"Chocolate Cake Premix","brands":"Weikfield","ingredients_text":"Sugar, refined wheat flour, cocoa solids, salt, raising agents, emulsifiers, artificial chocolate flavour","additive_flags":"Clean"},
    {"barcode":"8904208600951","product_name":"Paneer Makhanwala Premix","brands":"Rasao Suhana","ingredients_text":"Paneer, tomato, butter, cream, spices, salt, sugar, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901030966132","product_name":"Dark Soya Sauce","brands":"Knorr","ingredients_text":"Water, soybean extract, salt, sugar, vinegar, acidity regulator, preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8904037247600","product_name":"Rolled Oats","brands":"Soulful","ingredients_text":"Oats (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901058895735","product_name":"Maggi Ketchup Rich","brands":"Maggi","ingredients_text":"Tomato paste, sugar, water, vinegar, salt, spices, acidity regulator (INS 260), preservative (INS 211)","additive_flags":"INS 211 preservative"},
    {"barcode":"8906007280655","product_name":"Fortune Cotton Seed Oil","brands":"Fortune","ingredients_text":"Refined cotton seed oil, antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8901441011049","product_name":"Lijjat Papad","brands":"Lijjat","ingredients_text":"Urad dal flour, salt, spices (black pepper, cumin), edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8901042970868","product_name":"Mutter Paneer Ready Masala","brands":"MTR","ingredients_text":"Paneer, green peas, tomato, spices, salt, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8904145912650","product_name":"Similac Advance","brands":"Abbott","ingredients_text":"NON-FOOD — Infant formula/medicine","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8902901027990","product_name":"Good Life MP Wheat Chakki Atta 5kg","brands":"Good Life","ingredients_text":"100% whole wheat flour (MP wheat)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904132948563","product_name":"Filtered Groundnut Oil","brands":"Independence","ingredients_text":"Groundnut oil (filtered), antioxidant (INS 319), vitamins A & D","additive_flags":"INS 319 TBHQ"},
    {"barcode":"8906058611569","product_name":"Gaia Dark Choco Chip","brands":"Gaia","ingredients_text":"Sugar, cocoa solids, cocoa butter, emulsifier (INS 322), artificial vanilla flavour","additive_flags":"Clean"},
    {"barcode":"8901023018411","product_name":"Aer Spray","brands":"Godrej","ingredients_text":"NON-FOOD — Air freshener","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901207040450","product_name":"Roghan Badam Shireen","brands":"Dabur","ingredients_text":"Almond oil (sweet)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906072845483","product_name":"Roasted Peanut","brands":"Jack & Jill","ingredients_text":"Roasted peanuts, iodized salt","additive_flags":"Clean"},
    {"barcode":"8904132968813","product_name":"Roasted & Salted Cashews","brands":"Snactac","ingredients_text":"Cashew nuts, iodized salt","additive_flags":"Clean"},
    {"barcode":"8902979042987","product_name":"Mango Thokku","brands":"Various","ingredients_text":"Raw mango, salt, red chilli, edible vegetable oil, mustard, fenugreek","additive_flags":"Clean"},
    {"barcode":"8901207024856","product_name":"Chat Cola","brands":"Hajmola","ingredients_text":"Spices (black salt, cumin, amchur, red chilli), salt, sugar, cola flavour, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8904132918214","product_name":"Besan Ladoo","brands":"Snactac","ingredients_text":"Gram flour (besan), sugar, ghee, cardamom","additive_flags":"Clean"},
    {"barcode":"8906010070144","product_name":"Ganesh Mummy's Own","brands":"Ganesh Mummy's Own","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8905507035567","product_name":"Maida","brands":"First Crop","ingredients_text":"Refined wheat flour (maida)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8905507025087","product_name":"Rajma Red","brands":"First Crop","ingredients_text":"Rajma (kidney beans)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906040250240","product_name":"Dates","brands":"Various","ingredients_text":"Dates (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906044443501","product_name":"Coffee Crunchettes","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8901155413313","product_name":"Gits Ready Meals - Paneer Tikka Masala","brands":"Gits","ingredients_text":"Paneer, tomato, spices, salt, edible vegetable oil, cream","additive_flags":"Clean"},
    {"barcode":"8902901222999","product_name":"Till Nylon 100gm","brands":"Good Life","ingredients_text":"Sesame seeds (till)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8901192108029","product_name":"Catch Jeera Powder 50g","brands":"Catch","ingredients_text":"Cumin powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8903236700244","product_name":"Coffee Booster","brands":"Cosmix","ingredients_text":"Coffee blend, herbal extracts, spices","additive_flags":"Clean"},
    {"barcode":"8901786191000","product_name":"Everest Super Garam Masala","brands":"Everest","ingredients_text":"Coriander, cumin, black pepper, cloves, cinnamon, cardamom, bay leaf, nutmeg, mace","additive_flags":"Clean spice blend"},
    {"barcode":"8906011730542","product_name":"Ashiver","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8904137452515","product_name":"Chukde Poppy Seeds","brands":"Chukde","ingredients_text":"Poppy seeds (khus khus)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908002753264","product_name":"Double Toned Milk","brands":"Red Cow","ingredients_text":"Double toned milk, vitamins A & D","additive_flags":"Clean"},
    {"barcode":"8903151720112","product_name":"Laxminarayan Potato Chiwda","brands":"Laxminarayan","ingredients_text":"Potato, edible vegetable oil, peanuts, sago, salt, spices, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8902433009303","product_name":"Snickers","brands":"Snickers","ingredients_text":"Sugar, peanuts, glucose syrup, milk solids, cocoa butter, cocoa mass, emulsifiers, salt","additive_flags":"Clean"},
    {"barcode":"8901393018530","product_name":"Alpenliebe Just Jelly","brands":"Just Jelly","ingredients_text":"Sugar, glucose syrup, gelatin, fruit flavour, acidity regulator, colours","additive_flags":"Verify colours"},
    {"barcode":"8901719107665","product_name":"Biskit","brands":"Parle","ingredients_text":"Refined wheat flour, sugar, edible vegetable oil, invert syrup, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8901389001898","product_name":"Cacao Reserve Belgium Melt","brands":"Sos Save Our Souls","ingredients_text":"Sugar, cocoa solids, cocoa butter, milk solids, emulsifiers, flavours","additive_flags":"Clean"},
    {"barcode":"8905672622333","product_name":"Fasola Biała Konser","brands":"Moc Warzyw Dino","ingredients_text":"White beans, water, salt","additive_flags":"Clean"},
    {"barcode":"8908026382006","product_name":"Tofu","brands":"Mothers Nature","ingredients_text":"Soybean, water, coagulant","additive_flags":"Clean"},
    {"barcode":"8906084381597","product_name":"Classic Bhakharwadi","brands":"Jagdish","ingredients_text":"Refined wheat flour, gram flour, edible vegetable oil, spices, salt, sugar, coconut, sesame seeds","additive_flags":"Clean"},
    {"barcode":"8903023006078","product_name":"Kabuli Chana","brands":"Vedaka","ingredients_text":"Kabuli chana (white chickpeas)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906150460034","product_name":"Roasted Salted Magic Mix","brands":"Sao Foods","ingredients_text":"Mixed nuts, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8901874131420","product_name":"Valor Papdi","brands":"Kitchen Xpress","ingredients_text":"Refined wheat flour, edible vegetable oil, salt, spices","additive_flags":"Clean"},
    {"barcode":"8906141461484","product_name":"Mixed Veg","brands":"Vimal","ingredients_text":"Mixed vegetables (frozen)","additive_flags":"Clean"},
    {"barcode":"8904063229885","product_name":"Cheese Balls","brands":"Minute Khana","ingredients_text":"Corn flour, edible vegetable oil, cheese powder, salt, spices, flavour enhancers","additive_flags":"Clean"},
    {"barcode":"8901148248878","product_name":"Stamlo 5","brands":"Various","ingredients_text":"NON-FOOD — Medicine","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8906108190198","product_name":"Chunky Butter Chicken Spread","brands":"Licious","ingredients_text":"Chicken, butter, tomato, cream, spices, salt, sugar, edible vegetable oil","additive_flags":"Clean"},
    {"barcode":"8909509926731","product_name":"Kinder Sorpresa","brands":"Kinder","ingredients_text":"Sugar, milk solids, cocoa butter, cocoa mass, emulsifiers, flavours, toy inside","additive_flags":"Clean"},
    {"barcode":"8901725101435","product_name":"Jalimals","brands":"Various","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8904022900084","product_name":"Brown Bread","brands":"Various","ingredients_text":"Whole wheat flour, water, sugar, yeast, salt, edible vegetable oil, preservative (INS 282)","additive_flags":"INS 282 preservative"},
    {"barcode":"8904063210678","product_name":"Roasted Crushed Peanuts","brands":"Haldiram's","ingredients_text":"Roasted peanuts (crushed), iodized salt","additive_flags":"Clean"},
    {"barcode":"8901155115415","product_name":"Dahi Vada Mix","brands":"Gits","ingredients_text":"Urad dal flour, spices, salt, raising agents","additive_flags":"Clean"},
    {"barcode":"8907931000449","product_name":"Garden Veggie Straws","brands":"Various","ingredients_text":"Potato starch, potato flour, edible vegetable oil, salt, spinach powder, tomato powder","additive_flags":"Clean"},
    {"barcode":"8906057810062","product_name":"Spicy Plantain Chips","brands":"Various","ingredients_text":"Plantain, edible vegetable oil, spices, iodized salt","additive_flags":"Clean"},
    {"barcode":"8904011502541","product_name":"Jaggery Powder","brands":"Double Horse","ingredients_text":"Jaggery powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904293731691","product_name":"Indie Flavours Bombay Mixture","brands":"Indie Flavours/Flipkart","ingredients_text":"Rice flakes, gram flour, edible vegetable oil, peanuts, sago, salt, spices, raising agents, colours (INS 160c)","additive_flags":"INS 160c colour"},
    {"barcode":"8904084900633","product_name":"Imitation Snow Crab","brands":"Various","ingredients_text":"Surimi (fish paste), starch, salt, sugar, egg white, crab flavour, colours","additive_flags":"Clean"},
    {"barcode":"8906080601576","product_name":"Aam Padpad","brands":"Paper Boat","ingredients_text":"Water, mango pulp, sugar, acidity regulators","additive_flags":"Clean"},
    {"barcode":"8904215501661","product_name":"ujoygnhyyhyyhhggyhhh","brands":"ducthv","ingredients_text":"NON-FOOD — Invalid/nonsense entry","additive_flags":"NON-FOOD — PURGE"},
    {"barcode":"8901205027705","product_name":"White Tea","brands":"Various","ingredients_text":"White tea (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906002770694","product_name":"Mini Classic Cold Coffee","brands":"Various","ingredients_text":"Instant coffee, sugar, milk solids, emulsifier, flavours","additive_flags":"Clean"},
    {"barcode":"8908020709007","product_name":"Elemental Manga+","brands":"ELEMENTAL","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8906165783906","product_name":"Biozyme Performance Whey","brands":"MuscleBlaze","ingredients_text":"Whey protein concentrate, emulsifier (INS 322), artificial flavour, sweetener","additive_flags":"Clean"},
    {"barcode":"8906055442524","product_name":"Organic Tattva Mustard Oil","brands":"Organic Tattva","ingredients_text":"Organic mustard oil (cold-pressed)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904391593333","product_name":"Mango Mallika","brands":"Unknown Brand","ingredients_text":"Mango (Mallika variety)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906135071453","product_name":"Millet Cereal","brands":"Native Food Store","ingredients_text":"Millet flour, raising agents, salt","additive_flags":"Clean"},
    {"barcode":"8901440210795","product_name":"Turmeric Powder","brands":"Eastern","ingredients_text":"Turmeric powder (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8908008116018","product_name":"Um Rupa","brands":"M/S Marwein Group","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8906033740208","product_name":"McVitie's TASTIES BUTTER COOKIES","brands":"McVitie's","ingredients_text":"Refined wheat flour, sugar, butter, edible vegetable oil, raising agents, emulsifiers, artificial butter flavour","additive_flags":"Clean"},
    {"barcode":"8908001551007","product_name":"KOKANRAJ KOKUM SYRUP","brands":"KOKANRAJ","ingredients_text":"Kokum extract, sugar, water, acidity regulator","additive_flags":"Clean"},
    {"barcode":"8902901224726","product_name":"Toor Dal 500g","brands":"Good Life","ingredients_text":"Toor dal (pigeon pea)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906009820323","product_name":"Silver Coin Suji","brands":"Silver Coin","ingredients_text":"Semolina (suji/rava) from wheat","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906167310643","product_name":"Arhar Dal 1kg","brands":"Various","ingredients_text":"Arhar/Toor dal (pigeon pea)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8902901224733","product_name":"Toor Dal 1kg","brands":"Good Life","ingredients_text":"Toor dal (pigeon pea)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8904089920629","product_name":"Curd","brands":"Heritage","ingredients_text":"Pasteurised toned milk & active lactic cultures","additive_flags":"Clean"},
    {"barcode":"8906005618603","product_name":"Mini Swiss Roll (Choco-Vanilla) [10 Rs]","brands":"Winkles","ingredients_text":"Refined wheat flour, sugar, eggs, edible vegetable oil, cocoa solids, vanilla flavour, raising agents, emulsifiers","additive_flags":"Clean"},
    {"barcode":"8904335601326","product_name":"Chia Seeds","brands":"Yogabar","ingredients_text":"Chia seeds (100%)","additive_flags":"Clean single-ingredient"},
    {"barcode":"8906079010334","product_name":"Luvit Pops!","brands":"Luvit","ingredients_text":"Verify specific product","additive_flags":"Verify"},
    {"barcode":"8904132972469","product_name":"Good Life Till White 200g","brands":"Good Life","ingredients_text":"White sesame seeds (till)","additive_flags":"Clean single-ingredient"}
]

elevated_count = 0
added_count = 0
purged_count = 0

for item in batch_42_rows:
    barcode = str(item["barcode"]).strip()
    pname = item["product_name"].strip()
    brand = item["brands"].strip()
    ing = item["ingredients_text"].strip()
    flags = item.get("additive_flags", "")
    
    # Check if non-food
    if "NON-FOOD" in ing.upper() or "NON-FOOD" in flags.upper() or "PURGE" in flags.upper():
        df_all = df_all[df_all['barcode'] != barcode]
        df_confirmed = df_confirmed[df_confirmed['barcode'] != barcode]
        df_needs_ver = df_needs_ver[df_needs_ver['barcode'] != barcode]
        purged_count += 1
        continue

    # Update or add in master DB
    idx_all = df_all[df_all['barcode'] == barcode].index
    status_tag = 'CONFIRMED_INDIA_890' if barcode.startswith('890') else 'CONFIRMED_FOREIGN'
    if len(idx_all) > 0:
        df_all.loc[idx_all, 'product_name'] = pname
        df_all.loc[idx_all, 'brands'] = brand
        df_all.loc[idx_all, 'ingredients_text'] = ing
    else:
        new_row = {
            'barcode': barcode,
            'product_name': pname,
            'brands': brand,
            'ingredients_text': ing,
            'sold_in_india_status': status_tag,
            'ingredient_confidence': 'HIGH',
            'status': 'KEEP',
            'data_source': 'Brand Official Publication',
            'source_license': 'User-submitted',
            'collection_method': 'API/CSV Import'
        }
        df_all = pd.concat([df_all, pd.DataFrame([new_row])], ignore_index=True)

    # Check if in needs_ver, promote to confirmed
    idx_nv = df_needs_ver[df_needs_ver['barcode'] == barcode].index
    if len(idx_nv) > 0:
        df_needs_ver = df_needs_ver[df_needs_ver['barcode'] != barcode]
        elevated_count += 1

    # Upsert in confirmed
    idx_c = df_confirmed[df_confirmed['barcode'] == barcode].index
    if len(idx_c) > 0:
        df_confirmed.loc[idx_c, 'product_name'] = pname
        df_confirmed.loc[idx_c, 'brands'] = brand
        df_confirmed.loc[idx_c, 'ingredients_text'] = ing
        df_confirmed.loc[idx_c, 'sold_in_india_status'] = status_tag
        df_confirmed.loc[idx_c, 'ingredient_confidence'] = 'HIGH'
        df_confirmed.loc[idx_c, 'status'] = 'KEEP'
    else:
        conf_row = {
            'barcode': barcode,
            'product_name': pname,
            'brands': brand,
            'ingredients_text': ing,
            'sold_in_india_status': status_tag,
            'ingredient_confidence': 'HIGH',
            'status': 'KEEP',
            'data_source': 'Brand Official Publication',
            'source_license': 'User-submitted',
            'collection_method': 'API/CSV Import'
        }
        df_confirmed = pd.concat([df_confirmed, pd.DataFrame([conf_row])], ignore_index=True)
        added_count += 1

# Save updated files
df_all.to_csv(all_supabase_csv, index=False)
df_confirmed.to_csv(confirmed_csv, index=False)
df_needs_ver.to_csv(needs_ver_csv, index=False)

print(f"Batch 42 Processing Summary:")
print(f"  Elevated from Needs Verification to Confirmed: {elevated_count}")
print(f"  Newly added to Confirmed: {added_count}")
print(f"  Purged Non-Food Barcodes: {purged_count}")
print(f"  Final Master CSV Count: {len(df_all)}")
print(f"  Final Confirmed CSV Count: {len(df_confirmed)}")
print(f"  Final Needs Verification CSV Count: {len(df_needs_ver)}")
